Fix wrong decoding on ConfigPushSvc and update default server list
mamoe/mirai pull request #1015
Opened 2021-02-11 15:24 UTC by sandtechnology

2021-02-11 16:03 UTC, Karlatemp requested changes
感谢你的帮助

----

请统一一下命名

2021-02-11 16:03 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/ConfigPushSvc.kt
> +            }
统一命名

2021-02-11 16:03 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/ConfigPushSvc.kt
> +                val serverListPush = kotlin.runCatching {
统一命名

2021-02-11 16:03 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/ConfigPushSvc.kt
>                  }
统一命名

2021-02-11 17:01 UTC, Karlatemp approved these changes

2021-02-12 06:21 UTC, Him188 requested changes

2021-02-12 06:21 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/ConfigPushSvc.kt
> +                bot.logger.info { "Server send a new server list." }
```suggestion
                bot.network.logger.info { "Server list updated." }
```

2021-02-12 08:31 UTC, Him188 approved these changes

2021-02-13 03:34 UTC, merged