Correct group sync and add friend sync, fix #1058
mamoe/mirai pull request #1060
Opened 2021-02-27 13:10 UTC by sandtechnology

2021-02-27 15:08 UTC, Karlatemp requested changes

2021-02-27 15:08 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/list/FriendList.kt
> +        ): OutgoingPacket {
```suggestion

        fun forSingleFriend(
            client: QQAndroidClient,
            uin: Long
        ): OutgoingPacket {
```

2021-02-27 15:08 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                                    .sendAndExpect(bot)
```suggestion
                            val response: FriendList.GetFriendGroupList.Response =
                                FriendList.GetFriendGroupList.forSingleFriend(
                                    bot.client,
                                    msg.msgFriendMsgSync.fuin
                                ).sendAndExpect(bot)
```

2021-02-27 15:11 UTC, Karlatemp approved these changes

2021-02-27 18:29 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                        bot.network.launch {
why `launch`

2021-02-27 18:39 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                        bot.network.launch {
需要在网络发包（ 是要换成run吗

2021-02-27 19:30 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                        bot.network.launch {
run，或者使用 bot.sendAndExpect，或者 network.sendAndExpect

2021-02-27 19:30 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                        bot.network.launch {
有一些扩展可以避免run

2021-03-01 02:12 UTC, Him188 approved these changes

2021-03-05 06:12 UTC, merged