File transfer
mamoe/mirai pull request #1069
Opened 2021-03-03 04:43 UTC by Him188

Close #805 
相关 #861

2021-03-03 04:45 UTC, Him188 commented
- upload, download, send, forward
- list, move, mkdir, delete, rename

2021-03-03 04:49 UTC, Him188 commented
部分协议来自 https://github.com/Mrs4s/MiraiGo/commit/14ebb9cdcd81f8ed3edb9bc5a4b95f48655b0f03

2021-03-03 04:55 UTC, Him188 commented
实现的功能已经全部完成测试, 已知问题:
- [ ] `move` 目录没有移动其子文件
- [ ] 引用回复文件消息时官方客户端无法定位 (而官方客户端可以定位到官方文件消息)

目前还没有确定的是 `RemoteFile.write`. 
1. 需要提供一个方式来获取上传进度. 
2. `write` 命名可能不合适
2. 可能要上传(`write`)后不发送 feed (文件消息), 让用户自行通过 `toMessage()` 后发送

待完成:
 - [ ] `ExternalResource`, `Contact` 的相关扩展 (待确认)

2021-03-03 10:30 UTC, sandtechnology commented
`write`操作应该是内部的？通过`Group.uploadFile`然后返回`RemoteFile`如何？
以及我觉得`uploadFile`函数应该给一个是否发送文件信息的选项 或者直接包装成含`RemoteFile`的`Message`？

2021-03-03 10:34 UTC, Karlatemp commented
`write` 命名为 `upload` 更好? 鉴于文件的特殊性 上传后不发送 feed (文件消息) 可以考虑放置于 `IMirai` 内

2021-03-04 10:35 UTC, Karlatemp requested changes

2021-03-04 10:35 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
> +    public suspend fun upload(resource: ExternalResource): Boolean = upload(resource, null)
```
上传后不会发送文件消息, 即官方客户端只能在 "群文件" 中查看文件. 可通过 [toMessage] 获取到文件消息并通过 [Group.sendMessage] 发送. 或使用
```
文档不完整

2021-03-04 10:35 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
> +    }
实际操作与 `RemoteFile.uploadAndSend` 不一致

2021-03-04 15:15 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/highway/FileHighway.kt
> +
这个空文件可以删除?

2021-03-04 15:15 UTC, Karlatemp commented on mirai-core/src/commonTest/kotlin/internal/utils/FileSystemTest.kt
> +    }
空 test

2021-03-05 09:26 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
> +    public suspend fun uploadAndSend(file: File): Boolean = file.toExternalResource().use { uploadAndSend(it) }
返回类型与 `public suspend fun <C : FileSupported> C.uploadFileAndSend(...): MessageReceipt<C>` 不一致也许会产生疑惑, 建议返回类型保持一致, 或者添加一个新的方法/修改返回类型

```kotlin
// public companion object
public suspend fun <C : FileSupported> C.uploadFileAndSend(
            path: RemoteFile,
            resource: ExternalResource
): MessageReceipt<C>

// or
public suspend fun uploadAndSend(file: File): MessageReceipt<FileSupported>?
```

2021-03-05 09:26 UTC, Karlatemp approved these changes

2021-03-05 10:31 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
> +    public suspend fun uploadAndSend(file: File): Boolean = file.toExternalResource().use { uploadAndSend(it) }
MR返回值的是后一天写的，前一天写的Z返回值没有考虑周全

2021-03-08 10:34 UTC, merged