Compiled code verify
mamoe/mirai pull request #1080
Opened 2021-03-08 09:25 UTC by Karlatemp

相关issue #1078

2021-03-08 10:07 UTC, Him188 commented
verity? verify?

2021-03-10 00:06 UTC, Him188 commented
KJBB 1.10.2 应该修复了，可以测试了

2021-03-10 00:08 UTC, Him188 commented on .github/workflows/release.yml
> +        run: ./gradlew verifyCompiledClasses --scan
把他添加到 `check`

2021-03-14 10:07 UTC, blindpirate requested changes
`verifyCompiledClasses`定义真的可以改进。。。

2021-03-14 10:07 UTC, blindpirate commented on build.gradle.kts
> +        }.map { project ->
```suggestion
       projects.mapNotNull { findProject(it) }
            .map { project: Project ->
```

我注意到很多地方用`runCatching`来选择性地执行`project()`，其实有个`findProject` API可以用的。

2021-03-14 10:07 UTC, blindpirate commented on build.gradle.kts
> +                }.map { it.files.asSequence() }.flatten()
```suggestion
                    val libs = classpath.flatMap {
                        project.configurations.findByName(it)?.files ?: emptyList()
                    }
```

- `asSequence`很多地方没有必要，不明白为啥要加
- `flatMap` API请了解一下
- `NamedObjectCollection.findByName` API请了解一下

2021-03-14 10:07 UTC, blindpirate commented on build.gradle.kts
> +            ).map { (targetClasses, classpath) ->
```suggestion
                ).map { (targetClasses: List<String>, classpath: List<String>) ->
```

这个代码对可读性是灾难，如果一定要这么做，请最起码加上类型声明，不过，还是十分希望把这部分代码拿出来成为单独的方法。另外，`runtimeClasspath`是`Configuration`的名字，建议叫`configurationNames`。

2021-03-14 10:07 UTC, blindpirate commented on build.gradle.kts
> +        }
我看了很久才弄清楚这里是两层list，用`flatMap`化简如下：

版本一：

```
        projects.mapNotNull { findProject(it) }
            .flatMap { project: Project ->
                val classesDir = project.buildDir.resolve("classes")
                listOf(
                    listOf("kotlin/main", "kotlin/jvm/main") to listOf("runtimeClasspath", "jvmRuntimeClasspath"),
                    listOf("kotlin/main", "kotlin/android/main") to listOf(
                        "runtimeClasspath",
                        "androidRuntimeClasspath"
                    )
                ).map { (targetClasses: List<String>, classpath: List<String>) ->
                    val libs: List<File> = classpath.flatMap {
                        project.configurations.findByName(it)?.files ?: emptyList()
                    }
                    val sources: List<File> = targetClasses.map { classesDir.resolve(it) }.filter { it.isDirectory }
                    sources to libs
                }
            }.forEach { (sources: List<File>, libs: List<File>) ->
                analyzes.NoSuchMethodAnalyzer.check(sources.asSequence(), libs.asSequence())
            }
```

版本二：

```
        projects.mapNotNull { findProject(it) }
            .forEach { project: Project ->
                val classesDir = project.buildDir.resolve("classes")
                listOf(
                    listOf("kotlin/main", "kotlin/jvm/main") to listOf("runtimeClasspath", "jvmRuntimeClasspath"),
                    listOf("kotlin/main", "kotlin/android/main") to listOf(
                        "runtimeClasspath",
                        "androidRuntimeClasspath"
                    )
                ).forEach { (targetClasses: List<String>, classpath: List<String>) ->
                    val libs: List<File> = classpath.flatMap {
                        project.configurations.findByName(it)?.files ?: emptyList()
                    }
                    val sources: List<File> = targetClasses.map { classesDir.resolve(it) }.filter { it.isDirectory }
                    analyzes.NoSuchMethodAnalyzer.check(sources.asSequence(), libs.asSequence())
            }
```

2021-03-14 10:07 UTC, blindpirate commented on build.gradle.kts
> +    }
这一坨都可以合并到`register(){}`的花括号里，为啥要拿出来？

2021-03-14 10:07 UTC, blindpirate commented on build.gradle.kts
> +    }
Plus, 

```
    listOf("mirai-console", "mirai-console-terminal")
        .filter { findProject(it) != null }
        .forEach { jvmProject ->
            mustRunAfter(":$jvmProject:classes")
        }
```

2021-03-14 10:14 UTC, blindpirate commented
那个庞大的任务定义如果是我，可能会写成这样，把逻辑拆出来成为一个extension function，或者，我觉得`verifyCompiledClasses`应该定义在每个目标`Project`中，即：`mirai-core-api:verifyCompiledClasses`, etc. 而不是root project里一个庞大的`verifyCompiledClasses` task。

```
fun Project.verifyCompileClasses(targetClasses: List<String>, configurationNames: List<String>) {
    val classesDir = buildDir.resolve("classes")

    val libs: List<File> = configurationNames.flatMap {
        project.configurations.findByName(it)?.files ?: emptyList()
    }
    val sources: List<File> = targetClasses.map { classesDir.resolve(it) }.filter { it.isDirectory }
    analyzes.NoSuchMethodAnalyzer.check(sources.asSequence(), libs.asSequence()) 
}


tasks.register("verifyCompiledClasses") {
    val projects = listOf("mirai-core-api", "mirai-core-utils", "mirai-console", "mirai-console-terminal")
    group = "verification"
    doFirst {
        projects.mapNotNull { findProject(it) }
            .forEach {
                it.verifyCompileClasses(listOf("kotlin/main", "kotlin/jvm/main"), listOf("runtimeClasspath", "jvmRuntimeClasspath"))
                it.verifyCompileClasses(listOf("kotlin/main", "kotlin/android/main"), listOf("runtimeClasspath", "androidRuntimeClasspath"))
            }
    }
    dependsOn("check")
    listOf("mirai-core-api", "mirai-core-utils").forEach { mppProject ->
        mustRunAfter(":$mppProject:jvmMainClasses")
        mustRunAfter(":$mppProject:androidMainClasses")
    }
    listOf("mirai-console", "mirai-console-terminal")
        .filter { findProject(it) != null }
        .forEach { jvmProject ->
            mustRunAfter(":$jvmProject:classes")
        }
}
```

2021-03-14 10:19 UTC, blindpirate commented on buildSrc/src/main/kotlin/analyzes/AsmUtil.kt
> +object AsmUtil {
弱弱的问一下，这些方法有测试么……

2021-03-14 10:29 UTC, Karlatemp commented
@blindpirate 十分感谢你的帮助，我会根据你的建议进行修改

2021-03-14 16:16 UTC, Karlatemp commented on buildSrc/src/main/kotlin/analyzes/AsmUtil.kt
> +object AsmUtil {
是有进行测试的

2021-03-15 02:41 UTC, blindpirate commented on buildSrc/src/main/kotlin/analyzes/AsmUtil.kt
> +object AsmUtil {
@Karlatemp 可否指给我测试代码的位置？

2021-03-15 03:14 UTC, Karlatemp commented on buildSrc/src/main/kotlin/analyzes/AsmUtil.kt
> +object AsmUtil {
本地测试，此工具类逻辑正确我还是有信心保证的

2021-03-15 03:23 UTC, Him188 commented on buildSrc/src/main/kotlin/analyzes/AsmUtil.kt
> +object AsmUtil {
最好还是写 unit test，如果出了问题就可能会导致 binary 不兼容

2021-03-17 15:54 UTC, Karlatemp commented
- [ ] Mirai-Console

```
> Task :mirai-console:verify_NoNoSuchMethodError
> net/mamoe/mirai/console/command/descriptor/AbstractCommandValueArgumentParser.class
    > Analyze illegalArgument(Lnet/mamoe/mirai/console/command/descriptor/CommandValueArgumentParser;Ljava/lang/String;Ljava/lang/Throwable;)Ljava/lang/Void;
          No such method: net/mamoe/mirai/console/command/descriptor/AbstractCommandValueArgumentParser$Companion.access$illegalArgument(Lnet/mamoe/mirai/console/command/descriptor/AbstractCommandValueArgumentParser$Companion;Lnet/mamoe/mirai/console/command/descriptor/CommandValueArgumentParser;Ljava/lang/String;Ljava/lang/Throwable;)Ljava/lang/Void;, opcode=184
    > Analyze checkArgument(Lnet/mamoe/mirai/console/command/descriptor/CommandValueArgumentParser;ZLkotlin/jvm/functions/Function0;)V
          No such method: net/mamoe/mirai/console/command/descriptor/AbstractCommandValueArgumentParser$Companion.access$checkArgument(Lnet/mamoe/mirai/console/command/descriptor/AbstractCommandValueArgumentParser$Companion;Lnet/mamoe/mirai/console/command/descriptor/CommandValueArgumentParser;ZLkotlin/jvm/functions/Function0;)V, opcode=184
```

https://github.com/mamoe/mirai-console/blob/da32c90eed36ff8281ad0d2257c31efd89661ab3/backend/mirai-console/src/command/descriptor/CommandValueArgumentParser.kt#L115-L150


```kotlin
public abstract class AbstractCommandValueArgumentParser<T : Any> : CommandValueArgumentParser<T> {
    public companion object {
        @JvmStatic
        @JvmSynthetic
        protected inline fun CommandValueArgumentParser<*>.illegalArgument(message: String, cause: Throwable? = null): Nothing

        @JvmStatic
        @JvmSynthetic
        protected inline fun CommandValueArgumentParser<*>.checkArgument(
            condition: Boolean,
            crossinline message: () -> String = { "Check failed." },
        )
    }
}
```

2021-03-18 01:07 UTC, Him188 commented on buildSrc/src/main/kotlin/analyzes/NoSuchMethodAnalyzer.kt
> +                        method.instructions?.forEach { insn ->
可以(?)提一个 fun 叫 `verifyMethod` 来减少缩进层数

2021-03-18 04:33 UTC, Him188 approved these changes

2021-03-18 04:41 UTC, Him188 commented
Rebase onto or merge from dev?

2021-03-18 04:43 UTC, Karlatemp commented
> Rebase onto or merge from dev?

Merge? rebase maybe need force push

2021-03-18 04:44 UTC, Him188 commented
> > Rebase onto or merge from dev?
> 
> Merge? rebase maybe need force push

总是会被 squash, 都行

2021-03-20 05:34 UTC, merged