Make ForwardMessageBuilder easier to use for Java, close #1087
mamoe/mirai pull request #1089
Opened 2021-03-10 02:32 UTC by Him188

2021-03-10 14:49 UTC, Karlatemp reviewed
Java 也可以使用 `builder.named(123456789L, "Nick").says(....);` 调用 KotlinDSL 的方法, 可以在注释中说明

2021-03-10 15:00 UTC, Him188 commented
> Java 也可以使用 `builder.named(123456789L, "Nick").says(....);` 调用 KotlinDSL 的方法, 可以在注释中说明

感觉没有 add 好，还是首选标准的方式

2021-03-11 15:02 UTC, Karlatemp requested changes

2021-03-11 15:02 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/ForwardMessage.kt
> +
`@since 2.6`

2021-03-11 15:02 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/ForwardMessage.kt
> +
`@since 2.6`

2021-03-18 04:03 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/ForwardMessage.kt
> +    }
```suggestion
    @JvmOverloads
    public fun add(senderId: Long, senderName: String, message: Message, time: Int = -1): ForwardMessageBuilder {
        return if (time == -1) senderId named senderName says message
        else senderId named senderName at time says message
    }
```

2021-03-18 04:08 UTC, Karlatemp approved these changes

2021-03-22 04:12 UTC, merged