Add more extensions for RemoteFile and ExternalResource, update docs
mamoe/mirai pull request #1105
Opened 2021-03-18 05:53 UTC by Him188

2021-03-18 14:20 UTC, Karlatemp requested changes

2021-03-18 14:20 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
> +
```suggestion
    /**
     * 获取该目录下所有文件, 返回的 [RemoteFile] 都拥有 [RemoteFile.id] 用于区分重名文件或目录. 当 [RemoteFile] 表示一个文件时返回 [emptyList].
     */
    public suspend fun listFilesCollection(): List<RemoteFile> = listFiles().toList()

```

2021-03-19 03:16 UTC, Karlatemp approved these changes

2021-03-19 04:32 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
> +        public suspend fun <C : FileSupported> C.uploadFileAndSend(
是否叫 `sendFile` 好? 类似图片的 `sendImage`

2021-03-20 05:41 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
> +        public suspend fun <C : FileSupported> C.uploadFileAndSend(
@Karlatemp

2021-03-20 05:45 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/RemoteFile.kt
> +        public suspend fun <C : FileSupported> C.uploadFileAndSend(
我认为最好和 `RemoteFile` 内的 `uploadAndSend` 保持一致, 避免混乱

2021-03-20 07:59 UTC, merged