Rename `RichMessageOrigin` to `MessageOrigin`
mamoe/mirai pull request #1116
Opened 2021-03-26 12:02 UTC by Him188

为了添加 `Dice` 的 origin

> message/MarketFaceImpl.kt:47
> ```kotlin
> delegate.toDiceOrNull()?.let { return it } // TODO: 2021/2/12 add dice origin, maybe rename MessageOrigin
> ```

可能有更好的命名, 姑且先改叫 `MessageOrigin`

2021-03-26 12:05 UTC, Karlatemp commented
是否需要像以前一样先保留一段时间的二进制兼容（已经无法使用）再彻底删除？

2021-03-26 12:06 UTC, Him188 commented
> 是否需要像以前一样先保留一段时间的二进制兼容（已经无法使用）再彻底删除？

似乎不容易提供兼容

2021-03-26 12:06 UTC, Karlatemp requested changes
https://github.com/mamoe/mirai/blob/d56f5fc8945c5b15824ac015bb22d1bb6ddb7c55/mirai-core-api/src/commonMain/kotlin/message/data/MessageOrigin.kt#L42-L46

如果要重命名为 `MessageOrigin`, 此处  `origin` 类型也应该随之修改

2021-03-26 12:09 UTC, Him188 commented
> https://github.com/mamoe/mirai/blob/d56f5fc8945c5b15824ac015bb22d1bb6ddb7c55/mirai-core-api/src/commonMain/kotlin/message/data/MessageOrigin.kt#L42-L46
> 
> 如果要重命名为 `MessageOrigin`, 此处 `origin` 类型也应该随之修改

那就不容易改了, any suggestions?

2021-03-26 12:11 UTC, Karlatemp commented
> > https://github.com/mamoe/mirai/blob/d56f5fc8945c5b15824ac015bb22d1bb6ddb7c55/mirai-core-api/src/commonMain/kotlin/message/data/MessageOrigin.kt#L42-L46
> > 
> > 如果要重命名为 `MessageOrigin`, 此处 `origin` 类型也应该随之修改
> 
> 那就不容易改了, any suggestions?

改成 `Message`/`MessageContent` 吧, 未来也容易扩展

Reason: `UnsupportedMessage` + `RichMessage` + `MarketFace`

2021-03-28 04:17 UTC, Karlatemp approved these changes
不过原来序列化后 `type: "RichMessageOrigin"` 的反序列化会不会出错

2021-03-28 05:12 UTC, Him188 commented
> 不过原来序列化后 `type: "RichMessageOrigin"` 的反序列化会不会出错，直接序列化 `MessageChain` 的可能不知道 `RichMessageOrigin` 的存在

会出错

2021-04-03 14:54 UTC, Him188 commented
发现其实在 2.3 就没有提供序列化支持...

2021-04-03 15:48 UTC, Karlatemp approved these changes

2021-04-03 16:31 UTC, merged