GroupAnnoucement
mamoe/mirai pull request #1141
Opened 2021-04-01 14:34 UTC by sonder-joker

希望给出更多的建议，以进一步修改

2021-04-01 14:47 UTC, Him188 requested changes

2021-04-01 14:47 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
> +        while (true) {
可以像 `RemoteFileImpl.getFilesFlow` 一样使用 Kotlin `Flow` 来使延迟获取到用户需要

2021-04-01 14:47 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/NewGroupAnnouncement.kt
> +public data class Announcement(
建议不定义 `data`, `data` 将来很难提供扩展稳定性

2021-04-01 14:47 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/NewGroupAnnouncement.kt
> +public data class Announcement(
建议不定义 `data`, `data` 将来很难提供扩展稳定性

2021-04-01 14:47 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +    public suspend fun sendGroupAnnouncement(announcement: Announcement): String
`Group` 对象中的方法就可以不包含 `Group` 命名了
```suggestion
    public suspend fun sendAnnouncement(announcement: Announcement): String
```

2021-04-01 14:52 UTC, Him188 requested changes

2021-04-01 14:52 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/NewGroupAnnouncement.kt
> +    // 已经阅读的成员数量, 如果是confirm则为已经确认的成员数量
标准化 KDoc (其他属性相同)
```suggestion
    /** 已经阅读的成员数量, 如果 [needConfirm] 为 `true` 则是已经确认的成员数量 **/
```

2021-04-01 14:52 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/NewGroupAnnouncement.kt
> +    public val publishTime: Long,
添加注释 (KDoc) 解释单位是秒还是毫秒

2021-04-01 14:52 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/NewGroupAnnouncement.kt
> +    public val isTop: Boolean = false,
```suggestion
    public val isPinned: Boolean = false,
```

2021-04-02 02:36 UTC, sonder-joker commented
有一个小问题
关于Announcement类中，有如下三个属性
```kotlin
    public val publishTime: Long,
    public val isAllRead: Boolean = false,
    public val readMemberNumber: Int = 0
```
为只读属性，如何限制用户的构造？

2021-04-02 03:01 UTC, Him188 commented
> 有一个小问题
> 关于Announcement类中，有如下三个属性
> 
> ```kotlin
>     public val publishTime: Long,
>     public val isAllRead: Boolean = false,
>     public val readMemberNumber: Int = 0
> ```
> 
> 为只读属性，如何限制用户的构造？
> 之前想通过internal set 但因为跨模块而行不太通
> 是否要添加继承？

API 提供 interface Announcement，在协议模块实现。可以参考 `FriendInfo.`

2021-04-03 14:24 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +    public suspend fun sendAnnouncement(
是我没有考虑周全, 还是需要在 API 模块提供 `Announcement` 的构造方式. 这个函数参数过多, 导致它在未来的扩展性比较低.

可以考虑使用 Builder 模式处理, 像 Console 那边的 `JvmPluginDescriptinoBuilder` 和 Core 的 `MessageSourceBuilder`. 这样可以提供不仅灵活而且稳定的接口, 毕竟我们不能确定服务器何时会添加或去除一个属性.

2021-04-03 14:24 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +    public suspend fun sendAnnouncement(
当然, 我建议将 `Announcement` 的构造器全部 `internal`, 只允许通过 builder 构建.

2021-04-03 14:26 UTC, sonder-joker commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +    public suspend fun sendAnnouncement(
同意你的看法，之前就打算写成Builder，我将略作修改

2021-04-03 14:37 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +    public suspend fun sendAnnouncement(
来自 @sandtechnology 的建议:
1. builder 传参 bot ID 和群 ID
2. Announcement 存有上述两个属性
3. 将 `Group.sendAnnouncement` 改为 `Announcement.publish()` (或其他有意义的名称), 处理时从 `Bot.getInstance` 找 Bot, 来调用 `IMirai` 的接口

2021-04-09 12:11 UTC, Karlatemp requested changes
感谢你的帮助

---

各注释中的中文与英文之间应该有空格

2021-04-09 12:11 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    public val readMemberNumber: Int
```suggestion
    /**
     * 所有人都已阅读, 如果 [AnnouncementConfiguration.needConfirm] 为true则为所有人都已确认,
     */
    public val isAllRead: Boolean

    /**
     * 已经阅读的成员数量，如果 [AnnouncementConfiguration.needConfirm] 为true则为已经确认的成员数量
     */
    public val readMemberNumber: Int
```

2021-04-09 12:11 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +public fun BuildAnnouncement(
```suggestion
public fun buildAnnouncement(
```

2021-04-09 12:11 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +}
delete

2021-04-09 12:11 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +public interface ReadAnnouncement : Announcement {
`ReceivedAnnoucement` 会更好?

2021-04-09 12:11 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    block: AnnouncementConfigurationLambda
`AnnouncementConfiguration.() -> Unit`

2021-04-09 12:13 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    block: AnnouncementConfigurationLambda
FYI: `BotConfiguration` 有这样的设计, 我忘了是什么目的了

2021-04-09 12:18 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    AnnouncementConfiguration().apply(block)
`inline`

2021-04-09 12:39 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> + * [AnnouncementConfiguration]的DSL构造函数
```suggestion
 * [AnnouncementConfiguration] 的 DSL 构造函数
```
通常文档英文和中文之间要有空格

2021-04-09 12:39 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +public fun BuildAnnouncement(
```suggestion
public fun buildAnnouncement(
```

2021-04-09 12:39 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    public val image: ExternalResource?
image 的用途是? (我猜是用于发送)

在接收时定义类型为 `ExternalResource` 不太好

2021-04-10 02:27 UTC, sonder-joker commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    block: AnnouncementConfigurationLambda
是为了方便java调用，不过好像没啥必要

2021-04-10 02:29 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    block: AnnouncementConfigurationLambda
Java 里也可以使用 lambda

2021-04-10 02:34 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    block: AnnouncementConfigurationLambda
mirai target JVM8 和 Android，在 Android 没有 java.util.Function?

那么 Java 就要 new 一个 xxx$lambda$1 的类型

2021-04-10 02:38 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    block: AnnouncementConfigurationLambda
Java 里也可以使用 kotlin 的 lambda (`kotlin.jvm.functions.FunctionX`)

2021-04-10 02:56 UTC, sonder-joker commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    public val image: ExternalResource?
还是使用```ByteArray```为好，上传的时候再转换为```ExternalResource``` 
或许可以考虑```Image```来实现？不过```Image```是消息，不太符合群公告图片的定义，但群公告图片也具有```Image```的部分实现，可以考虑进一步拆分接口或者添加接口

2021-04-17 08:21 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +    public suspend fun deleteAnnouncement(receiveAnnouncement: ReceiveAnnouncement): Unit =
可以改为扩展函数

2021-04-17 08:21 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    public val announcementParameters: AnnouncementParameters
`ReceiveAnnouncement` 也可以修改这个属性, 应该是不太好的 (因为这些属性不会同步到服务器, 用户修改了没有作用)

2021-04-17 09:08 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +    public val announcementParameters: AnnouncementParameters
https://github.com/sonder-joker/mirai/pull/1

2021-04-26 12:35 UTC, Him188 requested changes
有很多意外修改, 试试 rebase onto mamoe/dev?

2021-04-26 12:35 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +                Mirai.uploadGroupAnnouncementImage(bot, group.id, parameters.image.toExternalResource())
`toExternalResource` 资源未关闭

2021-04-26 12:38 UTC, Him188 commented
@Karlatemp 

`public suspend fun Group.sendAnnouncement` 放到 `Announcement.kt` 还是 `Group.kt`, 或者 `Group.Companion` static 更好?

2021-04-26 12:42 UTC, Him188 commented
@sonder-joker `sendAnnouncement` 会不会发送公告消息到聊天?

2021-04-26 14:37 UTC, Karlatemp commented
> `public suspend fun Group.sendAnnouncement` 放到 `Announcement.kt` 还是 `Group.kt`, 或者 `Group.Companion` static 更好?

取决于趋向 `GroupKt.send...` 还是 `Group.send....`, 我个人趋向于 `Group.Companion` (static)

2021-04-29 08:13 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +                Mirai.uploadGroupAnnouncementImage(bot, group.id, parameters.image.toExternalResource())
修改建议: 使用 `toExternalResource().use { }`

2021-04-29 09:07 UTC, sonder-joker commented
> @sonder-joker `sendAnnouncement` 会不会发送公告消息到聊天?

不太清楚...我实验一下

2021-04-29 13:34 UTC, sonder-joker commented
> > `public suspend fun Group.sendAnnouncement` 放到 `Announcement.kt` 还是 `Group.kt`, 或者 `Group.Companion` static 更好?
> 
> 取决于趋向 `GroupKt.send...` 还是 `Group.send....`, 我个人趋向于 `Group.Companion` (static)

Companion没有办法获取Group的ID,必须还添加一个参数，也许不太好

2021-04-29 13:35 UTC, Him188 commented
> > > `public suspend fun Group.sendAnnouncement` 放到 `Announcement.kt` 还是 `Group.kt`, 或者 `Group.Companion` static 更好?
> > 
> > 
> > 取决于趋向 `GroupKt.send...` 还是 `Group.send....`, 我个人趋向于 `Group.Companion` (static)
> 
> Companion没有办法获取Group的ID,必须还添加一个参数，也许不太好

```kotlin
companion object {
  @JvmStatic
  fun Group.send(args)
}
```

2021-05-08 16:20 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +public suspend fun Group.deleteAnnouncement(receiveAnnouncement: ReceiveAnnouncement): Unit =
可以放到 Group.Companion 并标注 `@JvmStatic` 供 Java 用户使用

2021-05-13 09:17 UTC, Him188 approved these changes

2021-05-13 10:24 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/Announcement.kt
> +        val bot = Bot.getInstance(botId)
使用 `group.bot` 更好

然后因为没标注可序列化，上下文的 `botId` 可以换成 `bot` 实例

2021-05-13 10:24 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +import kotlin.io.use
这条 import 似乎没有用到

2021-05-13 14:08 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +import kotlin.io.use
这你都能看出来😲

2021-05-22 03:25 UTC, sonder-joker commented
好像网络层变更了 不清楚如何merge（

2021-05-31 09:17 UTC, Him188 commented
> 好像网络层变更了 不清楚如何merge（

rebase onto `dev` 并解决冲突即可. 不推荐使用 merge. 不过建议等 2.7-M1 发布再合 (届时网络层会更稳定一些)

2021-06-16 05:59 UTC, Him188 commented
Rebase 到 dev 然后重新生成 apiDump 就可以合并了

2021-06-19 07:30 UTC, Him188 approved these changes
TODO: merge 添加 `@since`

2021-06-19 07:41 UTC, Karlatemp approved these changes

2021-06-19 07:41 UTC, Karlatemp commented
TODO: Reformat `GroupAnnouncement.kt`

2021-06-23 16:59 UTC, Him188 commented
build 失败可能是某种 bug

2021-06-23 16:59 UTC, merged