添加管理员修改功能
mamoe/mirai pull request #1178
Opened 2021-04-08 17:55 UTC by HoshinoTented

尚未完全测试，Response 处理不完全

2021-04-08 18:02 UTC, HoshinoTented commented
?

2021-04-08 23:39 UTC, Him188 requested changes

2021-04-08 23:39 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/NormalMemberImpl.kt
> +            "`$operationName` operation requires the highest permission, while ${group.botPermission} == ${MemberPermission.OWNER}"
```suggestion
            "`$operationName` operation requires the OWNER permission, while bot has ${group.botPermission}"
```

2021-04-08 23:39 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
> +            val result = readBytes().loadAs(OidbSso.OIDBSSOPkg.serializer()).result
```suggestion
            val result = readProtoBuf(OidbSso.OIDBSSOPkg.serializer()).result
```

2021-04-09 05:17 UTC, HoshinoTented commented on mirai-core/src/commonMain/kotlin/contact/NormalMemberImpl.kt
> +            "`$operationName` operation requires the highest permission, while ${group.botPermission} == ${MemberPermission.OWNER}"
是 bot has group.botPermission 还是 bot has MemberPermission.OWNER？

2021-04-09 05:26 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/NormalMemberImpl.kt
> +            "`$operationName` operation requires the highest permission, while ${group.botPermission} == ${MemberPermission.OWNER}"
group.botPermission

2021-04-09 07:50 UTC, HoshinoTented commented
实际上我并不觉得这个 Response 有什么用

2021-04-09 07:51 UTC, HoshinoTented commented
已经测试了：
* 相同权限时给予相同权限（主动抛出 IllegalState）
* 给予权限后修改 Member 权限
* 无权限时给予权限（主动抛出 PermissionDenied）

2021-04-09 10:38 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/NormalMemberImpl.kt
> +        }
```suggestion
```

我觉得可以不需要抛这个异常----用户通常只期望在执行 `modifyAdmin` 之后目标群员变成了管理员, 而不会在意它是否已经是管理员了 (或者相反)

2021-04-09 10:38 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/NormalMemberImpl.kt
> +                "modify admin failed: TODO"
这是不期望的结果, 可以直接抛 `Failed to modify admin` 并附带 resp 中的返回的 msg (OIDB 包的)

2021-04-09 10:38 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
> +            return ModifyAdmin.Response(stupidTencentCrapPkg.result == 0)
(接上面)

在这里可以获取到 `stupidTencentCrapPkg,msg` (不太记得了, 可能是它里面 rsep 的 msg)

2021-04-09 11:43 UTC, Him188 approved these changes

2021-04-09 11:50 UTC, Karlatemp approved these changes

2021-04-09 11:54 UTC, Him188 commented
Thank you

2021-04-09 13:44 UTC, HoshinoTented commented
Are you OK?
Hello, Thank you.
Thank you VERY MUCH!

2021-04-10 04:48 UTC, HoshinoTented commented
修复 origin == new 时仍然会进行操作并广播 PermissionChangedEvent 的 bug

2021-04-16 00:33 UTC, merged