ECDH: Replacing old curve, thanks to MiraiGo
mamoe/mirai pull request #1237
Opened 2021-05-02 11:18 UTC by sandtechnology

潜在的兼容性问题：
因为在AccountSecrets添加了新字段用于存储public key，所以旧的文件载入时会报错

2021-05-02 11:29 UTC, Karlatemp commented on mirai-core/src/androidMain/kotlin/utils/crypto/ECDHJvmDesktop.kt
>  import net.mamoe.mirai.utils.md5
使用 `mirai-utils` 里的方法

2021-05-02 11:29 UTC, Karlatemp commented on mirai-core/src/androidMain/kotlin/utils/crypto/ECDHJvmDesktop.kt
>          }
调用的频率高不高，如果高的话每次重新从二进制读取 `publicKey` 会不会导致运行效率较低, 最好不要每次都重新解析一样的公秘钥

2021-05-02 17:26 UTC, Him188 commented
会等新网络合入 dev 再合这个

2021-05-09 06:21 UTC, sandtechnology commented
与 dev 完成合并，可以合并了

2021-05-09 06:26 UTC, Him188 commented
> 与 dev 完成合并，可以合并了

看起来 commits 是坏的?

2021-05-09 08:03 UTC, sandtechnology commented
> 
> 
> > 与 dev 完成合并，可以合并了
> 
> 看起来 commits 是坏的?

做了一次 rebase， 应该可以了

2021-05-09 13:33 UTC, Him188 requested changes

2021-05-09 13:33 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/crypto/ECDH.kt
> +public data class ECDHInitialPublicKey(val version: Int = 1, val keyStr: String, val expireTime: Long = 0) {
```suggestion
internal data class ECDHInitialPublicKey(val version: Int = 1, val keyStr: String, val expireTime: Long = 0) {
```

2021-05-09 13:33 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/components/EcdhInitialPublicKeyUpdater.kt
> +            logger.info("Start to check if the ecdh key still valid.")
这句 log 可以去除

2021-05-09 13:33 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/components/EcdhInitialPublicKeyUpdater.kt
> +            logger.error("Failed to fetch ecdh public key from server, use default key instead", it)
第一次初始化总是会输出这个 `error`?

2021-05-09 13:33 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/components/EcdhInitialPublicKeyUpdater.kt
> +            logger.error("Failed to fetch ecdh public key from server, use default key instead", it)
```suggestion
            logger.error("Failed to fetch ECDH public key from server, using default key instead", it)
```

2021-05-09 13:33 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/context/AccountSecrets.kt
> +    override var ecdhInitialPublicKey: ECDHInitialPublicKey,
是否有测试过带着旧 secrets 文件更新?

2021-05-09 13:35 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/context/AccountSecrets.kt
> +    override var ecdhInitialPublicKey: ECDHInitialPublicKey,
会报错无法载入 因为缺少字段

2021-05-09 13:36 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/components/EcdhInitialPublicKeyUpdater.kt
> +            logger.error("Failed to fetch ecdh public key from server, use default key instead", it)
不会 这里捕获的主要是网络请求失败导致的错误数据等情况 大多数情况下是成功的

2021-05-09 13:36 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/context/AccountSecrets.kt
> +    override var ecdhInitialPublicKey: ECDHInitialPublicKey,
然后继续正常运行吗

2021-05-09 13:37 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/components/EcdhInitialPublicKeyUpdater.kt
> +            logger.error("Failed to fetch ecdh public key from server, use default key instead", it)
我在担心 ecdhInitialPublicKey 没有被初始化. 尽量避免 lateinit

2021-05-09 13:38 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/components/EcdhInitialPublicKeyUpdater.kt
> +            logger.error("Failed to fetch ecdh public key from server, use default key instead", it)
我也不想.jpg 不知道有没有什么更好的处理 因为这里是suspend的

2021-05-09 13:39 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/context/AccountSecrets.kt
> +    override var ecdhInitialPublicKey: ECDHInitialPublicKey,
是的 会直接以slowlogin登录然后保存新的 secrets

2021-05-09 13:40 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/components/EcdhInitialPublicKeyUpdater.kt
> +            logger.error("Failed to fetch ecdh public key from server, use default key instead", it)
改为由 `EcdhInitialPublicKeyUpdater` 存 `ecdhInitialPublicKey`. client 通过 bot.components 调用

2021-06-13 07:14 UTC, sandtechnology commented
Rebase 完成，可以合并

2021-06-16 05:42 UTC, Him188 approved these changes

2021-06-23 06:59 UTC, merged