Fix #1192, request admin when loading groups
mamoe/mirai pull request #1257
Opened 2021-05-09 06:30 UTC by sandtechnology

2021-05-09 06:38 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +            }
最好在加载群信息的时候执行, 根据 `getRawGroupMemberList` 语义此处似乎也不应该对现有信息进行修改

2021-05-09 06:38 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
> +            }
```suggestion
            class Failed(val code: Int, val msg: String) : Response() {
                override fun toString(): String = "GetAdmin.Response.Failed(code=$code, msg=$msg)"
            }
```

2021-05-09 06:41 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +            }
主要是找不到更加合适的加载点了，`getRawGroupMemberList` 在返回新列表之前理应确保权限的准确性

2021-05-09 06:48 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +            }
看错了，以为是改现有的

2021-05-09 06:52 UTC, Karlatemp approved these changes

2021-05-09 13:16 UTC, Him188 requested changes

2021-05-09 13:16 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
> +            return readProtoBuf(OidbSso.OIDBSSOPkg.serializer()).let { oidbssoPkg ->
`readOidbRespCommon`

2021-05-09 15:32 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/TroopManagement.kt
> +            return readProtoBuf(OidbSso.OIDBSSOPkg.serializer()).let { oidbssoPkg ->
readOidbRespCommon之前试过，不过不符合这里需要取值的需求就没用（

2021-05-27 17:37 UTC, Him188 approved these changes

2021-06-20 02:28 UTC, AdoptOSS commented
如果可以确定 flag bit [0] == 1 就是管理员
那么似乎没必要这么再发一个包请求管理员列表
考虑
```kotlin
if (flag and 0x1 != 0)
```
----

https://github.com/mamoe/mirai/blob/2014c341022eb2b6d2338311ffe6985ee5e5aa32/mirai-core/src/commonMain/kotlin/contact/info/MemberInfoImpl.kt#L42

在某些老群，管理员的该值并不是1，可能是1,3,5,7,9...
只要是单数就可判定为管理员

_Originally posted by @takayama-lily in https://github.com/mamoe/mirai/issues/1192#issuecomment-834074562_

2021-06-20 02:30 UTC, AdoptOSS commented
OICQ确实采用了flag的判断方法
不知道他们的用户反馈如何
https://github.com/takayama-lily/oicq/blob/06cc43e774828b5d92edaed2dbe03e051088fe49/lib/core/friendlist.js#L173

2021-06-23 06:58 UTC, merged

2021-06-23 07:06 UTC, sandtechnology commented
> 
> 
> OICQ确实采用了flag的判断方法
> 不知道他们的用户反馈如何
> https://github.com/takayama-lily/oicq/blob/06cc43e774828b5d92edaed2dbe03e051088fe49/lib/core/friendlist.js#L173

没来得及做模式切换 如果后面影响使用应该会做一个配置来解决这个

2021-06-23 07:07 UTC, Him188 commented
2.7-M2 放出去用几周, 然后 RC 再放几周, 到 2.7.0 发布时就有足够时间测试了