Redesign SwingSolver
mamoe/mirai pull request #1285
Opened 2021-05-26 15:23 UTC by Karlatemp

close #1283

---

Snapshot on Windows10 with default java desktop LookAndFeel

![snapshot](https://user-images.githubusercontent.com/30070303/119686747-38e84b00-be79-11eb-9bd9-a94724b0cdfd.png)

2021-05-27 17:35 UTC, Him188 approved these changes

2021-05-31 09:12 UTC, Him188 requested changes

2021-05-31 09:12 UTC, Him188 commented on mirai-core-api/src/jvmMain/kotlin/utils/LoginSolver.jvm.kt
> +                                }
```suggestion
                                client.get<String>(uri)
```

2021-05-31 09:12 UTC, Him188 commented on mirai-core-api/src/jvmMain/kotlin/utils/SwingSolver.kt
> +        val image = runInterruptible(Dispatchers.IO) { ImageIO.read(data.inputStream()) }
```suggestion
        val image = runBIO { ImageIO.read(data.inputStream()) }
```

2021-05-31 09:12 UTC, Him188 commented on mirai-core-api/src/jvmMain/kotlin/utils/SwingSolver.kt
> +            val timerQueue = launch {
这跟 `runTxCaptchaHelper` 是不是非常像(重复)?

2021-05-31 09:34 UTC, Karlatemp commented on mirai-core-api/src/jvmMain/kotlin/utils/SwingSolver.kt
> +            val timerQueue = launch {
yes

2021-05-31 10:25 UTC, Him188 commented on mirai-core-api/src/jvmMain/kotlin/utils/SwingSolver.kt
> +            val timerQueue = launch {
最好避免重复

2021-06-01 04:25 UTC, Him188 approved these changes

2021-06-01 04:26 UTC, merged