群公告的lowLevelApi
mamoe/mirai pull request #138
Opened 2020-03-14 03:05 UTC by mzdluo123

2020-03-14 03:13 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +        val json = Json(JsonConfiguration(ignoreUnknownKeys = true))
将 json 保存在 companion 以避免频繁构造

2020-03-14 03:13 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +    override suspend fun _lowLevelGetAnnouncements(groupId:Long, page: Int, amount: Int): GroupAnnouncementList? {
返回非空的 `GroupAccouncementList`

2020-03-14 03:16 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +        val json = Json(JsonConfiguration.Stable)
将 json 保存在 companion 以避免频繁构造

2020-03-14 03:16 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +        val json = Json(JsonConfiguration.Stable)
将 json 保存在 companion 以避免频繁构造

2020-03-14 03:17 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +    @OptIn(LowLevelAPI::class)
传递 LowLevelAPI 给外部 (改为 `@LowLevelAPI`)

2020-03-14 03:17 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +    @OptIn(LowLevelAPI::class)
传递 LowLevelAPI 给外部 (改为 `@LowLevelAPI`)

2020-03-14 03:17 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +    @OptIn(LowLevelAPI::class)
传递 LowLevelAPI 给外部 (改为 `@LowLevelAPI`)

2020-03-14 03:18 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/lowLevelApi.kt
> +    suspend fun _lowLevelGetAnnouncements(groupId: Long, page: Int = 1, amount: Int = 10): GroupAnnouncementList?
改为非空的 `GroupAccountmentList`

2020-03-14 03:19 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +    private fun getBkn(): Int {
改为 `val bkn: Int get() = `

2020-03-14 03:20 UTC, Him188 requested changes
See comments on files

2020-03-14 03:23 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +    override suspend fun _lowLevelGetAnnouncements(groupId:Long, page: Int, amount: Int): GroupAnnouncementList? {
并格式化这个文件: `groupId:Long` 中间应有空格.
可使用 IDE `Ctrl+Alt+L`

2020-03-14 03:49 UTC, merged

2021-07-27 13:13 UTC, Peanuuutz commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/QQAndroidBot.kt
> +            return Int.MAX_VALUE.and(magic)
想问一下这个神奇的算法是怎么反推出来的？