ExternalResourceLeakObserver
mamoe/mirai pull request #1383
Opened 2021-07-02 15:57 UTC by Karlatemp

2021-07-02 18:43 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ExternalResourceLeakObserver.kt
> +            Thread.sleep(60 * 1000L)
busy waiting

2021-07-02 18:43 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalImageImpls.kt
> +    public val createStackTrace: Array<StackTraceElement> = Thread.currentThread().stackTrace
获取 stacktrace 应该是非常慢的？

2021-07-02 18:43 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalImageImpls.kt
> +        if (_closed) return
should be thread safe

2021-07-02 18:43 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalImageImpls.kt
> +public abstract class ExternalResourceHolder : Closeable {
internal 包，不需要 public

2021-07-02 18:46 UTC, Him188 requested changes

2021-07-02 18:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ExternalResourceLeakObserver.kt
> +internal object ExternalResourceLeakObserver : Runnable {
应该放在 core-api 作为 internal。似乎没有放在 core 的理由。

2021-07-02 18:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ExternalResourceLeakObserver.kt
> +internal object ExternalResourceLeakObserver : Runnable {
然后可以使那个 `@Internal public` 改为 internal

2021-07-03 01:14 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalImageImpls.kt
> +    public val createStackTrace: Array<StackTraceElement> = Thread.currentThread().stackTrace
除非用户在很短的时间内创建大量 `ExternalResource`, 创建一次 `ExternalResource` 带来几毫秒的性能损失是在可接受范围内的

2021-07-03 07:17 UTC, Him188 reviewed
为什么不直接让 ERInternal 实现 holder 的工作？可以降低复杂度很多

2021-07-03 07:18 UTC, Karlatemp commented
> 为什么不直接让 ERInternal 实现 holder 的工作？可以降低复杂度很多

WeakReference 进去 queue 之后引用已经被 gc 掉了，需要另外分离一个 holder 出来

2021-07-03 07:58 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalImageImpls.kt
> +    public val createStackTrace: Array<StackTraceElement> = Thread.currentThread().stackTrace
我记得创建异常的性能损失是创建一个普通对象 35x slower，在库层面应该尽可能避免。

ER.close 主要由 mirai-core 实现，用户实现的情况会是非常少的。当 close 异常，该异常的 stacktrace 就会包含用户实现的代码，理应已经能提供足够调试信息。

综上考虑，为了很小的调试信息而牺牲 x35 性能不划算，就像 Kotlin 协程也默认是不进行 stacktrace recovery

2021-07-03 10:56 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/ExternalResourceLeakObserver.kt
> +                                } else ". Add jvm option `-D$isExternalResourceCreationStackEnabledName=true` to visit creation stack track"
```suggestion
                                } else ". Add jvm option `-D$isExternalResourceCreationStackEnabledName=true` to show creation stack track"
```

2021-07-03 10:57 UTC, Him188 approved these changes

2021-07-03 14:05 UTC, merged