Redesign Announcement API
mamoe/mirai pull request #1389
Opened 2021-07-04 10:02 UTC by Him188

2021-07-04 10:17 UTC, Karlatemp requested changes

2021-07-04 10:17 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/announcement/AnnouncementImage.kt
> + */
`@since 2.7`

2021-07-04 10:17 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/announcement/Announcements.kt
> +     */
```suggestion
    /**
     * 上传群公告图片
     *
     * 注意: 需要由调用方关闭 [resource].
     */
```

2021-07-04 10:17 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/announcement/Announcements.kt
> +    public suspend fun publish(announcement: Announcement): OnlineAnnouncement
```suggestion
    /**
     * 在该群发布群公告并获得 [OnlineAnnouncement].
     *
     * @throws PermissionDeniedException 没有权限时抛出
     */
    public suspend fun publish(announcement: Announcement): OnlineAnnouncement
```

2021-07-04 10:17 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/announcement/OnlineAnnouncement.kt
> +    public val fid: String
无意义的 `JvmName`

2021-07-04 10:17 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/OnlineAnnouncementImpl.kt
> +package contact
package name

2021-07-04 14:17 UTC, Karlatemp approved these changes

2021-07-06 11:12 UTC, merged

2021-07-07 01:42 UTC, Nambers commented
好像还要再从html编码转次编码?
![image](https://user-images.githubusercontent.com/35139537/124687399-652ac900-df07-11eb-9011-83e0265401c3.png)
原文:
![image](https://user-images.githubusercontent.com/35139537/124687449-8095d400-df07-11eb-8f10-6a70eb25626a.png)

PS: 此外, GroupSetting的entranceAnnouncement还是没impl?我看里面代码好像已经impl到memo了，不过好像取不到

2021-07-07 02:58 UTC, Him188 commented
@Nambers 开两个 issue

2021-07-07 03:37 UTC, Nambers commented
> @Nambers 开两个 issue

ok