Introduce auto close for `ExternalResource`
mamoe/mirai pull request #1392
Opened 2021-07-05 11:09 UTC by Him188

2021-07-05 14:17 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +    public val autoClose: Boolean get() = false
isAutoClose better

2021-07-05 14:17 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +        public fun ExternalResource.autoClose(): ExternalResource {
as/to AutoCloseable better

2021-07-05 14:20 UTC, Karlatemp requested changes

2021-07-05 14:20 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +}
如果 `action` 和 `close` 同时抛出一个错误, 那么 `close` 的错误将会覆盖掉 `action` 抛出的错误

```kotlin
// 字节码较为臃肿
if (autoClose) use{ action() }
else action()
```

```kotlin
// 与  `use`  实现逻辑一样
var error: Throwable? = null
try {
    return action()
} catch (err: Throwable) {
   // ...
} finally {
   // ....
}
```

2021-07-07 04:04 UTC, Karlatemp approved these changes

2021-07-19 01:46 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +     * 在 _使用一次_ 后自动 [close].
```suggestion
     * 是否在 _使用一次_ 后自动 [close].
```

2021-07-19 01:46 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> + * 执行 [action], 如果 [toAutoCloseable], 在执行完成后调用 [ExternalResource.close].
```suggestion
 * 执行 [action], 如果 [isAutoClose], 在执行完成后调用 [ExternalResource.close].
```

2021-07-19 01:46 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> + * 执行 [action], 如果 [toAutoCloseable], 在执行完成后调用 [ExternalResource.close].
```suggestion
 * 执行 [action], 如果 [isAutoClose], 在执行完成后调用 [ExternalResource.close].
```

2021-07-19 01:46 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> + * 执行 [action], 如果 [toAutoCloseable], 在执行完成后调用 [ExternalResource.close].
```suggestion
 * 执行 [action], 如果 [isAutoClose], 在执行完成后调用 [ExternalResource.close].
```

2021-07-30 19:01 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +public inline fun <T : ExternalResource, R> T.letAutoClose(action: (resource: T) -> R): R {
```suggestion
public inline fun <T : ExternalResource, R> T.useAutoClose(action: (resource: T) -> R): R {
```
Maybe better?

2021-09-01 12:04 UTC, Him188 commented
仅 `public fun ExternalResource.toAutoCloseable()` 为 stable

2021-09-01 12:05 UTC, merged