Introduce Record for new API, revert changes on Voice
mamoe/mirai pull request #1452
Opened 2021-07-31 11:29 UTC by Him188

还需要考虑帮助 MAH 构造 `Record`

2021-07-31 11:34 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Record.kt
> +    public suspend fun getUrlForDownload(): String
可能定义为 `val url: String` 就足够了, 协议里是直接提供 URL

2021-07-31 11:49 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
> +    fun ImMsgBody.Ptt.toVoice() = RecordImpl(
toRecord

2021-07-31 11:49 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
> +            kotlinx.io.core.String(fileName),
可以改成 kotlin stdlib api?

2021-07-31 11:49 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/Record.kt
> +            values().find { it.formatName == formatName }
不推荐直接 `values()`, `values()` 会执行的时候拷贝一次数组, 使用 `private val VALUES = values()` 代替

2021-08-01 03:33 UTC, AdoptOSS requested changes

2021-08-01 03:33 UTC, AdoptOSS commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
>              "${resource.md5.toUHexString("")}.amr",
在QQ中总是使用`amr`扩展名（待验证），但在`mirai`中能否使用`silk`标记silk文件，以便通过`voiceId`还原`codec`属性？
这可能可以帮助`mah`等项目处理`voiceId`
（在发送时涉及的协议部分可以仍旧强制使用`amr`扩展名）

2021-08-01 04:45 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
>              "${resource.md5.toUHexString("")}.amr",
Record 有 codec 属性，filename 不可靠

2021-08-01 04:52 UTC, AdoptOSS commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
>              "${resource.md5.toUHexString("")}.amr",
从使用者的角度讲，rpc调用（mah/onebot等等）时，很多人还是希望`uploadVoice`得到一个`id`（就像`imageId`那样），而不是得到一串可能需要解析的数据。如果可能的话，最好能提供某种方法，把必要参数以某种方式塞进`id`里面组合成一个`roundTripId`，给客户端使用（但不是json序列化，json格式在这个场景下太过复杂，明显不适合作为 mirai码/cq码/ob码 的参数）

2021-08-01 04:54 UTC, AdoptOSS commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
>              "${resource.md5.toUHexString("")}.amr",
理想的RPC调用是这样（当然这个 复杂id的解析和生成 也可以放到 mah 中实现，但这就很可能意味着 mah 必须调用 Internal api）
```kotlin
val id = remote.uploadVoice(....)
remote.send("[mirai:voice:$id]")
```

2021-08-01 05:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
>              "${resource.md5.toUHexString("")}.amr",
那是属于 MAH 应用层的设计范畴，core 只提供协议层的封装。Record 构造方式正在考虑，这个 PR 还只是 draft。

2021-08-01 07:14 UTC, Him188 commented
@AdoptOSS 现在怎么样?

2021-08-01 07:32 UTC, Karlatemp commented on mirai-core/src/jvmTest/kotlin/message/data/MessageSerializationTest.kt
> +    fun `test Record serialization`() {
`OfflineRecord` missing testing

2021-08-02 08:05 UTC, Karlatemp approved these changes

2021-08-02 18:04 UTC, Him188 reviewed
在 Telegram 看到语音消息用的是 audio，故将系列更名为 Audio 可能更合适？@karlatemp

在使用 Record 之时我并未考虑，原本仅是替换 Voice

2021-08-03 12:25 UTC, Karlatemp commented
> 在 Telegram 看到语音消息用的是 audio，故将系列更名为 Audio 可能更合适？@Karlatemp
> 
> 在使用 Record 之时我并未考虑，原本仅是替换 Voice

Record 表示是某种记录, Audio 这直接表明是个音频, 似乎 Audio 更加适合

2021-08-04 04:31 UTC, Him188 commented
@ryoii 考虑到 MAH 的实现, 你对这个新设计有没有意见?

2021-08-04 08:13 UTC, AdoptOSS commented
-[ ] Mirai Code Support?

2021-08-04 09:13 UTC, Him188 commented
> Mirai Code Support?

有 extraData，url 等数据，很难用 mirai code 表示

2021-08-04 09:42 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/Audio.kt
> +            Factory by loadService("net.mamoe.mirai.internal.message.OfflineAudioFactoryImpl")
Why not get service from `MiraiImpl`

2021-08-04 09:44 UTC, Karlatemp approved these changes

2021-08-04 09:51 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Audio.kt
> +            Factory by loadService("net.mamoe.mirai.internal.message.OfflineAudioFactoryImpl")
现在啥都往 MiraiImpl 塞, 我感觉它会越来越大

2021-08-05 13:48 UTC, merged