Improve logging: use Log4j internally and support markers
mamoe/mirai pull request #1464
Opened 2021-08-06 14:14 UTC by Him188

close #1426

2021-08-07 07:01 UTC, AdoptOSS requested changes
一个隐藏的bug
JdkLogger 中 debug 和 verbose 的优先级错误

2021-08-07 07:01 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +        logger.log(java.util.logging.Level.FINER, message, e)
```suggestion
        logger.log(java.util.logging.Level.FINEST, message, e)
```

2021-08-07 07:01 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +        logger.log(java.util.logging.Level.FINEST, message, e)
```suggestion
        logger.log(java.util.logging.Level.FINER, message, e)
```

2021-08-07 07:08 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +    fun nameWarning(marker: Marker, message: String?, e: Throwable?) {
```suggestion
    fun nativeWarning(marker: Marker, message: String?, e: Throwable?) {
```
Typo

2021-08-07 07:08 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +    // unsafe
`Log4jLoggerAdapter` is internal
这些 unsafe 方法是否有存在的必要？

2021-08-07 07:18 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/internal/utils/MarkedMiraiLogger.kt
> + * 内部添加 [Marker] 支持, 并兼容旧 [MiraiLogger] API.
这种设计实际上使得 logger 变得更加复杂化
为何不直接并入原有的 `MiraiLogger` 接口？
从 jvm 层面来讲提供 default method 应该可以维持较好的兼容性
至于默认实现：
```
val marker: Marker? get() = null
fun subLogger(name: String) = 原来的那个加前缀的logger
```

2021-08-07 07:20 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/internal/utils/MarkedMiraiLogger.kt
> +        if (origin is Log4jLoggerAdapter) origin.nativeVerbose(marker, message, e)
这不应该成立
`Log4jLoggerAdapter` 实现了 `MarkedMiraiLogger` 并重写了 `subLogger`，不应该创建出 `MarkedMiraiLoggerImpl`

2021-08-07 07:29 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/utils/MiraiLogger.kt
> + * 不建议实现或使用 [MiraiLogger]. 请优先考虑使用上述第三方框架. [MiraiLogger] 仅应用于兼容旧版本代码.
`MiraiLogger` 接口仍然可以视作一种通用的可接入各种第三方框架的接口，没有必要不推荐使用

不推荐，或者说需要改进的是 `PlatformLogger` 这些实现

2021-08-07 07:31 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/utils/MiraiLogger.kt
> +        public fun create(requester: Class<*>): MiraiLogger = create(requester, null)
在 kotlin 中应始终推荐使用 KClass
考虑添加 java friendly 标记

2021-08-07 13:17 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/MiraiLogger.kt
> + * 不建议实现或使用 [MiraiLogger]. 请优先考虑使用上述第三方框架. [MiraiLogger] 仅应用于兼容旧版本代码.
没有必要, 这就导致 mirai 需要提供兼容性保证

2021-08-07 13:18 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/MiraiLogger.kt
> +        public fun create(requester: Class<*>): MiraiLogger = create(requester, null)
没有必要, 它们效果相同, 而且 mirai 总是需要提供这两个方法的兼容性保证

2021-08-07 13:21 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/MarkedMiraiLogger.kt
> + * 内部添加 [Marker] 支持, 并兼容旧 [MiraiLogger] API.
这是因为我不希望将 marker 暴露给用户而导致需要提供兼容性保证

2021-08-07 13:22 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +    // unsafe
有

2021-08-07 13:22 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
>      }
```
import java.util.logging.Logger as JdkLogger
import java.util.logging.Level as JdkLogLevel
```

2021-08-07 16:32 UTC, AdoptOSS commented
然而考虑到 mirai core 只是作为库而非应用框架存在，不应该与某个特定的日志库强绑定，而 subLogger 又是涉及到日志语义的部分，必须暴露出去才能让用户自己的 adapter 功能完整

Sent from Outlook for Android<https://aka.ms/ghei36>

2021-08-07 20:59 UTC, Him188 commented
@AdoptOSS 这就是不建议使用 MiraiLogger 的原因。用户应该使用 log4J。Log4J2 与 SLF4J 一样，有设计 API 模块，可以对接 SLF4J 和更多平台。mirai 仅默认使用 log4j-api 因此不失扩展性。用户没有除兼容旧版本外的理由而继续使用设计不佳的 MiraiLoggger。

2021-08-08 01:52 UTC, AdoptOSS commented
JVM 平台的日志库有很多，用户不一定使用 log4j，举例而言 Logback 就是一款优秀的日志库。如果不把 subLogger 公开，用户将无法写出功能完整的 LogbackAdapter。更麻烦的是，假如用户使用的其他类库依赖了其他日志库，关于logger的管理将陷入更大的麻烦。

Sent from Outlook for Android<https://aka.ms/ghei36>


________________________________
From: Him188 ***@***.***>
Sent: Sunday, August 8, 2021 4:59:52 AM
To: mamoe/mirai ***@***.***>
Cc: AdoptOSS ***@***.***>; Mention ***@***.***>
Subject: Re: [mamoe/mirai] Improve logging: use Log4j internally and support markers (#1464)


@AdoptOSS<https://github.com/AdoptOSS> 这就是不建议使用 MiraiLogger 的原因。用户应该使用 log4J。Log4J2 与 SLF4J 一样，有设计 API 模块，可以对接 SLF4J 和更多平台。mirai 仅默认使用 log4j-api 因此不失扩展性。用户没有除兼容旧版本外的理由而继续使用设计不佳的 MiraiLoggger。

―
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/mamoe/mirai/pull/1464#issuecomment-894706273>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AROIETAB5UVOU6L2S6Q3XTTT3WNEPANCNFSM5BV75LLA>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>.

2021-08-08 03:36 UTC, Him188 commented
@AdoptOSS 

> 如果不把 subLogger 公开，用户将无法写出功能完整的 LogbackAdapter

Log4J2 与 SLF4J 一样，有设计 API 模块，可以对接 SLF4J 和更多平台。

> 更麻烦的是，假如用户使用的其他类库依赖了其他日志库，关于logger的管理将陷入更大的麻烦。

这也属于我的考虑范围之中，而这是无法避免的。ktor 使用 SLF4J 而这并不代表 mirai 就必须使用 SLF4J。由于有 Log4J2 to SLF4J 的模块的存在，用户仍然能够用单一日志框架。我计划在 2.7.0 提供这方面的文档说明。

2021-08-08 06:47 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/MarkedMiraiLogger.kt
> +        if (origin is Log4jLoggerAdapter) origin.nativeVerbose(marker, message, e)
确实, nice catch.

2021-08-09 20:21 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +        else logger.trace(message, e)
根据实际测试并不需要为 `marker` 做空判断

2021-08-09 20:21 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/internal/utils/MarkedMiraiLogger.kt
> +        MiraiLoggerMarkedWrapper(origin, Marker(name, origin.markerOrNull ?: MARKER_MIRAI))
needless

2021-08-09 20:25 UTC, Karlatemp commented
Missing test of previous log implementation

2021-08-09 20:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +        else logger.trace(message, e)
utils/LoggerAdapters.kt:56

```kotlin
    /**
     * 将 [org.apache.logging.log4j.Logger] 转换作为 [MiraiLogger] 使用.
     */
    @JvmStatic
    public fun org.apache.logging.log4j.Logger.asMiraiLogger(): MiraiLogger {
        return Log4jLoggerAdapter(this, null)
    }
```
是有的

2021-08-09 20:29 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +        else logger.trace(message, e)
还是说 log4j 处理了这个? 但由于它实现的不同, 我觉得还是保持这个比较好

2021-08-09 20:32 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +        else logger.trace(message, e)
```java
LogManager.getLogger("0").error((Marker) null, "Test");
```
的测试结果是可以正常输出

2021-08-09 20:38 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/utils/LoggerAdapterImpls.kt
> +        else logger.trace(message, e)
StatusLogger 和 SimpleLogger 都会忽略 Marker 参数, 而有可能某个实现没有忽略, 为了保证总是可用, 还是保留 null check

2021-08-11 04:32 UTC, Karlatemp approved these changes

2021-08-11 07:24 UTC, merged