Improve `SimpleListenerHost` registration
mamoe/mirai pull request #1490
Opened 2021-08-22 05:41 UTC by Karlatemp

For slove https://mirai.mamoe.net/topic/548/java%E4%B8%AD-simplelistenerhost-handleexception%E5%87%BD%E6%95%B0%E5%B9%B6%E6%B2%A1%E6%9C%89%E8%A2%AB%E6%89%A7%E8%A1%8C

2021-08-22 06:51 UTC, Him188 requested changes

2021-08-22 06:51 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/EventChannel.kt
> +                (rsp[Job] ?: this.defaultCoroutineContext[Job]) !== listenerJob -> true
这是什么意思? 添加注释

2021-08-22 06:51 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/EventChannel.kt
> +        val cancelHook: Job?
hook 意义不明确 (它实际上可能是 listenerJob) (我没读懂下面的一系列判断)

2021-08-27 12:22 UTC, Him188 requested changes

2021-08-27 12:22 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/EventChannel.kt
> +                    (listenerCoroutineContext[CoroutineExceptionHandler] ?: EmptyCoroutineContext)
后面加的 `(listenerCoroutineContext[CoroutineExceptionHandler] ?: EmptyCoroutineContext)` 对下面的 `rsp[Job]` 没有影响

2021-08-27 12:27 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/event/EventChannel.kt
> +                    (listenerCoroutineContext[CoroutineExceptionHandler] ?: EmptyCoroutineContext)
这句是用来规定必须令 `CoroutineExceptionHandler` 为 listenerHost 的 `CoroutineExceptionHandler`

`rsp[Job]` 对应的是 `coroutineContext[Job]`

2021-08-27 12:29 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/EventChannel.kt
> +                    (listenerCoroutineContext[CoroutineExceptionHandler] ?: EmptyCoroutineContext)
没看到最后 `rsp` 返回给了 `coroutineContext0`

2021-08-27 12:29 UTC, Him188 approved these changes

2021-09-01 06:00 UTC, merged