Hide event logs that are too verbose
mamoe/mirai pull request #1497
Opened 2021-08-26 15:08 UTC by Karlatemp

2021-08-26 15:12 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt
> +    public var isShowingVerboseEventLog: Boolean = false
考虑 systemProp? 网络层其他属性都是通过 systemProp 指定的

2021-08-26 15:20 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.kt
> +    public var isShowingVerboseEventLog: Boolean = false
在 Event.kt 已经有 systemProp 指定了

2021-08-27 02:53 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/Event.kt
> +        private val SHOW_VERBOSE_EVENT_ALWAYS = systemProp("mirai.event.show.verbose.event", false)
```suggestion
        private val SHOW_VERBOSE_EVENT_ALWAYS = systemProp("mirai.event.show.verbose.events", false)
```

2021-08-27 02:53 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/event/VerboseEvent.kt
> +@MiraiInternalApi
1.5.30 调整了 OptIn 机制, 该注解有可能导致一些问题, 待测试

2021-08-27 07:11 UTC, Him188 requested changes
在 docs/DebuggingNetwork.md 添加 mirai.event.show.verbose.events 的说明

2021-08-27 12:32 UTC, Him188 approved these changes
等待 1.5.30 升级的评估再合并

2021-09-01 11:59 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/internal/event/VerboseEvent.kt
> +@MiraiInternalApi
![image](https://user-images.githubusercontent.com/12100985/131666762-a15e7e88-ad59-4fc7-9b02-b370b655d20b.png)

新 OptIn 似乎没有问题, 但 Ktor 类似的定义又是有问题的

还是加上这个注解吧

2021-09-01 11:59 UTC, Him188 requested changes
![image](https://user-images.githubusercontent.com/12100985/131666762-a15e7e88-ad59-4fc7-9b02-b370b655d20b.png)

新 OptIn 似乎没有问题, 但 Ktor 类似的定义又是有问题的

还是加上这个注解吧

2021-09-04 16:06 UTC, Him188 approved these changes

2021-09-04 16:06 UTC, merged