Mock Testing Framework
mamoe/mirai pull request #1521
Opened 2021-09-05 03:47 UTC by Karlatemp

close #1304

2021-09-05 08:46 UTC, Him188 commented on mirai-core/build.gradle.kts
> +        val jvmMock by getting {
多一个source set有可能会导致publishing有问题

2021-09-05 08:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/BotWithComponents.kt
> +internal interface BotWithComponents {
should extend Bot

2021-09-05 08:54 UTC, Karlatemp commented on mirai-core/build.gradle.kts
> +        val jvmMock by getting {
我本地测试过了， publish没问题

2021-09-06 01:45 UTC, Him188 commented on mirai-core-mock/build.gradle.kts
> +    testApi(code)
会不会导致 IDE 的 navigation 有问题？

2021-09-06 01:45 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/MockBotFactory.kt
> +    public companion object {
```suggestion
    public companion object : MockBotFactory by MockBotFactoryImpl() {
```

2021-09-06 01:45 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/contact/MockBotFactoryImpl.kt
> +            lateinit var nick_: String
建议默认一个 nick，避免 lateinit

2021-09-06 01:45 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/contact/MockBotFactoryImpl.kt
> +            lateinit var configuration_: BotConfiguration
默认一个config

2021-09-06 01:45 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/contact/MockBotFactoryImpl.kt
> +            lateinit var tmpFsServer_: TmpFsServer
默认值

2021-09-06 01:45 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/contact/MockBotFactoryImpl.kt
> +                if (!::configuration_.isInitialized) {
把这个判断改为默认值，即使可能会浪费一次，但换来的维护稳定性是值得的

2021-09-06 01:45 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/contact/MockMember.kt
> +    public fun modifyNameCard(value: String)
不广播事件，那就改名为 set 吧

2021-09-06 04:44 UTC, Karlatemp commented on mirai-core-mock/build.gradle.kts
> +    testApi(code)
目前我在本地编写的时候还没遇到

2021-09-06 05:03 UTC, Him188 commented on mirai-core-mock/build.gradle.kts
> +    testApi(code)
那就等出问题了再修吧

2021-09-08 10:20 UTC, Him188 requested changes

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/utils/type.kt
> +public suspend infix fun Nudge.startAction(actor: UserOrBot) {
我觉得这不适合 infix

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/utils/type.kt
> +public suspend fun MessageChain.mockFireRecalled(operator: Contact? = null) {
我觉得弄一个 object 专门进行 mock 事件(或者与 message 相关的 mock 事件)的广播

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/utils/type.kt
> +public suspend fun ExternalResource.mockUploadAsOnlineAudio(bot: MockBot): OnlineAudio {
是不是应该让 ER.upload 在测试时直接返回(不上传数据), 而不是写这个 mock upload? 似乎不会在测试中调用 mockUploadAsOnlineAudio

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/utils/type.kt
> +public suspend fun ExternalResource.mockUploadAsOnlineAudio(bot: MockBot): OnlineAudio {
如果测试要调用 mockUpload, 而生产要调用 upload, 那么测试就没有意义了?----生产代码并没有被测试

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/utils/io.kt
> +
不属于 mock framework 的一部分, 应该放到 mirai-core-utils (这个模块属于内部模块)

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/utils/type.kt
> +public inline infix fun MockBot.group(value: Long): MockGroup = getGroupOrFail(value)
为什么不用 MockBot.getGroup 呢

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/userprofile/UserProfileService.kt
> +@Suppress("CONFLICTING_OVERLOADS", "ILLEGAL_JVM_NAME", "INAPPLICABLE_JVM_NAME")
suppress CONFLICTING_OVERLOADS 比较危险, 建议放到最细定义即相关 fun 上

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/userprofile/UserProfileService.kt
> +        return withContext(Dispatchers.IO) {
应该用 runBIO 以支持 cancellability

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/userprofile/UserProfileService.kt
> +        withContext(Dispatchers.IO) {
应该用 runBIO 以支持 cancellability

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/userprofile/UserProfileService.kt
> +public interface UserProfileServiceJ : UserProfileService {
加个简单文档描述用途

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/userprofile/UserProfileService.kt
> +public interface UserProfileService {
加个简单文档描述用途

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/userprofile/UserProfileService.kt
> +public interface MockUserProfileBuilder {
加个简单文档描述, 引用 buildUserProfile

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/utils/MemberInfo.kt
> +public fun simpleMemberInfo(
Java 怎么调用? `MemberInfoKt.simpleMemberInfo`?

<!--如果还有 simpleGroupInfo, simpleUserInfo 等相似函数时, 建议在一个 interface 内定义(整合), 方便 Java 调用, 在未来也可以以 context receivers 于 Kotlin 实现-->

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/internal/contact/util.kt
> +internal infix fun MessageSource.plusMsg(msg: Message): MessageChain = buildMessageChain {
我认为不适合 infix

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/internal/contact/AbstractMockContact.kt
> +    coroutineContext: CoroutineContext,
```suggestion
    parentCoroutineContext: CoroutineContext,
```

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/internal/components/MockEventDispatcherImpl.kt
> +internal open class MockEventDispatcherImpl(
Copied from TestEventDispatcher? Leave a note.

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/fsserver/TmpFsServer.kt
> +public interface TmpFsServer : Closeable {
简单文档

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/database/MessageDatabase.kt
> +    // implement note: concurrent method
```suggestion
    // implementation note: thread-safe
```

2021-09-08 10:20 UTC, Him188 commented on mirai-core-mock/test/MsgDbTest.kt
> +    fun testIdConversation() {
```suggestion
    fun testIdConversion() {
```

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/MockBot.kt
> +    public fun destroy()
为什么不继承使用 close? 现在 MockBot 有 close 和 destroy, 含义相同, 该用哪个?

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/MockBot.kt
> +    public suspend fun doRelogin()
```kotlin
    /**
     * 登录, 或重新登录.
     */
    public suspend fun login()
```

login 有重新登录的作用

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/MockBot.kt
> +    /// Mock Contract API
```suggestion
    /// Mock Contact API
```

typo?

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/MockBot.kt
> +    public fun addGroup(id: Long, uin: Long, name: String): MockGroup
我建议 addGroup 后返回 this 即 bot. 可为 Kotlin 写扩展 addGroup(xxx, apply: MockGroup.() -> Unit ) 来对这个 group '应用' 更多的设置, 例如 addMember:

```kotlin
bot.run {
    addGroup(1, "test") {
         addMember(123) {
                nick = OWNER
         }
    }
    addGroup(2, "test") {
         addMember(123) {
                nick = OWNER
         }
    }
}
```

(参考: Gradle Kotlin DSL)

-----

还有一个问题要考虑, 每个 Group 必须有一个 OWNER. 现在 API 没有在构造时要求制定, 如何处理这个问题?
- A. 在 addGroup 时指定, 那么 addGroup 需要更多参数; 遇到 bot 是 OWNER 的情况如何处理?
- B. 在 addGroup 之后添加, 那么 MockGroup.owner 可能异常, 某些其他功能可能也有异常 (`getMember` 会返回 null), 用户容易遗漏.

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/MockBot.kt
> +    public suspend fun uploadOnlineAudio(resource: ExternalResource): OnlineAudio
看起来这个方法没有很大实际作用----不会有生产代码会调用它. 

若要在 message chain 内模拟 OnlineAudio, 那它(OnlineAudio 的构造方法)也不应该属于某个 Bot, 而是专做一个 OnlineAudio 的构造器(工厂?)更好?

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/contact/MockContact.kt
> +    public suspend infix fun says(message: MessageChain): MessageChain
添加文档, 指明该函数会导致的事件广播, 以及返回值的意义

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/contact/MockGroup.kt
> +    public fun changeOwnerNoEventBroadcast(member: NormalMember)
我建议通过 members 内唯一的 OWNER NormalMember 指定

2021-09-08 10:20 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/contact/announcement/MockAnnouncements.kt
> +    public fun publish(announcement: MockOnlineAnnouncement)
有什么作用? 添加文档

2021-09-08 11:42 UTC, Him188 reviewed
完成了一遍完整 review, 总体来说挺好。这套 mock API 重新实现了 core Contact，去掉所有网络请求但保留广播事件的行为;为各 Contact 添加了新的属性和方法来允许模拟来自服务器的变化，并兼顾实现了事件的广播。

### 待解决的问题

#### 在 Kotlin 写测试

测试肯定会涉及到事件处理，例如要期望程序对一个变更回复一条消息，测试程序则会期待 `GroupMessagePostSendEvent` *（不太记得名字了）*的广播。如何在 Kotlin 方便地接收这个事件？
```kotlin
val list = ConcurrentLinkedQueue<GroupMessagePostSendEvent>()
val listener = GlobalEventChannel.subscribeAlways<GroupMessagePostSendEvent> { list.add(it) }

// test code

listener.cancel()
```
这样的工具函数应该是*必要*的。

### 可能的优化

#### 区分模拟事件和响应事件

测试框架里模拟的属性变更与待测程序调用的方法是相同的，如何分辨是来自程序还是来自测试？如何知晓程序是否对事件作出反应？现在可能只能通过接收事件来解决，但考虑以下场景：

见示例：

> 程序实现当一个人群名片有修改时, 就同时修改另一个人的群名片

```kotlin
// 待测程序
eventChannel.subscribeAlways<MemberNameCardChangedEvent> { event ->
     group[123456].nameCard = event.new
}

// 测试代码
val collected = collectBroadcastEvents { // 伪, 收集该 block 内产生的所有事件
   member.nameCard = "A" // 模拟来自服务器的变更
}
```

`collected` 有两个事件----模拟过程会产生一个事件，然后处理时又会产生一个。可以通过 drop 第一个事件来解决问题，但若过程更复杂一些：
```
// 测试代码
val collected = collectBroadcastEvents { // 伪, 收集该 block 内产生的所有事件
   member.nameCard = "A" // 模拟来自服务器的变更
   member2.nameCard = "B" // 模拟来自服务器的变更
   member3.nameCard = "C" // 模拟来自服务器的变更
   // 假设这个功能需要这样的连续事件
}
```

可能需要考虑优化这种情况，即在接收后或广播前过滤模拟事件。

#### '响应式'消息处理

一个'响应式'消息处理场景：用户输入三条消息："查询成绩"，"张三"，"1000100"（学号）
```kotlin
assertEventCollected<MessagePostSendEvent> { member says "查询成绩" }.run {
    assertEquals("请输入您的姓名", message.content)
}
assertEventCollected<MessagePostSendEvent> { member says "张三" }.run {
    assertEquals("请输入您的学号", message.content)
}
assertEventCollected<MessagePostSendEvent> { member says "1000100" }.run {
    assertEquals("您的成绩是 100", message.content)
}
```

这样的处理可能过于冗长了，若有相关 DSL 将能大幅提升体验：
```kotlin
val marks = 100
database.setStudentMarks(1000100, marks) // 在数据库设置成绩

assertInteractiveMessaging {
    member says "查询成绩"
    bot replies "请输入您的姓名"
    member says "张三"
    bot replies "请输入您的学号"
    member says "1000100"
    bot replies { "您的成绩是 $marks" }
}
```

says 和 replies 的实现应该是即时的，这样用户可以在对话中任意穿插其他的 assert。

#### 制造模拟事件

在响应式消息测试 DSL 设想之上考虑，前文提到的关于模拟事件筛选的问题，以广播前过滤的方式实现应该更好，还可以借助 DSL，通过如下语法实现模拟事件
```kotlin
withMockContext(group) { // this: MockGroupDslContext
    member nickChangesTo "test" // 一般现在时, 声明并广播一条来自服务器的事件：用户昵称变为 test。
    bot replied "OK" // 一般过去时, assert, 从刚刚 collect 的事件中 pop 一个并判断

    member.nudges(bot) { // 服务器事件：用户戳了 bot
        action = "拍了拍"
        suffix = "的肩膀"
    } 

    bot nudged member // assert 一个反馈
```

我只以一个用户的角度简单考虑了 DSL 语法，实现起来可能要更全面考虑（例如 Java）。

#### 实现广播前筛选

要避免 collect 到模拟事件，一个方法是为事件 coroutineContext 添加一个 marker element，然后在 collect 时检测。这可能会要修改一部分 core 实现，当然这也需要实现类似上文 `withMockContext` 的事件模拟方式才能做到修改 coroutineContext 。

2021-09-08 14:15 UTC, Karlatemp commented on mirai-core/src/jvmMock/kotlin/utils/type.kt
> +public suspend infix fun Nudge.startAction(actor: UserOrBot) {
这是因为我想设计一种 `bot group 123 member 456 says "7890"` 类似的 DSL

2021-09-08 14:16 UTC, Karlatemp commented on mirai-core/src/jvmMock/kotlin/utils/type.kt
> +public suspend fun ExternalResource.mockUploadAsOnlineAudio(bot: MockBot): OnlineAudio {
这是提供给位于测试源的 tester 主动模拟某人发出了一条语音用的，用于 `A says <audio>`

2021-09-08 14:17 UTC, Karlatemp commented on mirai-core/src/jvmMock/kotlin/utils/type.kt
> +public inline infix fun MockBot.group(value: Long): MockGroup = getGroupOrFail(value)
这是因为我想设计一种 `bot group 123 member 456 says "7890"` 类似的 DSL

2021-09-08 14:24 UTC, Karlatemp commented on mirai-core/src/jvmMock/kotlin/MockBot.kt
> +    public suspend fun uploadOnlineAudio(resource: ExternalResource): OnlineAudio
此方法是为 Java 提供的测试方法，用于 `MockContact.says`，按照 Java 习惯可能更多的会使用 `bot.uploadOnlineAudio` 便选择放在此处

2021-09-08 14:32 UTC, Karlatemp commented on mirai-core/src/jvmMock/kotlin/MockBot.kt
> +    public fun addGroup(id: Long, uin: Long, name: String): MockGroup
现在的策略是如果没有指定 owner 那么默认 owner 就是 bot 自己

2021-09-11 11:45 UTC, Him188 commented on mirai-core/src/jvmMock/kotlin/utils/type.kt
> +public suspend infix fun Nudge.startAction(actor: UserOrBot) {
infix 仅适合 receiver 和 parameter 为并列关系时使用, 如 `to`, `with`. 有主次关系时应用传统 .call() 

> https://youtrack.jetbrains.com/issue/KT-9730
> 在一系列提案中, 仅 `compareTo` 被采纳

2021-09-11 11:49 UTC, Karlatemp commented
> `在 Kotlin 写测试`, `'响应式'消息处理`

该框架是是设计用来测试 `main` 的各种方法的, 也就是在 `main` 中已经有相关的事件监听函数用户才会在 `test` 编写相关测试代码, 如果需要提供则应该在 `mirai-core-api` 提供

2022-06-19 07:51 UTC, Him188 commented
今天必review

2022-06-19 11:07 UTC, Him188 requested changes

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/README.md
> +```
把示例分开放

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/MockBot.kt
> +    override fun getStrangerOrFail(id: Long): MockStranger = super.getStrangerOrFail(id).cast()
我觉得让所有新增的与原来 Bot 行为不同的函数加 `@MockBotDSL`，这样有明显区分

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/MockBotFactory.kt
> +    public fun newMockBotBuilder(): BotBuilder
这些没有必要标记 DSL

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/MockBotFactory.kt
> +): MockBotFactory.BotBuilder = configuration(BotConfiguration(block))
没有必要标记 DSL

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/MockContact.kt
> +    override var avatarUrl: String
如果与原属性行为不符（原来不允许设置），建议增加新属性然后标记 DSL

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +    public var uin: Long
uin 不应该允许变更

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +    public val controlPane: MockGroupControlPane
标记 DSL？

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +    public val honorMembers: MutableMap<GroupHonorType, MockNormalMember>
标记 DSL？

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/MockFriend.kt
> +    public val mockApi: MockApi
标记 DSL？

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +    public fun addMember0(mockMember: MemberInfo): MockNormalMember
`MockBot.addGroup` 在不接受 lambda 参数的时候返回 MockGroup，那么这个 `MockGroup.addMember` 就应该返回 `Member`

在 Kotlin 可以使用：
```kotlin
group.apply {
    addMember().apply {
         ...
    }
    addMember().apply {
         ...
    }
}
```

在 Java 使用普通方式

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroupControlPane.kt
> +    public fun withActor(actor: MockNormalMember): MockGroupControlPane
增加注释表示返回的东西的广播行为

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/MockUserOrBot.kt
> +    }
`@DSL`

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/database/MessageDatabase.kt
> +}
应该叫做 id 和 internalid，'id2' 属于一个新概念

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/announcement/MockAnnouncements.kt
> +public data class MockOnlineAnnouncement @MiraiInternalApi public constructor(
no data class

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/contact/announcement/MockAnnouncements.kt
> +    public fun publish0(announcement: Announcement, actor: NormalMember): OnlineAnnouncement
`@DSL`? 这个函数会干什么？

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/internal/contact/util.kt
> +internal infix fun MessageSource.withMessage(msg: Message): MessageChain = buildMessageChain {
这不适合 infix

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/txfs/TxFileDisk.kt
> +public interface TxFileDisk {
改名叫 `ServerFileDisk`?

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/txfs/TxFileSystem.kt
> +public interface TxFileSystem {
`ServerFileSystem`?

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/txfs/TxRemoteFile.kt
> +public interface TxRemoteFile {
名称

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/txfs/TxRemoteFile.kt
> +public data class TxRemoteFileInfo(
名称

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/userprofile/UserProfileService.kt
> +        public fun newDefaultInstance(): UserProfileService {
```suggestion
        public fun getDefault(): UserProfileService {
```
不必保证每次调用都会创建新实例

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/userprofile/UserProfileService.kt
> +public interface UserProfileServiceJ : UserProfileService {
我感觉把 `J` 前缀放到前面更好，但历史上也有一些放后面的，你决定吧

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/userprofile/UserProfileService.kt
> + * [UserProfile] 的 DSL 构造器
```suggestion
 * [UserProfile] 的构建器
```
这个 builder 本身跟 DSL 没有关系

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/userprofile/contactinfos.kt
> +}
builder 没有必要标记 DSL

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/userprofile/contactinfos.kt
> +}
builder 没有必要标记 DSL

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/userprofile/contactinfos.kt
> +        public operator fun invoke(): MockMemberInfoBuilder = ThreeInOneInfoBuilder()
builder 没有必要标记 DSL

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/userprofile/contactinfos.kt
> +}
builder 没有必要标记 DSL

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/utils/NameGenerator.kt
> +        public val DEFAULT: NameGenerator = SimpleNameGenerator()
建议使用方法

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/utils/NameGenerator.kt
> +}
看起来没有必要 public

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/utils/image.kt
> +public fun randomImageContent(): ByteArray = miraiutils_randomImageContent()
```suggestion
// Make `randomImageContent` public
public fun Image.Companion.randomImageContent(): ByteArray = miraiutils_randomImageContent()
```
减少top-level functions

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/utils/mockdsl.kt
> +public object MockActions {
对 class 没有必要 DSL

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/utils/type.kt
> +package net.mamoe.mirai.mock.utils
考虑这个文件会如何被 java 调用。它的名称将会是 TypeKt. 另外这个名称我感觉也不合适，和 `util` 一样迷糊，试试 `MockConversion`？

考虑 `@file:JvmName` 去掉 Kt

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/src/utils/type.kt
> +    newAnonymous(name, UUID.randomUUID().toString())
没有必要，这导致语义不明确（没有 implies 是 get 或 getorfail）
对函数的别名更容易增加复杂性

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/build.gradle.kts
> +    api(`ktor-server-netty`)
好像没必要 api

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/test/DslTest.kt
> +    }
不记得 `says` 定义在哪了，看到这感觉没有必要 infix。另外基于 `says`，`sayMessage` 应该叫 `saysMessage`。它实际上也可以作为 `says` 的 overload

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/test/MockBotTestBase.kt
> +    internal fun `$$bot_release`() {
no magic name

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/test/TxFsDiskTest.kt
> +internal class TxFsDiskTest {
name

2022-06-19 11:07 UTC, Him188 commented on mirai-core-utils/src/androidMain/kotlin/Image.android.kt
> +public fun randomImage_android(): Bitmap {
internal

2022-06-19 11:07 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/http.kt
> + */
IDE 给你留了惊喜

2022-06-19 11:07 UTC, Him188 commented on mirai-core-utils/src/jvmMain/kotlin/Image.jvm.kt
> +public fun randomImage_awt_jvm(): BufferedImage {
internal

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/build.gradle.kts
> +    api(project(":mirai-core-utils"))
好像没必要 api

mirai-core-utils 会随时发送 API 或 ABI 变更

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/build.gradle.kts
> +    implementation(`kotlinx-atomicfu-jvm`)
使用了 atomicfu 但没有使用 atomicfu 的编译器插件

2022-06-19 11:07 UTC, Him188 commented on mirai-core-mock/build.gradle.kts
> +    implementation(bouncycastle)
看起来没必要

2022-06-20 09:13 UTC, Karlatemp commented on mirai-core-mock/src/userprofile/UserProfileService.kt
> +        public fun newDefaultInstance(): UserProfileService {
ProfileService 是可变的，不适合用 default 吧

2022-06-20 09:28 UTC, Karlatemp commented on mirai-core-mock/test/DslTest.kt
> +    }
已经有 `says(action: MessageChainBuilder.() -> Unit)` 了, 在来个 `says(action: () -> Message)` 会混乱, 就换了个名字

2022-06-21 10:02 UTC, Karlatemp commented on mirai-core-mock/src/contact/MockGroup.kt
> +    public fun addMember0(mockMember: MemberInfo): MockNormalMember
这样的目的主要是支持
```
addGroup()
  .addMember()
  .addMember()
  .addMember()
```
的链式写法

2022-06-21 13:33 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +    public fun addMember0(mockMember: MemberInfo): MockNormalMember
没有必要，apply 就是为了做这个的

2022-06-21 13:34 UTC, Him188 commented on mirai-core-mock/src/userprofile/UserProfileService.kt
> +        public fun newDefaultInstance(): UserProfileService {
这是你自己取的名字叫 default 哦

那可以叫 getInstance

2022-06-24 07:13 UTC, Him188 commented
rebase 之后 
<img width="167" alt="image" src="https://user-images.githubusercontent.com/12100985/175482895-a5db4eac-23a1-4cd7-9e02-82e2b799f74b.png">


我死了

2022-06-24 08:31 UTC, Karlatemp commented
主要是 api 部分

2022-06-24 09:29 UTC, Him188 commented
在我 review 完之前能不能先不要 force，force 一次就白 review 了

2022-07-02 08:42 UTC, Him188 requested changes
不要 rebase, 不要 rebase, 不要 rebase,
等我 APPROVE 了再 rebase, 等我 APPROVE 了再 rebase, 等我 APPROVE 了再 rebase, 
还有之前的问题你没处理, 现在 rebase 了记录也没了我重写一遍

----

一些函数真的有必要放在 mirai-core-utils 么, 它们更应该在 mock framework 的模块中

去除所有包名和类名中的 `tx`

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/MockBot.kt
> +    }
为了一致性这个应该删除

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/MockBot.kt
> +}
这个应该删除, 用户自己.apply去

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +    public fun addMember0(mockMember: MemberInfo): MockNormalMember
这个问题没有解决

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +
应该返回 member

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +    }
应该删除

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +}
应该删除

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/contact/announcement/MockAnnouncements.kt
> +    ): OnlineAnnouncement = publish0(announcement, actor, false)
改名为 `mockPublish` 或其他有意义的名字

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/database/MessageDatabase.kt
> +    public val msgId: Long,
它会造成歧义, 应该分两个属性 id 和 internalId

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/database/MessageDatabase.kt
> +    public val internal2: Int get() = msgId.toInt()
在 "它会造成歧义, 应该分两个属性 id 和 internalId" 的基础上删除

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/internal/MockBotImpl.kt
> +        return "MockBot<$nick, $id>"
```suggestion
        return "MockBot(nick=$nick, id=$id)"
```

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/internal/contact/MockAnonymousMemberImpl.kt
> +        return "$nick[匿名]"
```suggestion
        return "[匿名]$nick"
``` 
应该更清晰

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/internal/contact/MockFriendImpl.kt
> +        return "$nick($id)"
```suggestion
        return "Friend(nick=$nick, id=$id)"
```

需要保持一致

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/internal/contact/MockGroupImpl.kt
> +        return "$name($id)"
```suggestion
        return "Group(name=$name, id=$id)"
```

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/internal/contact/MockNormalMemberImpl.kt
> +        return "$nameCardOrNick[$id]"
```suggestion
        return "NormalMember(name=$nameCardOrNick, id=$id)"
```

你的各种 contact 类型的 toString 一共有三种格式哦

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/internal/txfs/MockServerFileDiskImpl.kt
> +package net.mamoe.mirai.mock.internal.txfs
package 去除 tx

2022-07-02 08:42 UTC, Him188 commented on mirai-core-mock/src/utils/mockdsl.kt
> +public object MockActions {
这里面不适合 infix, infix 更适合在一个限定的 scope 中使用, 例如:

```kotlin
broadcastMockEvents {
  user nickChangesTo "v"
}
```

2022-07-22 18:41 UTC, Him188 commented
曾经有个人让你别 force push，现在那个人又要重新 review 35个文件

2022-09-04 10:13 UTC, Him188 commented
@Karlatemp Your opportunity to merge

2022-09-09 11:40 UTC, Karlatemp commented
@Him188 另外再看一下文档有没有问题，没有问题一会 ci 过了就和了

2022-09-10 03:44 UTC, Him188 approved these changes
看了文档

2022-09-10 04:49 UTC, merged