Add height, width, size and imageType attribute to Image class
mamoe/mirai pull request #1548
Opened 2021-09-11 13:15 UTC by sandtechnology

Close #1543 #1204 #1032

可能存在的问题：
1.JVM自带库的图片支持格式受限，可能导致之前可以上传的图片在此更改后无法上传
2.Android方面目前未测试，可能存在问题

2021-09-11 15:42 UTC, Him188 requested changes

2021-09-11 15:42 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +        public fun match(str: String): ImageType {
添加其 orNull 版本

2021-09-11 15:42 UTC, Him188 commented on mirai-core/src/androidMain/kotlin/message/imagesImpl.kt
> +@file:JvmName("ImagesImplKtAndroid")
修改文件名（.kt）

2021-09-11 15:42 UTC, Him188 commented on mirai-core/src/jvmMain/kotlin/net/mamoe/mirai/internal/message/imagesImpl.kt
> +    throw IllegalStateException("Failed to find image readers for ExternalResource $this")
```suggestion
    throw UnsupportedOperationException("Failed to find image readers for ExternalResource $this")
```

2021-09-11 15:42 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/imagesImpl.kt
> +internal expect fun ExternalResource.getImageInfo(): ImageInfo
```suggestion
@Throws(IOException::class)
internal expect fun ExternalResource.getImageInfo(): ImageInfo
```

并在调用处考虑 runBIO

2021-09-11 15:47 UTC, Him188 commented
问题1：待review（考虑失败时之前的检测方案？）
问题2：2.8.0-M1 放出测试，测试一个月到 2.8.0 没问题那就是没问题了

2021-09-11 16:15 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +
我的建议是添加 `val attributes: ImageAttributes?` 而不是直接塞进 Image 对象

2021-09-11 16:15 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +        public fun match(str: String): ImageType {
`@JvmStatic`

2021-09-12 04:10 UTC, sandtechnology commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +
各个变量可能有不一样的情况，如果使用 nullable 的字段的我觉得对使用者更不友好

2021-09-12 04:31 UTC, Him188 requested changes
public inline fun Image(imageId: String)
和
Image.Companion.fromId 也应该添加这些参数的重载

2021-09-12 05:24 UTC, Him188 requested changes

2021-09-12 05:24 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +public enum class ImageType {
放 `// Internals` 之前

2021-09-12 05:24 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt
> +        val imageInfo = resource.getImageInfo()
runCatching {}.getOrNull, 来兼容平台不支持的情况

2021-09-12 05:24 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
> +        val imageInfo = resource.getImageInfo()
runCatching {}.getOrNull, 来兼容平台不支持的情况

2021-09-12 06:36 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt
> +        val imageInfo = resource.getImageInfo()
应该不需要？返回一个长宽为0正常的图片类型应该就ok了 如果是Null需要改一堆地方

2021-09-12 07:11 UTC, sandtechnology commented
> 
> 
> public inline fun Image(imageId: String)
> 和
> Image.Companion.fromId 也应该添加这些参数的重载

对于这些参数的重载应该是无意义的（这根据服务器上存储的文件而定而非由用户指定） 在没有得到实际文件前只提供 `imageId` 来构造也没有问题？

2021-09-12 08:18 UTC, sandtechnology commented
Ready for reviewing again

2021-09-12 08:53 UTC, Him188 requested changes

2021-09-12 08:53 UTC, Him188 commented on mirai-core/src/androidMain/kotlin/message/ImagesImplKtAndroid.kt
> +    return runBIO {
应该在调用处 runBIO

2021-09-12 08:53 UTC, Him188 commented on mirai-core/src/androidMain/kotlin/message/ImagesImplKtAndroid.kt
> +    return runBIO {
不应该为了 runBIO 而将这个函数变为 suspend

2021-09-12 11:30 UTC, sandtechnology commented
Ready for reviewing again

2021-09-12 23:29 UTC, sandtechnology commented
Ready for reviewing again

2021-09-13 02:57 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +    WEBP,
客户端不支持，是不是删掉更好？

2021-09-13 04:55 UTC, sandtechnology commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +    WEBP,
正有这个打算 我打算删除掉不支持的格式并为不支持上传的格式抛出异常

2021-09-13 14:24 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +        }
在 `companion object` 保存 `values()` 的 private 副本, 避免不必要的 clone 操作

2021-09-13 14:24 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/imagesImpl.kt
> +        stream.run {
withUse

2021-09-13 14:24 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/imagesImpl.kt
> +internal fun ExternalResource.getImageInfo(): ImageInfo {
根据代码逻辑该函数名为 `recalculateImageInfo0 更加合适`

2021-09-13 14:24 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/imagesImpl.kt
> +internal fun ExternalResource.getImageInfo(): ImageInfo {
该函数是否逻辑过于耦合了

2021-09-14 03:27 UTC, sandtechnology commented
Ready for reviewing again

2021-09-14 09:56 UTC, Karlatemp approved these changes
代码逻辑似乎无问题

2021-09-15 07:17 UTC, Him188 requested changes

2021-09-15 07:17 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt
> +                        width = it.fileWidth,
it 只适合在单行等简单 lambda 内使用, 此时请指定一个变量名

2021-09-15 07:20 UTC, Him188 approved these changes

2021-09-15 20:38 UTC, Him188 approved these changes

2021-09-15 20:38 UTC, merged