AbstractExternalResource
mamoe/mirai pull request #1637
Opened 2021-10-31 06:40 UTC by Karlatemp

2021-10-31 22:20 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +    public interface ResourceCleanCallback {
fun interface?

2021-11-01 10:30 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
>      public fun interface ResourceCleanCallback {
clean换为dispose可能更好

2021-11-01 10:30 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
>      public fun interface ResourceCleanCallback {
see DisposableHandle (coroutines)

2021-11-01 10:36 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
>      public fun interface ResourceCleanCallback {
我首先想到的是 jdk 内部的 `Cleaner`, 而且我觉得这些名称都行

2021-11-01 10:48 UTC, Him188 approved these changes

2021-11-02 22:36 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +     * 受限于构造器调用顺序, [AbstractExternalResource] 只能做到在调用相关资源方法的时候注册监视器,
前半句和上面重复了？

2021-11-02 22:36 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +     * Example
说明是正确示例还是错误示例

2021-11-02 22:36 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +     * 修改 `this` 的资源释放回调
加个句号，因为两行之间如果没有空行，就会被合并到一起

2021-11-09 22:53 UTC, Him188 requested changes

2021-11-09 22:53 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> + * @since TODO
```suggestion
 * @since 2.9
```

2021-11-10 14:39 UTC, merged