Message redesign
mamoe/mirai pull request #1667
Opened 2021-11-12 15:49 UTC by Karlatemp

### Changes

*See commit message*

### Issues:

- Fix #1640
- Fix #1507
- Close #1198

### New Feat

- #1198

### Superseded PRs

- #1640
- #1598

------

> For mamoe: Don't use `Squash and merge` for this pr

2021-11-14 00:26 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
> +            // We can't understand wny Image(group.uploadImage().imageId)
What does this mean?

2021-11-14 00:26 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/MultiMsgUploader.kt
> +    val tmpRand: Random = Random(Random.nextLong() xor currentTimeMillis()),
我觉得没有必要, 用 `Random.Default` 就可以了

2021-11-14 00:26 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/MultiMsgUploader.kt
> +    open suspend fun emit(id: String, msgs: Collection<ForwardMessage.INode>) {
方法体比较复杂, 有没有可能抽几个小函数 (如果更好)?

2021-11-14 00:26 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/data/richstatus/RichStatus.kt
> +                    println("WDT: $dataType")
println

2021-11-14 00:26 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/data/richstatus/RichStatus.kt
> +                    println("DT: $dataType, v7: $var7, 19:$var19")
println

2021-11-14 00:26 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ImagePatcher.kt
> +                return exists.postReturn()
逻辑比较复杂, mark一下明天再看

2021-11-14 00:26 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ImagePatcher.kt
> +        bot.network.run {
顺便去除 run, 减少一层缩进

2021-11-14 00:26 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ImagePatcher.kt
> +    fun putCache(image: OfflineGroupImage) {
把重载放到一起方便阅读

2021-11-14 00:26 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Numbers.kt
> +public fun Int.bitPlusAsLong(i2: Int): Long = this.toLongUnsigned().shl(Long.SIZE_BITS) or i2.toLongUnsigned()
我觉得叫 concat 可能更好

2021-11-14 00:26 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Resources.kt
> +    public fun tryToDispose(): Boolean {
`tryDispose` would be neater

2021-11-14 00:26 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Resources.kt
> +    private val count = AtomicInteger(-1)
使用 `const val` 代替 magics -1 和 -2

2021-11-14 00:26 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Resources.kt
> +    public fun currentStatus(): Int = count.get()
I'd prefer
```suggestion
    public fun currentCound(): Int = count.get()
```
for not introducing a new concept 'status'

2021-11-14 00:26 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Resources.kt
> +public class ResourceAccessLock {
这个用在哪里了?

2021-11-14 00:26 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Resources.kt
> +    public fun release() {
release 多次 (导致 count < -2) 会怎么办?

2021-11-14 00:26 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Resources.kt
> +    public fun setToInit() {
```suggestion
    public fun setInitialized() {
```

If you use`uninitialized`, you'd also use `initialized` over `init`.

2021-11-14 00:26 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Resources.kt
> +    public fun setToLocked() {
```suggestion
    public fun setLocked() {
```

'To' is redundant. Removing for clarity. Same for the other 3 'To's.

2021-11-14 00:28 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Resources.kt
> +    public fun release() {
Test 缺少 release 测试

2021-11-14 00:40 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
> +            // We can't understand wny Image(group.uploadImage().imageId)
user's code

2021-11-14 00:42 UTC, Karlatemp commented on mirai-core-utils/src/commonMain/kotlin/Resources.kt
> +public class ResourceAccessLock {
ImagePatcher

2021-11-14 14:52 UTC, sandtechnology reviewed
加了点命名建议（

2021-11-14 14:52 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/data/richstatus/RichStatus.kt
> +                if (dataType > 0 && dataType < 128) {
dataType in 1...128?

2021-11-14 14:52 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/data/richstatus/RichStatus.kt
> +                    val var19 = String(rawData, dataStartPosition, dataLength)
var19->dataStr?

2021-11-14 14:52 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/data/richstatus/RichStatus.kt
> +            var var7: String? = null
var7->pendingDataStr?

2021-11-14 14:52 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/data/richstatus/RichStatus.kt
> +                                        var var4 = byteBuffer.get().toIntUnsigned()
var6->topicsIndex
var4->topicsId?

2021-11-14 14:52 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/utils/ImagePatcher.kt
> +    private fun iid(imageId: String): String {
getImageIdFromStr?

2021-11-14 14:52 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/utils/ImagePatcher.kt
> +        val iid = iid(image.imageId)
imageId?

2021-11-14 14:52 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/utils/ImagePatcher.kt
> +        val cacheOGI: UnsafeMutableNonNullProperty<OfflineGroupImage> = unsafeMutableNonNullPropertyOf(),
Add a comment: OGI->OfflineGroupImage

2021-11-14 14:52 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/utils/ImagePatcher.kt
> +        val access: ResourceAccessLock = ResourceAccessLock(),
access->accessLock?

2021-11-14 15:09 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/data/richstatus/RichStatus.kt
> +                                        var var4 = byteBuffer.get().toIntUnsigned()
目前意义未知先不改

2021-11-14 15:11 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/message/MultiMsgUploader.kt
> +            }
不妨使用先随机 再递增的方式？

2021-11-14 23:41 UTC, Him188 reviewed
Any tests for `ImagePatcher`? It's essential to ensure `Image` works properly.

2021-11-14 23:41 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +                            cache.accessLock.release()
这有可能抛出 ISE. 这将是个 breaking change (createImage 不再线程安全)

2021-11-14 23:41 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/MultiMsgUploader.kt
> +                        elems = msgChain.toMessageChain()
```suggestion
                        elems = msgChain
```
redundant? (check before applying suggestion)

2021-11-14 23:41 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ImagePatcher.kt
> +    fun putCache(id: String): ImageCache {
Is this function thread-safe? --- it should be.

2021-11-14 23:47 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ImagePatcher.kt
> +    fun findCache(id: String): ImageCache? {
如果我没有理解错, `findCache` 之后是不是必须调用 `cache.release`? 如果是, 那应该在 `findCache` (和 `findCacheByImageId`)注明

2021-11-15 10:05 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/MultiMsgUploader.kt
> +            }
无太大意义

2021-11-15 22:06 UTC, Him188 approved these changes

2021-11-15 22:12 UTC, Him188 requested changes
Optimize commit history and prepare for Rebase and Merge

2021-11-16 04:38 UTC, merged