完善Events.md中自定义事件相关的示例
mamoe/mirai pull request #1686
Opened 2021-11-18 15:27 UTC by wssy001

2021-11-18 23:03 UTC, cssxsh commented on docs/Events.md
> +## 自定义事件
实现是编程术语

2021-11-19 01:24 UTC, wssy001 commented on docs/Events.md
> +## 自定义事件
> 实现是编程术语

已还原

2021-11-19 04:45 UTC, Karlatemp requested changes
- 使用了口语
- 中文与英文之间没有空格
- 示例代码中 *非模型类* 需要优先提供 kotlin 代码, 然后才是 java 代码

2021-11-19 04:45 UTC, Karlatemp commented on docs/Events.md
> +下列实现一个GroupFileUploadEvent(群文件上传事件)，完成新事件广播与订阅。
更换为更通用的 `MyCustomEvent`

2021-11-19 04:45 UTC, Karlatemp commented on docs/Events.md
> +}
作为教程字段数量不该过多，并且不应该存在无意义注释，并且使用 `public` 修饰符

2021-11-19 04:45 UTC, Karlatemp commented on docs/Events.md
> +使用EventKt.broadcast()广播新定义的事件
与上文重复

2021-11-19 04:45 UTC, Karlatemp commented on docs/Events.md
> +//balabala……
更换成书面语

2021-11-19 04:45 UTC, Karlatemp commented on docs/Events.md
> +```
与上文重复

```
#接收自定义事件

与上文提到的其他事件一样，只需要把需要监听的事件类型修改为 `MyCustomEvent` 即可监听自定义事件
```

2021-11-19 04:45 UTC, Karlatemp commented on docs/Events.md
> +注意，一定要用GlobalEventChannel.INSTANCE，不然无法正确监听新事件!!!
```
监听自定义事件时避免使用 `bot.eventChannel`, 因为自定义事件不一定会进入 `bot.eventChannel`
```

2021-11-19 06:08 UTC, wssy001 commented on docs/Events.md
> +下列实现一个GroupFileUploadEvent(群文件上传事件)，完成新事件广播与订阅。
拒绝，因为MyCustomEvent无任何实际意义，相反，GroupFileUploadEvent比MyCustomEvent更有意义，让人一看名字就能知道这个Event的用途

2021-11-19 06:09 UTC, wssy001 commented on docs/Events.md
> +}
类成员变量用public？你确定？

2021-11-19 08:29 UTC, Karlatemp commented on docs/Events.md
> +下列实现一个GroupFileUploadEvent(群文件上传事件)，完成新事件广播与订阅。
正是无特殊意义的名字才适合在文档中使用

2021-11-19 08:31 UTC, Karlatemp commented on docs/Events.md
> +}
因为只看该片段这些字段都无法设置，无修饰符都比 `private` 好

2021-11-19 08:50 UTC, wssy001 commented
每位程序猿都有自己对规范的教条，所以我选择close

2021-11-19 08:50 UTC, closed without merging

2021-11-19 16:04 UTC, sandtechnology commented
虽然这个 PR 已经被提交者关闭，但是还是想来说几个 PR 内容中的问题：
### 一、示例问题
Java 代码片段让我觉得编写者并没有写过文档，例如这个代码示例：
```
public class GroupFileUploadEvent extends AbstractEvent {
 
//    发送者的权限
    private MemberPermission permission;
//    发送时间
    private Integer time;
.....
}
```
它有几个问题：
#### 1.内容重复度太高
字段不应太多，不应该具体到名称（文档是起示范作用的例子，并不是实际的应用，应当尽量简洁，比如这里再多字段也是一样的示范）

#### 2.是错误示范
请问，如果全为 `private`，那可以让监听该事件的使用者获取相应需要的信息吗？这种情况下无修饰符的 `packge-private` 确实都比 `private` 好，我觉得的正确做法是 `private` 的同时提供一个对应的 `getter`，另外这里对基本类型使用了其包装类型，这也是一个错误的示范（[原因](https://dev.to/kylec32/effective-java-prefer-primitive-types-to-boxed-types-j4c)）
#### 3.命名等应该尽量抽象
文档是起示范作用的例子，并不是实际的应用，应当使用 MyCustomEvent 、 foo 等无具体意义的名称，让读者把重点放在实现的示范上。

### 二、措辞问题

#### 1.文档中用词应当客观，应为不带感情、个人观点的描述性文字
举个例子：
```
其实我本人不推荐单体APP使用自定义事件，何必多一层事件广播呢？不觉得鸡肋吗？
在这里我推荐如果有相对应的message，可以使用[链式调用](#链式调用)这边的示例筛选出具备message的event
```
应该为
```
如需筛选含有某个 `Message` 的事件，可参阅[链式调用](#链式调用)中的示例来实现
```

#### 2.在避免错误的提示中，应当提及要这么做的原因：
举个例子：
```
注意，一定要用GlobalEventChannel.INSTANCE，不然无法正确监听新事件!!!
```
应该为  Karlatemp 建议修改的
```
监听自定义事件时应避免使用 `bot.eventChannel`, 因为自定义事件不一定会进入 `bot.eventChannel`
```


<br/>
<br/>
<br/>
总之，文档是客观的描述性文档，起良好的示范作用，并不是踩坑记录等笔记类的内容，在编写文档时应该顾及读者的阅读体验。

以上均为个人观点，仅为建议和看法，欢迎理性交流。

2021-11-20 02:11 UTC, wssy001 commented
对不起 我从一开始就不该提交这个PR 请管理员删了吧，至于你所说的我全盘否定

2021-11-20 02:32 UTC, liujiahua123123 commented
👌