Secrets Protection
mamoe/mirai pull request #1718
Opened 2021-12-08 14:58 UTC by Karlatemp

2021-12-08 15:34 UTC, Him188 requested changes

2021-12-08 15:34 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/SecretsProtection.kt
> +    public object EscapedByteBufferSerializer : KSerializer<EscapedByteBuffer> by serializer<ByteArray>().map(
```suggestion
    public object EscapedByteBufferSerializer : KSerializer<EscapedByteBuffer> by ByteArraySerializer().map(
```
`serializer<ByteArray>()` 不是编译期处理的, 且依赖反射

2021-12-21 23:14 UTC, Him188 requested changes

2021-12-21 23:14 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/SecretsProtection.kt
> +            }
- [ ] 告诉这会导致什么, 如 "将无法保护密码不被通过内存转储的方式导出"
- [ ] 添加一个环境变量来控制忽略这个警告

2021-12-21 23:14 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/SecretsProtection.kt
> +public object SecretsProtection {
应该放到 mirai-core-utils — mirai 作为一个 bot 库没必要提供这个功能

2021-12-23 09:22 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/SecretsProtection.kt
> +public object SecretsProtection {
需要在不受支持的时候输出一个警告信息, 直接 `System.err`?

2021-12-23 10:44 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/SecretsProtection.kt
> +public object SecretsProtection {
也可以

2021-12-29 15:53 UTC, Him188 requested changes

2021-12-29 15:53 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/data/builtins/AutoLoginConfig.kt
> +            val value0: SecretsProtection.EscapedString,
`@Name("value")`? 测试下在 /help 中这个会是什么

2021-12-29 15:53 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/data/builtins/AutoLoginConfig.kt
>          public data class Password(
新构造器 `@since`

2022-01-02 07:28 UTC, Karlatemp commented on mirai-console/backend/mirai-console/src/internal/data/builtins/AutoLoginConfig.kt
> +            val value0: SecretsProtection.EscapedString,
一切正常
```
◆ /autoLogin add <account> <password> [passwordKind]    # 添加自动登录, passwordKind 可选 PLAIN 或 MD5
  /autoLogin clear    # 清除所有配置
  /autoLogin list    # 查看自动登录账号列表
  /autoLogin remove <account>    # 删除一个账号
  /autoLogin removeConfig <account> <configKey>    # 删除一个账号的一个配置项
  /autoLogin setConfig <account> <configKey> <value>    # 设置一个账号的一个配置项
```

2022-01-02 07:58 UTC, Him188 approved these changes

2022-01-03 17:38 UTC, merged