Add getAvatarUrl(spec: Int) fix (#1557)
mamoe/mirai pull request #1721
Opened 2021-12-09 15:25 UTC by cssxsh

待测试

2021-12-10 00:10 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
> +        get() = getAvatarUrl(spec = 100)
原本是 640, 为什么要改成 100?

2021-12-10 00:10 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
> +     * 头像下载链接,
```suggestion
     * 头像下载链接.
```

2021-12-10 00:10 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
> +     * 指定规格不存在时, 会返回 40x40px 的默认图片.
这句话在描述参数, 而下面又单独描述了参数, 建议统一放在一起描述

2021-12-10 00:10 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
> +     * http://q.qlogo.cn/headimg_dl?dst_uin=${id}&spec=${spec}
这个内容没必要放在文档中

2021-12-10 00:10 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +     */
修改建议同在 ContactOrBot 的

2021-12-10 00:11 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
> +    public fun getAvatarUrl(spec: Int): String = "http://q.qlogo.cn/g?b=qq&nk=${id}&s=${spec}"
`spec` 如果只能选这些值, 用 enum 会更好

2021-12-10 00:41 UTC, cssxsh commented on mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
> +        get() = getAvatarUrl(spec = 100)
> 原本是 640, 为什么要改成 100?

https://github.com/mamoe/mirai/issues/1557#issuecomment-989724749

gif 在spec比较高的情况下可能会失效，需要尝试较低的等级

不过这或许应该由用户自己处理

2021-12-21 23:08 UTC, Him188 requested changes

2021-12-21 23:08 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
> +     * @param spec 头像的规格. 指定规格不存在时, 会返回 40x40px 的默认图片.
```suggestion
     * @param spec 头像的规格. 
```

2021-12-21 23:08 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +     * @param spec 头像的规格. 指定规格不存在时, 会返回 40x40px 的默认图片.
```suggestion
     * @param spec 头像的规格. 
```

2021-12-21 23:08 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Group.kt
> +     * 群头像下载链接, 规格640px.
```suggestion
     * 群头像下载链接, 规格默认为 [AvatarSpec.LARGEST]
```

2021-12-21 23:08 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
> +     * 头像下载链接, 规格640px.
```suggestion
     * 群头像下载链接, 规格默认为 [AvatarSpec.LARGEST]
```

2021-12-21 23:08 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/AvatarSpec.kt
> + * 头像的规格, [size] 单位 px.
```suggestion
 * 头像的规格, [size] 单位为 px.
```

2021-12-21 23:08 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/AvatarSpec.kt
> +     * 群员列表中的显示大小, 实际上是40px, 但会比 [SMALLEST] 好一些
```suggestion
     * 群员列表中的显示大小, 实际上是 40 px, 但会比 [SMALLEST] 好一些
```

2021-12-21 23:08 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/AvatarSpec.kt
> +public enum class AvatarSpec(public val size: Int) : Comparable<AvatarSpec> {
```suggestion
public enum class AvatarSpec(@MiraiInternalApi public val size: Int) : Comparable<AvatarSpec> {
```

注意还要添加 import

如果没有特别需求, 一般尽快少地提供 public API, 减轻维护负担

2021-12-22 14:10 UTC, Him188 approved these changes

2021-12-22 19:12 UTC, Him188 commented
有测试过么

2021-12-23 17:14 UTC, cssxsh commented
> 有测试过么

做了一些
[group.list.txt](https://github.com/mamoe/mirai/files/7770630/group.list.txt)
[user.list.txt](https://github.com/mamoe/mirai/files/7770631/user.list.txt)

```kotlin
internal class AvatarUrlTest {
    private val folder: File by lazy { File("../test") }

    private val groups: Set<Long> by lazy {
        folder.resolve("group.list.txt").readLines().mapTo(HashSet()) { it.toLong() }
    }

    private val users: Set<Long> by lazy {
        folder.resolve("user.list.txt").readLines().mapTo(HashSet()) { it.toLong() }
    }

    private fun group(id: Long): Group = object : Group {
        override var name: String
            get() = TODO("Not yet implemented")
            set(_) {}
        override val settings: GroupSettings
            get() = TODO("Not yet implemented")
        override val id: Long = id
        override val owner: NormalMember
            get() = TODO("Not yet implemented")
        override val botAsMember: NormalMember
            get() = TODO("Not yet implemented")
        override val members: ContactList<NormalMember>
            get() = TODO("Not yet implemented")
        override val announcements: Announcements
            get() = TODO("Not yet implemented")

        override fun get(id: Long): NormalMember? {
            TODO("Not yet implemented")
        }

        override fun contains(id: Long): Boolean {
            TODO("Not yet implemented")
        }

        override suspend fun quit(): Boolean {
            TODO("Not yet implemented")
        }

        override suspend fun sendMessage(message: Message): MessageReceipt<Group> {
            TODO("Not yet implemented")
        }

        override suspend fun uploadVoice(resource: ExternalResource): Voice {
            TODO("Not yet implemented")
        }

        override suspend fun setEssenceMessage(source: MessageSource): Boolean {
            TODO("Not yet implemented")
        }

        override val bot: Bot
            get() = TODO("Not yet implemented")

        override suspend fun uploadImage(resource: ExternalResource): Image {
            TODO("Not yet implemented")
        }

        override val coroutineContext: CoroutineContext
            get() = TODO("Not yet implemented")
        override val filesRoot: RemoteFile
            get() = TODO("Not yet implemented")
        override val files: RemoteFiles
            get() = TODO("Not yet implemented")

        override suspend fun uploadAudio(resource: ExternalResource): OfflineAudio {
            TODO("Not yet implemented")
        }

    }

    private fun user(id: Long): User = object : User {
        override val id: Long = id
        override val remark: String
            get() = TODO("Not yet implemented")

        override suspend fun sendMessage(message: Message): MessageReceipt<User> {
            TODO("Not yet implemented")
        }

        override fun nudge(): UserNudge {
            TODO("Not yet implemented")
        }

        override val bot: Bot
            get() = TODO("Not yet implemented")

        override suspend fun uploadImage(resource: ExternalResource): Image {
            TODO("Not yet implemented")
        }

        override val coroutineContext: CoroutineContext
            get() = TODO("Not yet implemented")
        override val nick: String
            get() = TODO("Not yet implemented")

    }

    private val http = HttpClient(OkHttp) {
        expectSuccess = false
    }

    private fun ZipOutputStream.write(response: HttpResponse) {
        write(buildString {
            appendLine("${response.version} ${response.status}")
            response.headers.forEach { name, values ->
                appendLine("${name}: ${values.joinToString()}")
            }
        }.toByteArray())
    }

    private fun ZipOutputStream.putNextContact(contact: ContactOrBot) = runBlocking(Dispatchers.IO) {
        for (spec in AvatarSpec.values()) {
            val url = contact.getAvatarUrl(spec)
            val response = http.get<HttpResponse>(url)
            putNextEntry(ZipEntry("${contact.id}.${spec}.response.txt"))
            write(response)

            if (response.status != HttpStatusCode.OK) continue
            putNextEntry(ZipEntry("${contact.id}.${spec}.jpg"))
            write(response.readBytes())
        }
    }

    private fun useZipOutputStream(name: String, block: (stream: ZipOutputStream) -> Unit) {
        val zip = folder.resolve(name)
        zip.createNewFile()
        ZipOutputStream(zip.outputStream().buffered(ByteArrayPool.BUFFER_SIZE)).use(block)
    }

    @Test
    fun group() = runBlocking(Dispatchers.IO) {
        useZipOutputStream("group.zip") { stream ->
            stream.setLevel(Deflater.BEST_COMPRESSION)
            for (group in groups.map { group(id = it) }) {
                stream.putNextContact(group)
            }
            stream.flush()
        }
    }
    
    @Test
    fun user() = runBlocking(Dispatchers.IO) {
        useZipOutputStream("user.zip") { stream ->
            stream.setLevel(Deflater.BEST_COMPRESSION)
            for (user in users.map { user(id = it) }) {
                stream.putNextContact(user)
            }
            stream.flush()
        }
    }
}
```

2021-12-23 20:08 UTC, Him188 commented
@cssxsh 这种比较难测（依赖于服务器），其实只要本地把每个规格但我图片都测试正常就可以了，不用写测试

2022-02-21 12:31 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/ContactOrBot.kt
> +    public fun getAvatarUrl(spec: AvatarSpec): String = "http://q.qlogo.cn/g?b=qq&nk=${id}&s=${spec.size}"
```suggestion
    @Suppress("INAPPLICABLE_JVM_NANE")
    @JvmName("getAvatarUrl")
    public fun avatarUrl(spec: AvatarSpec): String = "http://q.qlogo.cn/g?b=qq&nk=${id}&s=${spec.size}"
```

感觉对 Kotlin 更友好（在 property 基础上加括号 spec）

2022-02-22 19:37 UTC, Him188 approved these changes

2022-02-22 19:37 UTC, Him188 commented
This branch has conflicts that must be resolved

2022-04-18 23:21 UTC, Him188 approved these changes
Before merge: add `@since`

2022-04-24 11:48 UTC, merged