fix: vararg
mamoe/mirai pull request #1760
Opened 2021-12-24 16:57 UTC by cssxsh

fix: https://github.com/mamoe/mirai-console/issues/342

2021-12-26 22:02 UTC, Him188 requested changes
1. 对于 vararg 参数不是最后一个参数的情况如何处理?
2. 对于有多个 vararg 参数如何处理?

2021-12-26 22:02 UTC, Him188 commented on mirai-console/backend/mirai-console/test/command/TestCommand.kt
> +fun assertArrayEquals(expected: LongArray, actual: LongArray, message: String? = null) {
assertContentEquals

2021-12-26 22:03 UTC, Him188 requested changes
增加对原生数组类型的测试

2022-01-06 21:03 UTC, Him188 commented
备注: 

我在写指令签名解析时留了这个注释 (`command/resolve/ResolvedCommandCall.kt:105`): 
```kotlin
public class ResolvedCommandCallImpl(
    override val caller: CommandSender,
    override val callee: Command,
    override val calleeSignature: CommandSignature,
    override val rawValueArguments: List<CommandValueArgument>,
    private val context: CommandArgumentContext,
) : ResolvedCommandCall {
    override val resolvedValueArguments: List<ResolvedCommandValueArgument<*>> by lazy {
        calleeSignature.valueParameters.zip(rawValueArguments).map { (parameter, argument) ->
            val value = argument.mapToTypeOrNull(parameter.type) ?: context[parameter.type.classifierAsKClass()]?.parse(
                argument.value,
                caller
            )
            ?: throw  NoValueArgumentMappingException(argument, parameter.type)
            // TODO: 2020/10/17 consider vararg and optional
            ResolvedCommandValueArgument(parameter.cast(), value)
        }
    }
}
```
![image](https://user-images.githubusercontent.com/12100985/148451697-876f5436-2608-4207-aea9-82df42ad86e2.png)

不确定这个 PR 实现的方式是否最佳

2022-06-07 16:44 UTC, Him188 reviewed
指令写了都快 2 年了, 已经忘了. 我去读了一下代码, 总体来说这个实现是不错的, 但是 mapToTypeOrNull 增加的 context 参数没有必要, 因为 mapToType 是比 context 优先级更高的一层*解决阶段*. 在这之后才会通过 *Contextual* 方式即  `CommandArgumentContext` 解决. 

建议顺便把我留的那个 TODO 也删掉

----

备注: 

vararg 是在 CommandCallResolver 处理的 (command/resolve/BuiltInCommandCallResolver.kt:138), 也就是说 CommandValueArgument 它的内容就已经会是 MessageChain 并且包含它应该接受的哪些 vararg 实际参数了. 那么这个集合应该作为一个整体处理. 目前和此 PR 都是这么做的.

根据 `ArgumentAcceptance` [定义](https://api.codestream.com/p/YJadJPPb4QMcV34Q/iucYmj-fTrmkJaBHKxUD1g) 可以看到优先级是 Direct > WithTypeConversion > WithContextualConversion > ResolutionAmbiguity > Impossible.  而对于 vararg, 目前是由其数组元素类型判断. 因此 List<String> 接受 MessageChain 的 acceptance 应该是 WithTypeConversion (ContentStringTypeVariant).  详见 [AbstractCommandValueParameter.accepting](https://api.codestream.com/p/YJadJPPb4QMcV34Q/zjGCAsHASR-V1bDcl0YXeg).

结合现行解决优先级, 这个 PR 所增加的转换是介于 Direct > WithTypeConversion 之间的, 我认为可行.

2022-06-07 16:44 UTC, Him188 commented on mirai-console/backend/mirai-console/src/command/parse/CommandValueArgument.kt
> +public fun <T> CommandValueArgument.mapToTypeOrNull(expectingType: KType, context: (KType, Message) -> T?): T? {
这个 context 好像不是支持 vararg 必要的?

2022-06-07 16:44 UTC, Him188 commented on mirai-console/backend/mirai-console/src/command/parse/CommandValueArgument.kt
> +    return (mapToTypeOrNullImpl(expectingType, value) ?: context(expectingType, value)) as T?
多余了, 这个实际上在 command/resolve/ResolvedCommandCall.kt:100 处理:

https://api.codestream.com/p/YJadJPPb4QMcV34Q/dqfjLrG8TOCxnhHPheQoUA

2022-06-10 17:14 UTC, cssxsh commented on mirai-console/backend/mirai-console/src/command/parse/CommandValueArgument.kt
> +public fun <T> CommandValueArgument.mapToTypeOrNull(expectingType: KType, context: (KType, Message) -> T?): T? {
必须的，只靠 `mapToTypeOrNullImpl` 没法对复杂的 ArrayItem 进行处理
https://github.com/mamoe/mirai/blob/fe55a24b701731f4d0c86c09588f36f9d8045ff2/mirai-console/backend/mirai-console/src/command/parse/CommandValueArgument.kt#L93-L103

2022-06-10 17:28 UTC, cssxsh commented on mirai-console/backend/mirai-console/src/command/parse/CommandValueArgument.kt
> +    return (mapToTypeOrNullImpl(expectingType, value) ?: context(expectingType, value)) as T?
> 多余了, 这个实际上在 command/resolve/ResolvedCommandCall.kt:100 处理:
> 
> https://api.codestream.com/p/YJadJPPb4QMcV34Q/dqfjLrG8TOCxnhHPheQoUA

结合上一条回复所说的 只靠 mapToTypeOrNullImpl 没法解决复杂的 参数类型 得靠 context

原本的代码里，CommandValueArgument.mapToTypeOrNull 处理失败（null） 会轮到 context 处理，
但是是 直接 将 parameter.type.classifierAsKClass() 传入，vararg 将会按 Array<*> 处理

有3种解决方案，
1. 在 ResolvedCommandCallImpl 区分 数组 和 非数组，
2. 在 CommandValueArgument.mapToTypeOrNull 里 区分 数组 和 非数组
3. 在 CommandArgumentContext 里添加 自动生成 Array<*> 解析器

我选择的是 2

2022-06-13 18:58 UTC, Him188 commented on mirai-console/backend/mirai-console/src/command/parse/CommandValueArgument.kt
> +    return (mapToTypeOrNullImpl(expectingType, value) ?: context(expectingType, value)) as T?
这个应该要在调用 CommandArgumentParser 的时候处理，即修改 command/resolve/ResolvedCommandCall.kt:100 的 `context[parameter.type.classifierAsKClass()]?.parse`

2022-06-15 13:50 UTC, cssxsh commented on mirai-console/backend/mirai-console/src/command/parse/CommandValueArgument.kt
> +    return (mapToTypeOrNullImpl(expectingType, value) ?: context(expectingType, value)) as T?
> 不知道你说的_复杂的参数类型_是什么，我假设它指的是 Array。`mapToTypeOrNull` 设计上就是只使用 `TypeVariants`，现在增加对 context 的依赖将导致该函数行为混乱。应该单独在 context 阶段判断 array 处理。所以修改 command/resolve/ResolvedCommandCall.kt:100 的 `context[parameter.type.classifierAsKClass()]?.parse` 是我最倾向于认为可行的

我打算不这部分逻辑拆出来 放到 ResolvedCommandCallImpl，你觉得怎么样？
https://github.com/mamoe/mirai/blob/34e38d4ce77f8879004b1507702c55b89a4208f8/mirai-console/backend/mirai-console/src/command/parse/CommandValueArgument.kt#L87-L115

2022-06-15 15:29 UTC, Him188 commented on mirai-console/backend/mirai-console/src/command/parse/CommandValueArgument.kt
> +    return (mapToTypeOrNullImpl(expectingType, value) ?: context(expectingType, value)) as T?
可能行

2022-06-26 00:50 UTC, Keyezi commented
希望能支持多个at解析

2022-07-31 07:55 UTC, Him188 approved these changes

2022-07-31 07:55 UTC, Him188 commented
> 希望能支持多个at解析

现在是支持的吧?

2022-07-31 07:56 UTC, merged

2022-07-31 08:01 UTC, Keyezi commented
> @Keyezi 现在是支持的吧?

回深圳试试，现在还在吃席要吃好几天 湖南这鬼地方真没法待