Redesign console plugin loading system
mamoe/mirai pull request #1842
Opened 2022-01-20 14:24 UTC by Karlatemp

重新设计 console 插件加载系统

## 新的插件类搜索机制

```
`- 在 <console 类加载器>(jdk.internal.loader.ClassLoaders$AppClassLoader) 搜索, 如果搜索到就返回
`- 在<全局共享库> (For JvmPlugin only) 中搜索, 如果搜索到就返回
`- 在插件依赖的其他插件的<共享库类加载器>以及其<本体类加载器>中搜索，如果搜索到就返回
`- 在当前插件的<独立私有依赖库>中搜索, 如果搜索到就返回
`- 在当前插件的<本体类加载器>中搜索，如果搜索到就返回
`- 在其他未直接显示依赖的插件的<本体类加载器>中搜索, 如果搜索到就返回
`- throw ClassNotFoundException(className)
```

## 新依赖引入

```
mirai-console
  `- org.apache.maven.resolver:maven-resolver-api
  `- org.apache.maven.resolver:maven-resolver-impl
  `- org.apache.maven.resolver:maven-resolver-connector-basic
  `- org.apache.maven.resolver:maven-resolver-transport-http
  `- org.apache.maven:maven-resolver-provider
```

## console 文件结构变动

```
console
  `- plugin-libraries - 下载下来的各种依赖存放位置, 结构为本地 Maven 仓库
  `- plugin-shared-libraries - 全局共享库
      `- libraries.txt - 动态依赖, 其 jar 会下载至 plugin-libraries
      |                  格式:  group:artifact:version, eg: net.mamoe:mirai-console:2.9.2
      `- ***.jar - 需要直接加载的 jar, 此文件内的全部 jar 都将被加载
```

## 其他细节更新

当运行时为 `Java 9+` 时, 报错堆栈将包含报错堆栈来源于哪个插件, `Java 8` 依然可正常运行

```
2022-01-20 22:20:44 I/Plugin Depend On Other: java.lang.Throwable: Stack trace
java.lang.Throwable: Stack trace
	at plugin-depend-on-other-0.0.0.jar//net.mamoe.console.integrationtest.ep.dependonother.PluginDependOnOther.onEnable(PluginDependOnOther.kt:38)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:117)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:255)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:171)
```

----

close #1809, close #1800, close #1815

2022-01-20 22:40 UTC, cssxsh commented
maven repo 的 来源是否能 指定多个 url 或 mavenlocal 或 gradle-cache ？

2022-01-21 00:12 UTC, Him188 requested changes

2022-01-21 00:12 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/data/builtins/PluginDependenciesConfig.kt
> +    val repoLoc by value<String>("https://maven.aliyun.com/repository/public")
我觉得有必要在初版就支持多个仓库

2022-01-21 00:12 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginClassLoader.kt
> +        }
如果 dependency 引用了 some-library 1.0, 插件引用了 some-library 2.0, 这会不会导致优先使用 1.0 的?

2022-01-21 00:12 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginDependencyDownload.kt
> +        if ("$artGroup:$artId" in MiraiConsoleBuildDependencies.dependencies)
考虑了版本问题么, console 依赖 1.0 而插件需要 2.0 的情况

2022-01-21 00:12 UTC, Him188 commented on mirai-console/backend/mirai-console/src/plugin/PluginManager.kt
> +    public val pluginLibrariesPath: Path
与下面 pluginSharedLibrariesPath 相比, 这个是不是不由全部插件共享? 应该注明

2022-01-21 00:12 UTC, Him188 commented on mirai-console/tools/gradle-plugin/src/main/kotlin/BuildMiraiPluginNew.kt
> +public open class BuildMiraiPluginNew : Jar() {
直接覆盖旧的 BuildMiraiPlugin? Gradle 插件无需提供 ABI 兼容, 没有必要保留旧的

2022-01-21 00:12 UTC, Him188 commented on mirai-console/tools/gradle-plugin/src/main/kotlin/BuildMiraiPluginNew.kt
> +                    runtime.add(artifact.id.componentIdentifier.displayName)
如果用户通过 mavenLocal() 解决该依赖, 之后 mirai console 加载插件时会找不到依赖
而在实现新的类加载系统前这是可以工作的

2022-01-21 00:12 UTC, Him188 commented on mirai-console/tools/gradle-plugin/src/main/kotlin/BuildMiraiPluginNew.kt
> +        metadataTask = project.tasks.create<GenMetadataTask>(name + "GenMetadata", this)
在一个 task 中注册另一个 task 是不好的

2022-01-21 00:44 UTC, Karlatemp commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginClassLoader.kt
> +        }
是，如果依赖了别的插件，且别的插件使用了1.0, 那么连接倒1.0才是正确逻辑，因为已经又依赖关系

2022-01-21 00:48 UTC, Karlatemp commented on mirai-console/tools/gradle-plugin/src/main/kotlin/BuildMiraiPluginNew.kt
> +                    runtime.add(artifact.id.componentIdentifier.displayName)
暂定解决方法：添加新的 configuration，并命名为 consoleShadowed

2022-01-21 00:54 UTC, Karlatemp commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginDependencyDownload.kt
> +        if ("$artGroup:$artId" in MiraiConsoleBuildDependencies.dependencies)
还没有，确定那些是必须加载console的版本（比如 kt-stdlib)，哪些可以进行覆盖，是一件比较麻烦的事

2022-01-21 21:17 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginDependencyDownload.kt
> +        if ("$artGroup:$artId" in MiraiConsoleBuildDependencies.dependencies)
`MiraiConsoleBuildDependencies` 是 console 'api' 方式暴露的吧, 那就强制使用 console 内置的. console 通过 'implementation' 依赖的就不要强制了, 要允许用户使用自己期望的版本, 因为这也不会导致兼容性问题

2022-01-21 21:35 UTC, Him188 commented on mirai-console/tools/gradle-plugin/src/main/kotlin/BuildMiraiPluginNew.kt
> +                    runtime.add(artifact.id.componentIdentifier.displayName)
也可以考虑叫 miraiPlugin 或者 mirai ?

2022-01-30 10:08 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginDependencyDownload.kt
> +        fun findMavenLocal(): File {
可以抽象出 JvmPluginDependencyResolver 以允许扩展, 不过那是后事了

2022-01-30 10:08 UTC, Him188 approved these changes

2022-01-30 11:43 UTC, Karlatemp commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginDependencyDownload.kt
> +        fun findMavenLocal(): File {
此系统在加载 PluginSystem 前就已经使用了, 不太容易扩展

2022-02-06 11:21 UTC, Karlatemp commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginDependencyDownload.kt
> +        if ("$artGroup:$artId" in MiraiConsoleBuildDependencies.dependencies)
看了一下 gradle 会把全部依赖都匹配上 （包括间接依赖）, 可能不太行

2022-02-06 22:09 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginClassLoader.kt
> +`- Resolve classes from other plugin jar
如果插件不指定依赖, 我觉得就不允许使用其他插件

2022-02-06 22:09 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginDependencyDownload.kt
> +        if ("$artGroup:$artId" in MiraiConsoleBuildDependencies.dependencies)
这个是必须要做的, 不然 console 什么版本加一个依赖就有可能导致插件不能用了, 而且插件在编译期和运行期的行为也会有可能不一样(因为依赖版本不同)

2022-02-06 22:09 UTC, Him188 commented on mirai-console/tools/gradle-plugin/README.md
> +Mirai Console Gradle 在打包 JAR（`buildPlugin`） 时不会携带任何外部依赖,
```suggestion
Mirai Console Gradle 在打包 JAR（`buildPlugin`） 时不会携带任何外部依赖（会保存一份来自 Maven Central 的依赖的列表, 在读取插件时下载） , 
```

2022-02-06 22:09 UTC, Him188 commented on mirai-console/tools/gradle-plugin/README.md
> +#### 排除依赖 (Legacy)
```suggestion
#### 排除依赖 (过时)
```

2022-02-07 09:01 UTC, Karlatemp commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginClassLoader.kt
> +`- Resolve classes from other plugin jar
这是原始行为，如果删除则为破坏性更新

2022-02-07 11:55 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginClassLoader.kt
> +`- Resolve classes from other plugin jar
那就添加一个警告吧，对每个 requestor 警告一次

2022-02-20 13:30 UTC, Him188 commented on mirai-console/backend/mirai-console/build.gradle.kts
> +
留个注释说明它有什么实际影响吧, 比如 "这些依赖将不允许插件覆盖"(?)

2022-02-20 13:31 UTC, Him188 approved these changes

2022-02-21 12:16 UTC, Him188 commented
@Karlatemp rebase merge?

2022-02-21 13:23 UTC, merged