Complete the work on Mocking frame
mamoe/mirai pull request #1872
Opened 2022-02-09 12:15 UTC by Nambers

origin pr: #1521
## Stranger
- [x] broadcastStrangerAddEvent
- [x] StrangerRelationChangeEvent
## Friend
- [x] FriendAvatarChangedEvent
- [ ] ~FriendInputStatusChangedEvent~ Already exist (`broadcastFriendInputStateChange()`)
## Group
- [x] GroupEntranceAnnouncementChangeEvent
- [x] MemberHonorChangeEvent
- [x] GroupTalkativeChangeEvent
- [ ] GroupFile sys v2

IDEA提示说要explicitly加public到interface里我就加了

2022-02-09 12:51 UTC, Karlatemp commented on mirai-core-mock/src/contact/MockStranger.kt
> +            }
不适合在接口定义提供实现，而且在接口提供实现的lazy无意义

2022-02-09 12:51 UTC, Karlatemp commented on mirai-core-mock/src/internal/contact/MockGroupImpl.kt
> +            }
应该与 `Group.announcements` 保持一致

2022-02-09 12:51 UTC, Karlatemp commented on mirai-core-mock/src/contact/MockFriend.kt
> +
不适合直接把内部的 `MockImage` 公开, `MockImage` 属于底层内部实现, 切 `core-api` 的 avatar 只有一个 url, 提供 `setAvatar(url: String)` 即可

2022-02-09 12:51 UTC, Karlatemp commented on mirai-core-mock/src/contact/MockGroup.kt
> +    public val honorMembers: Lazy<MutableList<MockNormalMember?>>
无特殊必要不要出现 `Lazy<*>`, 根据实现, 此处使用 `MutableMap<GroupHonorType, MockNormalMember>` 更适合

2022-02-09 12:51 UTC, Karlatemp commented on mirai-core-mock/test/mock/MockFriendTest.kt
> +    }
`.let { events ->}`, `events ->` 是有必要的, 在长 lambda 中默认名 `it` 并不适合, 剩余测试单元一样

2022-02-09 14:41 UTC, Nambers commented on mirai-core-mock/src/internal/contact/MockGroupImpl.kt
> +            }
ok 没看见string 的 entrance以及deprecated了

2022-02-09 14:56 UTC, Nambers commented on mirai-core-mock/src/internal/contact/MockGroupImpl.kt
> +            }
MockAnnouncements 下的 publish0 我加个 actor: MockNormalMember 参数? 目前好像是直接默认bot发的

2022-02-09 16:17 UTC, Him188 requested changes

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/test/mock/MockStrangerTest.kt
> +            assert(bot.getFriend(111)!!.avatarUrl != "")
assertNotEquals

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/test/mock/MockGroupTest.kt
>          assertEquals("Hello World", anc[0].content)
为什么广播两个但是只期待收到一个呢

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/test/mock/MockFriendTest.kt
> +            assert(bot.getFriend(222)!!.avatarUrl != "")
assertNotEquals

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/src/utils/image.kt
> +internal suspend fun randomMockImage(bot: MockBot): MockImage {
不需要 suspend

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/src/internal/contact/MockStrangerImpl.kt
> +        runBlocking { randomMockImage(this@MockStrangerImpl.bot).getUrl(this@MockStrangerImpl.bot) }
randomMockImage 不需要 suspend, 那么这里就不需要 runBlocking

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/src/internal/contact/MockFriendImpl.kt
>      }
是否需要广播事件有待讨论 @Karlatemp

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroupControlPane.kt
> + * 群设置面板, 进行的操作如果使用 withActor 会进行广播
```suggestion
 * 群设置面板, 进行的操作如果使用 [withActor] 会进行广播
```

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +     * 会自动广播[MemberHonorChangeEvent.Achieve]和[MemberHonorChangeEvent.Lose] 或 [net.mamoe.mirai.event.events.GroupTalkativeChangeEvent] 如果honorType是[GroupHonorType.TALKATIVE]
```suggestion
     * 如果 [honorType] 是 [GroupHonorType.TALKATIVE], 会自动广播 [MemberHonorChangeEvent.Achieve] 和[MemberHonorChangeEvent.Lose] 或 [net.mamoe.mirai.event.events.GroupTalkativeChangeEvent] 
```

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +     * 如果不需要广播直接更改 [MockGroup.honorMembers]
```suggestion
     *
     * 如果不需要广播事件, 可直接更改 [MockGroup.honorMembers]
```

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +     * 更改拥有群荣耀的群成员
```suggestion
     * 更改拥有群荣耀的群成员.
```

KDoc 在 render 之后会删除换行, 类似 Markdown 的解析, 写 KDoc 请务必写完后预览 rendered 效果

2022-02-09 16:17 UTC, Him188 commented on mirai-core-mock/src/contact/MockFriend.kt
> +     * 更改好友头像
```suggestion
     * 模拟好友头像变更. 将会广播 xxxx
```

有必要说明广播事件的行为

2022-02-09 16:18 UTC, Him188 commented
PR 不要用 merge, 用 rebase. 仓库只接受 linear history.

2022-02-09 16:33 UTC, Nambers commented
> PR 不要用 merge, 用 rebase. 仓库只接受 linear history. 

应该没有用到merge 我commit都是从旧的cherry pick回来的，到时候再检查看看

2022-02-10 03:12 UTC, Nambers commented on mirai-core-mock/test/mock/MockGroupTest.kt
>          assertEquals("Hello World", anc[0].content)
确实应该是2，去看了下core里的，如果没有就默认是"", 然后发布个新的也会触发

2022-02-10 03:14 UTC, Nambers commented on mirai-core-mock/src/utils/image.kt
> +internal suspend fun randomMockImage(bot: MockBot): MockImage {
但是bindFile要suspend, 用runBlocking?

2022-02-10 03:24 UTC, Nambers commented on mirai-core-mock/src/contact/MockGroup.kt
> +     * 更改拥有群荣耀的群成员
是在哪生成KDoc

2022-02-11 08:38 UTC, Karlatemp commented on mirai-core-mock/src/internal/contact/MockFriendImpl.kt
>      }
当时设计的时候, 对于有内部 `MockApi` 的时候, 通过外部修改会广播事件，通过 `inner MockApi` 修改的时候不会广播事件

2022-02-11 09:01 UTC, Karlatemp commented on mirai-core-mock/src/utils/image.kt
> +}
不知道语法对不对
```suggestion
// create a mockImage with random content
internal fun randomMockImage(bot: MockBot): MockImage {
    val text = randomImageContent()
    val bindId = generateUUID(text.md5())
    bot.tmpFsServer.fsSystem.getPath("${System.currentTimeMillis()}-${UUID.randomUUID()}").outputStream().use { fso ->
        fso.write(text)
    }
    runBlocking {
        bot.tmpFsServer.bindFile(uuid, bindId)
    }
    return MockImage(generateImageId(text.md5()), bindId)
}
```

2022-02-11 09:03 UTC, Nambers commented on mirai-core-mock/src/utils/image.kt
> +}
我看了下, 实际上的avatar是取不到image的，也就是取不到imageId, 那bindFile好像没必要了?((

2022-02-11 09:04 UTC, Nambers commented on mirai-core-mock/src/utils/image.kt
> +}
我打算改成这样
```
internal fun randomMockImage(bot: MockBot): MockImage {
    val uuid = UUID.randomUUID().toString()
    val f = bot.tmpFsServer.fsSystem.getPath(uuid)
    f.also {
        it.createFile()
    }.outputStream().use { fso ->
        fso.write(randomImageContent())
    }
    return MockImage(uuid, bot.tmpFsServer.resolveHttpUrl(f), imageType = ImageType.APNG)
}
```

2022-02-11 09:04 UTC, Karlatemp commented on mirai-core-mock/src/utils/image.kt
> +}
bindFile是桥接 http 链接的

2022-02-11 09:05 UTC, Nambers commented on mirai-core-mock/src/utils/image.kt
> +}
> bindFile是桥接 http 链接的

okok 那按照你这个来吧

2022-02-11 10:01 UTC, Him188 commented on mirai-core-mock/src/contact/MockGroup.kt
> +     * 更改拥有群荣耀的群成员
右键注释块，选 Render

2022-02-11 10:04 UTC, Nambers commented on mirai-core-mock/src/contact/MockGroup.kt
> +     * 更改拥有群荣耀的群成员
ok 原来是这个

2022-02-12 13:33 UTC, Him188 requested changes

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/contact/MockContact.kt
> +    public var _avatarUrl: String?
```suggestion
    public var _avatarUrl: String by lateinitMutableProperty { randomMockImage(bot).getUrl(bot) }
```

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/contact/MockContact.kt
> +        }
并没有广播事件 (并添加相关 test)

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/internal/contact/MockGroupImpl.kt
> +        }
重复太多, 为什么不在抽象类就实现好这个, 而要把实现复制放到子类?

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/internal/contact/MockFriendImpl.kt
> +        }
重复太多, 为什么不在抽象类就实现好这个, 而要把实现复制放到子类?

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/internal/remotefile/v2/MockAbsoluteFile.kt
> +    private var _exists = true
```suggestion
    @Volatile
    private var _exists = true
```

mirai 支持多线程工作, 尽量避免出现 data race 问题

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/internal/remotefile/v2/MockAbsoluteFolder.kt
> +package net.mamoe.mirai.mock.internal.remotefile.v2
更换为
package net.mamoe.mirai.mock.internal.absolutefile

AbsoluteFile 系统和 RemoteFile 系统是不同的. Karlatemp 给 RemoteFile 的 package 命名 v1 应该是因为他只是姑且实现了 RemoteFile 而没有过多考虑实用性, 为了将来能方便变更才给命名 v1.

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/internal/remotefile/v2/MockRemoteFiles.kt
> +    override suspend fun refreshed(): AbsoluteFolder = this
根据注释, 该函数必须返回一个新对象
```suggestion
    override suspend fun refreshed(): AbsoluteFolder = MRF_AbsoluteFolderRoot(files)
```

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/internal/remotefile/v2/utils.kt
> +}
这些已经实现在 net.mamoe.mirai.internal.utils.FileSystem, 不要制造重复

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/internal/remotefile/v2/utils.kt
> +}
把这两个函数放到 MockAbsoluteFolder 文件内更好

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/utils/image.kt
> +}
把它放到 MockImage 文件内的扩展函数 MockImage.Companion.random(bot) 更好, 尽量减少 utils

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/RemoteFileV2Test.kt
> +internal class RemoteFileV2Test : MockBotTestBase() {
test 没有覆盖完全

对 test 框架的测试是要尽可能覆盖全的, 如果 test 框架都有问题, 那将会很难发现

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/RemoteFileV2Test.kt
> +        val fff = files.root.resolveFileById(ff.id, true)!!
避免只有你能看懂的命名.

```suggestion
        val folder = files.root.createFolder("test")
        val uploaded = f.uploadNewFile("test.txt", "ccc".toByteArray().toExternalResource())
        val resolved = files.root.resolveFileById(ff.id, true)!!
```

记得替换 reference, 不要直接 apply suggestion

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/RemoteFileV2Test.kt
> +        val ff = f.uploadNewFile("test.txt", "cc".toByteArray().toExternalResource().toAutoCloseable())
避免需要花时间读赋值代码才能看懂的命名 (ff).
```suggestion
        val folder = files.root.createFolder("test1")
        files.root.createFolder("test2")
        val file = f.uploadNewFile("test.txt", "cc".toByteArray().toExternalResource().toAutoCloseable())
```
记得替换 reference, 不要直接 apply suggestion

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/RemoteFileV2Test.kt
> +        val f = files.root.uploadNewFile("test.txt", "c".toByteArray().toExternalResource())
备注: 相较于上面两段, 这里只定义一个 `f` 是 OK 的, 不会造成混乱

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/mock/MockFriendTest.kt
> +            assertNotEquals(bot.getFriend(111)!!.avatarUrl, "")
expect 在前, actual 在后

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/mock/MockGroupTest.kt
>          assertEquals(1, anc.size)
为什么 publish 两个, 但只能拿到一个呢
这个好像是 @Karlatemp  写的

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/mock/MockGroupTest.kt
> +        assertNotEquals(bot.addGroup(111, "aaa").avatarUrl.toUrl().readText(), "")
expect 在前, actual 在后

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/mock/MockGroupTest.kt
> +    internal fun testGroupRemoteFile() = runTest {
```suggestion
    internal fun testGroupFileUpload() = runTest {
```

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/mock/MockGroupTest.kt
> +            assertIsInstance<MemberHonorChangeEvent>(events[1])
还需要检查其内容, 写 test 不能偷懒

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/mock/MockFriendTest.kt
> +            assertIsInstance<FriendAvatarChangedEvent>(events[0])
还需要检查其内容

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/src/utils/image.kt
> +}
抱歉, 上一次 review 是我看漏了, 如果 bindFile 是 suspend 那就还是得 suspend.

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/mock/MockStrangerTest.kt
> +            assertIsInstance<StrangerRelationChangeEvent.Deleted>(events[1])
还要检查其内容

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/mock/MockStrangerTest.kt
> +            assertNotEquals(bot.getFriend(111)!!.avatarUrl, "")
expect 在前, actual 在后

2022-02-12 13:33 UTC, Him188 commented on mirai-core-mock/test/mock/MockMemberTest.kt
> +        assertNotEquals(m.avatarUrl, "")
expect 在前, actual 在后

2022-02-12 13:35 UTC, Nambers commented on mirai-core-mock/src/contact/MockContact.kt
> +        }
当时想的是因为每个事件不一样，所以在子类，如果有头像更改事件的，重写覆盖，如果没用就用这个

2022-02-12 13:36 UTC, Him188 commented on mirai-core-mock/src/contact/MockContact.kt
> +        }
这会导致行为与描述不符, 比不广播更不好

2022-02-12 13:40 UTC, Nambers commented on mirai-core-mock/src/contact/MockContact.kt
> +        }
> 这会导致行为与描述不符, 比不广播更不好

qs 我想想怎么改，如果没想好有什么方案我就reverse掉这个MockContact的方法, 还是按照每个类自己实现吧
就mockApi那里

2022-02-13 07:19 UTC, Nambers commented on mirai-core-mock/test/mock/MockGroupTest.kt
>          assertEquals(1, anc.size)
是指下面那个 1 == anc.size 吗， 这个是因为GroupEntranceAnnouncement 只会保留一个? 后面上传的会覆盖

2022-02-13 07:23 UTC, Nambers commented on mirai-core-mock/src/utils/image.kt
> +}
那 ` public var _avatarUrl: String by lateinitMutableProperty { randomMockImage(bot).getUrl(bot) }`
这里就需要suspend了，那就用
` public var _avatarUrl: String by lateinitMutableProperty { runBlocking{randomMockImage(bot).getUrl(bot) }}` ? 还是说有什么更好的解决方法

2022-02-13 07:24 UTC, Nambers commented on mirai-core-mock/test/RemoteFileV2Test.kt
> +internal class RemoteFileV2Test : MockBotTestBase() {
补了个rename的test, 还有其他的吗(( 没怎么想到
reslove的test 都含在其他test了因为都能用上

2022-02-13 12:11 UTC, Him188 commented on mirai-core-mock/src/utils/image.kt
> +}
`suspend fun setAvatarUrl`

这也是本来就比 `_avatarUrl` 更好的解决方案

2022-02-13 12:13 UTC, Him188 commented on mirai-core-mock/test/mock/MockGroupTest.kt
>          assertEquals(1, anc.size)
在真实群里发公告也是只会保留一个么

2022-02-13 12:14 UTC, Nambers commented on mirai-core-mock/src/utils/image.kt
> +}
但是我现在是这样写的?
![1644754411(1)](https://user-images.githubusercontent.com/35139537/153752511-c68287eb-b4da-4e25-8c0d-d3fd3bcf3e19.png)
之前的comment多打了个`_`
那就单独写出setter?

2022-02-13 12:18 UTC, Him188 commented on mirai-core-mock/src/utils/image.kt
> +}
单独写 setter, lateinitMutableProperty 里面可以 runBlocking 将就一下

2022-02-13 12:19 UTC, Nambers commented on mirai-core-mock/src/utils/image.kt
> +}
> 单独写 setter, lateinitMutableProperty 里面可以 runBlocking 将就一下

不对，单独写的setter也不用suspend 因为就是String, 那我就在里面加runBlocking就好了

2022-02-13 12:36 UTC, Nambers commented on mirai-core-mock/test/mock/MockGroupTest.kt
>          assertEquals(1, anc.size)
是 
![dad7d56221e71795b1fea9c525c0b14](https://user-images.githubusercontent.com/35139537/153753331-1844eb2b-fedb-4bce-9510-da1e11dcbb72.jpg)

2022-02-17 18:30 UTC, Him188 approved these changes

2022-02-19 08:01 UTC, Karlatemp approved these changes

2022-02-21 12:17 UTC, merged