Save journals to file
mamoe/mirai pull request #1874
Opened 2022-02-09 15:45 UTC by Karlatemp

close #1844

2022-02-09 16:03 UTC, Him188 requested changes

2022-02-09 16:03 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/MiraiConsoleTerminalLoader.kt
> -                logger = MiraiLogger.Factory.create(MiraiConsoleTerminalLoader::class, "stdout")
用带class的更好吧

2022-02-09 16:03 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/MiraiConsoleTerminalLoader.kt
> +                logger = LoggerCreator("stdout")::info
```suggestion
                logger = MiraiLogger.Factory.create(MiraiConsoleTerminalLoader::class, "stdout")::info
```
不知道这个语法是否正确

2022-02-09 16:03 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/MiraiConsoleTerminalLoader.kt
> +                logger = LoggerCreator("stderr")::warning
同上

2022-02-09 16:03 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +internal object LoggingService {
mirai-console 非静态, 不能写 object

即使 terminal 的 main 是启动单个实例, 但 terminal 可能会用在 test 里启动 console, 就会启动多次

2022-02-09 16:03 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +        }
锁来锁去的, 不如专门一个 thread 做 dispatcher 用 Kotlin 协程写, Channel

2022-02-09 17:38 UTC, Him188 commented
add tests please

2022-02-17 14:17 UTC, Him188 requested changes

2022-02-17 14:17 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    private val pipeline = Channel<String>(capacity = 2048)
这将会创建大小为 2048 的 array ---- 很明显多余了

使用 Channel 默认的 BUFFERED 就足够
```suggestion
    private val pipeline = Channel<String>(capacity = Channel.BUFFERED)
```

2022-02-17 14:21 UTC, Karlatemp commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    private val pipeline = Channel<String>(capacity = 2048)
使用大容量是经过考虑的，容量过小会在记录大量日志的时候导致日志文件顺序错乱

2022-02-17 14:28 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    private val pipeline = Channel<String>(capacity = 2048)
没看到大量日志的 test

可以试试在 trySend fail 的时候开一个协程, 用 start=UNDISPATCHED, 这样可能可以保证顺序, 不过启动协程/提交任务给线程还是不如缓冲效率高, 缓冲也要有

2022-02-17 14:40 UTC, Karlatemp commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    private val pipeline = Channel<String>(capacity = 2048)
test是在我本地测试的，因为大量日志写CI并不好写（无法对随机性做出预测）

如果是 undispatched 那么尝试提交依然还在原线程，此时无开新携程必要，并且我选择了failed后使用线程池提交是因为并不想堵住原线程（日志提交者），综合考虑下来我选择了最好的大缓冲区，并且占用也不高

2022-02-17 14:43 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    private val pipeline = Channel<String>(capacity = 2048)
大缓冲区仍然会有顺序问题, 只有从根本解决

UNDISPATCHED 会在原线程跑到第一个挂起点 (suspension point), 这个挂起点就会是 channel.send, 只是我在猜它能不能像 start=ATOMIC 那样保证协程启动顺序因此保证 send 顺序, 因为 ATOMIC 现在是 experimental.

2022-02-17 14:59 UTC, Karlatemp commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    private val pipeline = Channel<String>(capacity = 2048)
如果使用此策略，那么原执行速度会很大程度被磁盘IO影响, 尤其是这种零碎数据写入, 我没使用能保证顺序的直接写入文件也是基于此原因

2022-02-17 15:06 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    private val pipeline = Channel<String>(capacity = 2048)
不会影响, 写操作仍然是单独在那个 loop 里跑. 这只修改 pushInPool

`AbstractChannel.send`:
```kotlin
    public final override suspend fun send(element: E) {
        // fast path -- try offer non-blocking
        if (offerInternal(element) === OFFER_SUCCESS) return  // 直接 return
        // slow-path does suspend or throws exception
        return sendSuspend(element) //
    }

    // 这里必定挂起协程, 必定导致 pushInPool launch 的协程挂起, 然后 pushInPool 会 return.
    private suspend fun sendSuspend(element: E): Unit = suspendCancellableCoroutineReusable sc@ { cont ->
    }
```

2022-02-17 15:07 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    private val pipeline = Channel<String>(capacity = 2048)
写个 test 试下就知道了, 总是得有大量日志的 test 的

2022-02-17 18:25 UTC, Him188 approved these changes

2022-02-17 18:25 UTC, Him188 commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    }
所以 UNDISPATCHED 会保证顺序吗

2022-02-19 12:57 UTC, Karlatemp commented on mirai-console/frontend/mirai-console-terminal/src/LoggingService.kt
> +    }
是的, 效果好很多

2022-02-21 12:18 UTC, merged

2022-08-06 16:13 UTC, zxin8580 commented
could you please provides an option to disable the logging service T.T