Add: OtherClientCommandSenderOnMessageSync
mamoe/mirai pull request #1879
Opened 2022-02-11 16:47 UTC by cssxsh

想法是把 `MessageSyncEvent` 对接到 `OtherClientCommandSender` ,
但是 `MessageSyncEvent` 好像没有 `client` 方法（属性），所以改了 `MessageSyncEvent` 的 继承及实现

参考 OtherClientNoticeProcessor 改的代码，不过 return 而不是 throw 或者 给个 `UnknownClient` 真的好吗，信息直接被丢弃了

https://github.com/mamoe/mirai/blob/3a2663104b3b18eff88c83f4ab8a9b7335830209/mirai-core/src/commonMain/kotlin/network/notice/priv/OtherClientNoticeProcessor.kt#L124-L125

2022-02-11 18:27 UTC, Him188 commented
目前没人报告未识别 OtherClient 的情况，那就不要创造问题

2022-02-12 02:18 UTC, cssxsh commented
> 目前没人报告未识别 OtherClient 的情况，那就不要创造问题

啊，这个 pr 里我没加 UnknownClient ，只是问一下是不是忘了处理

2022-02-14 20:56 UTC, Him188 requested changes

2022-02-14 20:56 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/events/MessageSyncEvent.kt
> +    public override val client: OtherClient,
修改构造器是 ABI 变更

2022-02-14 20:57 UTC, Him188 commented
这个可能比较难写

2022-06-08 21:35 UTC, Him188 commented
由于我没有你的分支的 push 权限, 我会开一个新的 PR.

2022-06-08 21:35 UTC, closed without merging