Improve `/permissions listPermissions`
mamoe/mirai pull request #1913
Opened 2022-03-08 05:39 UTC by Karlatemp

![image](https://user-images.githubusercontent.com/30070303/157173462-32d34627-9f2e-4d3d-bba8-0185bc74038f.png)

2022-03-08 12:02 UTC, Him188 approved these changes

2022-03-08 14:23 UTC, Him188 commented
红色是什么意思

2022-03-08 14:29 UTC, Karlatemp commented
> 红色是什么意思

较危险权限节点，高亮提醒不要随便给他人这些权限节点的

2022-03-22 16:42 UTC, Him188 requested changes

2022-03-22 16:42 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/permission/getPermittedPermissions.kt
> +internal fun PermitteeId.getPermittedPermissionsAndSource(): Sequence<Pair<PermitteeId, Permission>> {
放在 PermitteeId 附近更好

2022-03-25 11:42 UTC, Him188 approved these changes

2022-03-25 11:42 UTC, merged