docs add more java example
mamoe/mirai pull request #1943
Opened 2022-03-21 13:22 UTC by hundun000

2022-03-21 14:00 UTC, Him188 requested changes

2022-03-21 14:00 UTC, Him188 commented on mirai-console/docs/Commands.md
> +Example-kotlin:
```suggestion
Kotlin 示例：
```

2022-03-21 14:00 UTC, Him188 commented on mirai-console/docs/Commands.md
> +Example-java:
```suggestion
Java 示例：
```

2022-03-21 14:00 UTC, Him188 commented on mirai-console/docs/Commands.md
> +    @Handler // 标记这是指令处理器  // 函数名随意
```suggestion
    @Handler // 标记这是指令处理器，方法名随意
```
Java 叫方法，Kotlin 叫函数。

2022-03-21 14:00 UTC, Him188 commented on mirai-console/docs/Commands.md
> +Example-kotlin:
```suggestion
Kotlin 示例：
```

2022-03-21 14:00 UTC, Him188 commented on mirai-console/docs/Commands.md
> +Example-java:
```suggestion
Java 示例：
```

2022-03-21 14:10 UTC, hundun000 commented on mirai-console/docs/Plugins.md
> +
为了表示“可以在任意位置调用”，就没用类和方法包起来。不知道有没有更好的写法。

2022-03-21 15:36 UTC, Karlatemp commented on mirai-console/docs/Plugins.md
> +
这种全局可用片段这种使用目前写法就行

~~~
java 示例
```java
~~~

2022-03-21 15:36 UTC, Karlatemp commented on mirai-console/docs/Plugins.md
> +
缩进

2022-03-22 04:40 UTC, hundun000 commented on mirai-console/docs/Plugins.md
> +
若标为```java，idea的markdown语法检查会（在Problems栏）报error：'class' or 'interface' expected

2022-03-22 06:24 UTC, Karlatemp commented on mirai-console/docs/Plugins.md
> +
忽略就行

2022-03-22 10:19 UTC, Karlatemp approved these changes

2022-03-30 18:12 UTC, Him188 approved these changes

2022-03-30 18:13 UTC, merged