Native target
mamoe/mirai pull request #2048
Opened 2022-05-20 07:49 UTC by Him188

mirai-core native target
使用 ktor 实现网络部分, 其余的使用 Rust 实现

2022-05-21 09:48 UTC, AdoptOSS commented
可能有用的信息：
考虑到Mirai项目庞大而复杂的多线程架构，建议基于新的 Native GC 构建

> The new Kotlin/Native memory manager lifts restrictions on object-sharing between threads. It also provides leak-free concurrent programming primitives that are safe and don’t require any special management or annotations.
> 
> The new memory manager will become the default one in future versions, so we encourage you to try it now. [Learn more](https://blog.jetbrains.com/kotlin/2021/08/try-the-new-kotlin-native-memory-manager-development-preview/) about the new memory manager and explore demo projects, or jump right to the [migration instructions](https://github.com/JetBrains/kotlin/blob/master/kotlin-native/NEW_MM.md) to try it yourself.

2022-05-21 13:25 UTC, LaoLittle commented
> 考虑到Mirai项目庞大而复杂的多线程架构，建议基于新的 Native GC 构建

以及coroutines-native-mt （）

2022-05-21 13:28 UTC, AdoptOSS commented
> 以及coroutines-native-mt （）

不，`native-mt`是在老内存模型下的残缺的多线程支持，new mm下直接用新版的普通版本就行

2022-05-21 13:33 UTC, LaoLittle commented
> > 以及coroutines-native-mt （）
> 
> 不，`native-mt`是在老内存模型下的残缺的多线程支持，new mm下直接用新版的普通版本就行

这样的么，我还以为mt就是多线程支持

2022-05-25 15:39 UTC, Him188 commented
现在全项目已经可以编译, 正在修复因迁移多平台导致的 jvm 目标测试失败

----
启用了新 experimental 内存管理

2022-05-27 00:41 UTC, LaoLittle commented
‘currentTimeMillis’的话kotlin有个内置函数’getTimeMillis’，无需手动调用c库

2022-05-27 01:15 UTC, Him188 commented
> ‘currentTimeMillis’的话kotlin有个内置函数’getTimeMillis’，无需手动调用c库

那个是 ktor-utils 的东西，不是标准库，指不定哪天它就没了，最好不能依赖它

2022-05-27 03:49 UTC, LaoLittle commented
> 那个是 ktor-utils 的东西，不是标准库，指不定哪天它就没了，最好不能依赖它

在jvm里确实，不过在native上是`kotlin.system`

2022-05-27 04:23 UTC, LaoLittle commented
还有就是native的动态库链接可能会有问题（主要是konan所使用的工具链glibc版本过低导致的）

[KT-52510](https://youtrack.jetbrains.com/issue/KT-52510)
[KT-43501](https://youtrack.jetbrains.com/issue/KT-43501)
[KT-47061](https://youtrack.jetbrains.com/issue/KT-47061)

2022-05-27 09:22 UTC, Him188 commented
我知道有 kotlinx-datetime，但是增加一个库就增加了体积，对 mirai 只需要 current time 来说是没必要的。linker 目前没有遇到问题。

2022-05-27 16:51 UTC, LaoLittle commented
> 我知道有 kotlinx-datetime，但是增加一个库就

好的

2022-05-28 19:56 UTC, WetABQ commented
> 我知道有 kotlinx-datetime，但是增加一个库就增加了体积，对 mirai 只需要 current time 来说是没必要的。linker 目前没有遇到问题。

`kotlinx-datetime` 目前还没有正式发布，并且它将使用的 Kotlin 标准库升级到了 `1.7.0-Beta`，会导致项目引入多个不同版本状态下的 Kotlin 标准库

2022-05-28 23:39 UTC, Him188 commented
由于要支持数个目标平台，和一些 Kotlin 现阶段交互限制，我打算改为纯 Kotlin 实现。将会提供 C 交互 API，有可能未来也会提供 Rust API。

2022-06-01 22:38 UTC, Him188 commented
现在在 macos 可以登录
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/12100985/171513154-2b8e97ba-731c-47f4-b0bc-279375572c10.png">

2022-06-04 15:44 UTC, AdoptOSS requested changes

2022-06-04 15:44 UTC, AdoptOSS commented on mirai-core-utils/src/mingwX64Main/kotlin/MiraiFileImpl.kt
> +            CheckNameLegalDOS8Dot3A(absolutePath, nullPtr(), 0, nullPtr(), b.ptr)
Use unicode version api `CheckNameLegalDOS8Dot3W`

2022-06-04 15:44 UTC, AdoptOSS commented on mirai-core-utils/src/mingwX64Main/kotlin/MiraiFileImpl.kt
> +    private fun getFileAttributes(): DWORD = memScoped { GetFileAttributesA(absolutePath) }
Use unicode version api `GetFileAttributesW`

2022-06-04 15:44 UTC, AdoptOSS commented on mirai-core-utils/src/mingwX64Main/kotlin/MiraiFileImpl.kt
> +            val handle = CreateFileA(
Use unicode version api `CreateFileW`

2022-06-04 15:44 UTC, AdoptOSS commented on mirai-core-utils/src/mingwX64Main/kotlin/MiraiFileImpl.kt
> +            DeleteFileA(absolutePath) == 0
Use unicode version api `DeleteFileW`

2022-06-04 15:44 UTC, AdoptOSS commented on mirai-core-utils/src/mingwX64Main/kotlin/MiraiFileImpl.kt
> +            RemoveDirectoryA(absolutePath) == 0
Use unicode version api `RemoveDirectoryW`

2022-06-04 15:44 UTC, AdoptOSS commented on mirai-core-utils/src/mingwX64Main/kotlin/MiraiFileImpl.kt
> +            return CreateDirectoryA(absolutePath, v.ptr) == 0
Use unicode version api `CreateDirectoryW`

2022-06-04 15:44 UTC, AdoptOSS commented on mirai-core-utils/src/mingwX64Main/kotlin/MiraiFileImpl.kt
> +                    getcwd(it.addressOf(0), it.get().size.convert())
Use unicode version api `GetCurrentDirectoryW`

2022-06-04 15:44 UTC, AdoptOSS commented on mirai-core-utils/src/mingwX64Main/kotlin/MiraiFileImpl.kt
> +            CheckNameLegalDOS8Dot3A(absolutePath, nullPtr(), 0, nullPtr(), b.ptr)
> This function can be used to determine whether or not a file name can be passed to a 16-bit Windows-based application or an MS-DOS-based application.

这里似乎不应该使用它，Mirai创建的文件并不必须要可以在 16-bit 环境下可用

2022-06-04 16:39 UTC, Him188 commented
![image](https://user-images.githubusercontent.com/12100985/172016775-73dd83d0-7f33-4355-afe4-4104619e9d10.png)
现在 macOS 下全部测试通过

2022-06-04 16:41 UTC, Him188 commented
@AdoptOSS 谢谢, 之后测试 Windows 平台的时候会去修复 , 如果你想 review 那我之后就不 force push 了

2022-06-06 10:35 UTC, AdoptOSS requested changes

2022-06-06 10:35 UTC, AdoptOSS commented on buildSrc/src/main/kotlin/HmppConfigure.kt
> +private fun Project.configureNativeInterop(
Clean up

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-console/backend/mirai-console/test/command/LoginCommandTest.kt
> +    fun `login with provided password`() = runBlocking {
Use `kotlinx-coroutines-test`

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-console/backend/mirai-console/test/command/LoginCommandTest.kt
> +    fun `login with saved plain password`() = runBlocking {
Use `kotlinx-coroutines-test`

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-console/backend/mirai-console/test/command/LoginCommandTest.kt
> +    fun `login with saved md5 password`() = runBlocking {
Use `kotlinx-coroutines-test`

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/androidMain/kotlin/package.kt
> +package net.mamoe.mirai
好奇这个文件的用途

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/Event.kt
> +@Suppress("TOP_LEVEL_FUNCTIONS_NOT_SUPPORTED") // compiler bug
Details?
特殊注释
```suggestion
@Suppress("TOP_LEVEL_FUNCTIONS_NOT_SUPPORTED") // FIXME compiler bug
```

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/events/friend.kt
>      @JvmField
对于atomicfu而言，在JVM下默认就会转换了field并调用xxxUpdater
```suggestion
```

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/events/group.kt
>      @JvmField
```suggestion
```

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/events/group.kt
>      @JvmField
```suggestion
```

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/events/group.kt
> +    internal val responded: AtomicBoolean = atomic(false)
atomicfu通过自动修改内部代码实现，可能无法被安全的`published`
考虑使用委托 (due to kotlinx.atomicfu#186, 可能需要手动委托)

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/events/group.kt
> +        fun copy_default(
既然是为了jvm兼容性存在的，just move it into jvmMain

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/select.kt
> +    public fun MessageSelectionTimeoutChecker.invoke000(block: suspend () -> R): Nothing? {
move into jvmMain

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/select.kt
> +    public infix fun MessageSelectionTimeoutChecker.reply000(block: suspend () -> Any?): Nothing? {
move into jvmMain

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/select.kt
> +    public infix fun MessageSelectionTimeoutChecker.reply000(message: String): Nothing? {
move into jvmMain

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/select.kt
> +    public infix fun MessageSelectionTimeoutChecker.reply000(message: Message): Nothing? {
move into jvmMain

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/select.kt
> +    public infix fun MessageSelectionTimeoutChecker.quoteReply000(block: suspend () -> Any?): Nothing? {
move into jvmMain

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/select.kt
> +    public infix fun MessageSelectionTimeoutChecker.quoteReply000(message: String): Nothing? {
move into jvmMain

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/event/select.kt
> +    public infix fun MessageSelectionTimeoutChecker.quoteReply000(message: Message): Nothing? {
move into jvmMain

2022-06-06 10:35 UTC, AdoptOSS commented on mirai-core-api/src/commonMain/kotlin/message/data/Message.kt
> +        repeat(count) l@{
why?

2022-06-06 15:43 UTC, Him188 commented on mirai-core-api/src/androidMain/kotlin/package.kt
> +package net.mamoe.mirai
解决 IDE 在复制粘贴/移动文件时错误地删除包名的问题

2022-06-06 15:44 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/Event.kt
> +@Suppress("TOP_LEVEL_FUNCTIONS_NOT_SUPPORTED") // compiler bug
是 KJBB 的问题, 不用特地让人注意

2022-06-06 15:46 UTC, Him188 commented on buildSrc/src/main/kotlin/HmppConfigure.kt
> +private fun Project.configureNativeInterop(
不确定以后是否还会用它, 就留着了, 已经在我本地注释掉了

2022-06-06 15:48 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/events/friend.kt
>      @JvmField
它确实会 transform, 改的时候没注意

2022-06-06 15:50 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/events/group.kt
> +        fun copy_default(
那会需要把这整个 class 变成 expect/actual, 会增加复杂度, 在考虑之后还是留 common 好

2022-06-06 15:51 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/select.kt
> +    public infix fun MessageSelectionTimeoutChecker.quoteReply000(message: Message): Nothing? {
这个 class 可以考虑变 expect

2022-06-06 15:52 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Message.kt
> +        repeat(count) l@{
估计以前改的忘了删, 在这个 PR 里没必要修改

2022-06-09 11:52 UTC, Him188 commented
使用 Kotlin 生成的 API 的 C++ 登录:

```c++
int main() {
    const auto *symbols = libmiraicore_symbols();
    const auto mirai = symbols->kotlin.root.net.mamoe.mirai;
    const auto BotConfiguration = mirai.utils.BotConfiguration;
    mirai.internal.initMirai();


    auto conf = BotConfiguration.BotConfiguration();

    BotConfiguration.set_workingDir(conf, ".");
    BotConfiguration.set_protocol(conf, BotConfiguration.MiraiProtocol.ANDROID_PAD.get());
    BotConfiguration.fileBasedDeviceInfo(conf, "device.local.json");

    auto bot = mirai.BotFactory.INSTANCE.newBot__(
            mirai.BotFactory.INSTANCE._instance(),
            123456L,
            my_passwrod,
            conf
    );

    mirai.Bot.loginB(bot);
    mirai.Bot.joinB(bot);
    return 0;
}
```

2022-06-13 22:58 UTC, Him188 commented
Actions Windows 平台 7GB 内存不够链接

2022-06-15 02:52 UTC, AdoptOSS commented
尝试下通过调整GC策略来降低 RAM 占用，看看可不可行？
比如使用 OpenJ9 这种专注于 RAM 优化的 JVM

2022-06-15 12:48 UTC, AdoptOSS commented
尝试修改了一些actions的设置：
- OpenJ9可以减少内存使用，但似乎会导致jvm下2个test不通过
- Java占用内存过大可以修改jvmArgs为`-Xmx3072m`来减少异常，本来的`-Xmx7000m`会导致极大的内存占用（jvm不会过于积极地回收），由于link步骤需要调用外部程序，而外部程序的内存分配失败无法被Java的GC所感知（java自己分配的话，如果内存不足，会去跑一下回收程序占分配），过大的数值极易导致linker内存分配失败
- 在`-Xmx***`较低的情况下，甚至可以启用daemon（似乎build速度有所提升）
- Windows下native的编译配置，缺少安装curl的必要步骤（还没调试成功【我好菜】）

2022-06-15 13:01 UTC, Him188 commented
Xmx 4000，kotlin 编译器就会说  OOM，所以之前改成 6000 了，然后测试了一下 7000

2022-06-15 13:21 UTC, AdoptOSS commented
我这算是勉强在win下跑出了 lld: error: unable to find library -lcurl 吧
https://github.com/AdoptOSS/mirai/runs/6899864946

Sent from Outlook for Android<https://aka.ms/ghei36>

________________________________
发件人: Him188 ***@***.***>
发送时间: 2022年6月15日星期三 下午9:01
收件人: mamoe/mirai
抄送: AdoptOSS; Mention
主题: Re: [mamoe/mirai] Native target (PR #2048)


Xmx 4000，kotlin 编译器就会说 OOM，所以之前改成 6000 了，然后测试了一下 7000

―
Reply to this email directly, view it on GitHub<https://github.com/mamoe/mirai/pull/2048#issuecomment-1156443264>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AROIETEH2IE56BU37AVR2X3VPHH3ZANCNFSM5WOS6VAA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-06-15 15:39 UTC, Him188 commented
@AdoptOSS 尝试给 link 那个 task 单独 Xmx3000 可以 link 上，目前在修库

2022-06-15 15:47 UTC, AdoptOSS commented on mirai-core/src/nativeMain/cinterop/OpenSSL.def
>                               -IC:/openssl/include/ \
感觉要用 `-IC` 的吧

2022-06-15 15:48 UTC, AdoptOSS commented on mirai-core/src/nativeMain/cinterop/OpenSSL.def
> +                             -LC:/vcpkg/packages/curl_x64-windows/include \
感觉要用 `-IC` 的吧

2022-06-15 15:48 UTC, Him188 commented on mirai-core/src/nativeMain/cinterop/OpenSSL.def
> +                             -LC:/vcpkg/packages/curl_x64-windows/include \
确实

2022-06-16 04:58 UTC, AdoptOSS commented
把link也调试出来了
找不到库其实不是搜索目录的问题，而是Windows下的查找规则，不会自动给你加`lib`前缀
```yaml
      - if: ${{ env.isWindows == 'true' }}
        name: Install OpenSSL & cURL
        run: |
          echo "set(VCPKG_BUILD_TYPE release)" | Out-File -FilePath "$env:VCPKG_INSTALLATION_ROOT\triplets\x64-windows.cmake" -Encoding utf8 -Append
          vcpkg install openssl:x64-windows curl[core,openssl]:x64-windows
          New-Item -Path $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\crypto.lib -ItemType SymbolicLink -Value $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\libcrypto.lib
          New-Item -Path $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\ssl.lib -ItemType SymbolicLink -Value $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\libssl.lib
          New-Item -Path $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\curl.lib -ItemType SymbolicLink -Value $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib\libcurl.lib
          echo "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
```

2022-06-17 12:20 UTC, Him188 commented
没 Windows 电脑了，最近一个月没法测了

2022-07-19 16:30 UTC, merged