QRCode on UnsafeDeviceVerify
mamoe/mirai pull request #2079
Opened 2022-06-07 02:57 UTC by Karlatemp

![image](https://user-images.githubusercontent.com/30070303/172286092-4b332759-9e63-4eae-b0ff-3c49d7fdef7c.png)

2022-06-07 09:39 UTC, Him188 requested changes

2022-06-07 09:39 UTC, Him188 commented on mirai-core-all/build.gradle.kts
> +    api(`zxing-javase`)
why api

2022-06-07 09:39 UTC, Him188 commented on mirai-core-utils/src/jvmMain/kotlin/PlatformImage.jvm.kt
> +private val zxingSupport = if (
Use ServiceLoader

2022-06-07 10:17 UTC, Him188 commented
要不做一个独立JVM模块，只用core的人可以单独依赖，mirai-core-all默包含

2022-06-07 10:37 UTC, Karlatemp commented
那什么名字比较合适呢， `mirai-core-platform-image`?

2022-06-07 11:14 UTC, Him188 commented
> 

mirai-login-solver-qr ?

2022-06-07 11:20 UTC, Karlatemp commented
那以后要加其他的图像处理的时候也得创建新的模块，我想把qr和未来可能的其他处理塞到一个模块内作为可选扩展

2022-06-07 12:50 UTC, Him188 commented
我觉得就是应该创建新模块，反正多一个模块也不多很多麻烦。

2022-06-07 12:51 UTC, Him188 commented
> 要不做一个独立JVM模块，只用core的人可以单独依赖，mirai-core-all默包含

我觉得还是不要默认包含好，让那个模块本身也可以作为 console 插件，然后 mcl 默认安装吧

2022-06-07 13:20 UTC, Karlatemp commented
> > 要不做一个独立JVM模块，只用core的人可以单独依赖，mirai-core-all默包含
> 
> 我觉得还是不要默认包含好，让那个模块本身也可以作为 console 插件，然后 mcl 默认安装吧

那样的话修改太大了，all 默认包含其实也没什么大问题

2022-06-07 13:22 UTC, Him188 commented
有问题，捆绑是不好的，就跟selemium一样

2022-06-07 15:47 UTC, Karlatemp commented
那可以把 all 的默认提供去掉, 让用户自己执行 `./mcl --update-package net.mamoe:mirai-core-utils-platform-image  --channel stable --type core`

2022-06-07 15:49 UTC, Him188 commented
> 那可以把 all 的默认提供去掉, 让用户自己执行 `./mcl --update-package net.mamoe:mirai-core-utils-platform-image --channel stable --type core`

我就是这样想的, 让它 compileOnly mirai-console 然后加个 service 就可以当做插件用也可以给 core 用了吧

2022-06-13 18:52 UTC, Him188 reviewed
我觉得这个模块名字不好，它应该只包含二维码功能，而不是将来会逐渐变得臃肿（像是捆绑安装）

2022-06-15 02:31 UTC, AdoptOSS commented
我更倾向于按现实世界的使用习惯来分类命名模块，并尽量减少 `core` 里的非协议功能
- `mirai-login-solver-desktop` 
   所有有关验证的 UI 都可以放里面（包括以前的对话框），从用户角度来讲基本上要用就都会用到
   ~不过像 `selemium` 这种环境要求复杂的可以单独出来 `mirai-login-solver-desktop-with-selemium`~ （当然 `selemium` 已经弃用了）
- `mirai-login-solver-android`

而对于 `core`， 只需要提供 `LoginSolver` 接口就行

ps. 安装OOP的理想情况，`LoginSolver`接口应该设计为
```
LoginSolver --> SliderLoginSolver
            --> CaptchaLoginSolver
```
然后根据具体的`LoginSolverImpl`是否实现对应的子接口来区分支持的验证类型（尽量不要引入过多的 `CanXXX` / `SupportXXX` 属性）

2022-06-15 02:34 UTC, AdoptOSS commented
然后就是，现在 `mirai` 已经有较为完善的 `SPI` 了，像以前那种引入一大堆系统变量、硬编码`Class.forName`查询`LoginSolver`的行为大概都可以去除/废弃了（除非是为了兼容性考虑）

2022-06-15 08:55 UTC, Him188 commented
@AdoptOSS 确实，我比较赞成你的想法

2023-09-02 03:26 UTC, closed without merging