Support change friend remark
mamoe/mirai pull request #2112
Opened 2022-06-24 08:17 UTC by Nambers

close #554 
目前还有个问题，他的decode方法不会运行到

2022-06-24 08:24 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/AbstractMember.kt
Why change it to var

2022-06-24 08:24 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/Friend.kt
> +
kdoc

2022-06-24 08:25 UTC, Nambers commented on mirai-core/src/commonMain/kotlin/contact/AbstractMember.kt
在qq客户端Member如果不是Friend的话是改不了备注的，只能改nameCard

2022-06-24 08:28 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/AbstractMember.kt
我给看成了 `val` -> `var` :(

2022-06-24 08:32 UTC, Him188 commented
不会被运行是因为你要到 KnownPacketFactories 增加

2022-06-24 08:34 UTC, Nambers commented
> 不会被运行是因为你要到 KnownPacketFactories 增加

okok 确实漏做了文档这一部分

2022-06-24 08:45 UTC, Nambers commented
> 不会被运行是因为你要到 KnownPacketFactories 增加

那我pr的目标branch是应该改成native-target吧? 毕竟要注册的都在那?

2022-06-24 09:02 UTC, Him188 commented
可以，native过几天就要合了，不过后面你肯定再要rebase回dev

注意这个不是 SPI，是静态写的

2022-06-25 04:53 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Friend.kt
> +     * 更改后会触发 FriendRemarkChangeEvent
```suggestion
     * 更改后会触发 [FriendRemarkChangeEvent]
```

2022-06-25 05:06 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/Friend.kt
> +
```
备注信息

更改备注后会广播 [FriendRemarkChangeEvent]

@see User.remarkOrNick
@see FriendRemarkChangeEvent
```

2022-06-25 05:06 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +        }
根据

https://github.com/mamoe/mirai/blob/1110a6f3fa400b3bc0b6e43acecac548d33537d9/mirai-core/src/commonMain/kotlin/network/notice/priv/FriendNoticeProcessor.kt#L220-L227

我认为没必要在这里修改 field, 而且也容易造成并发错误, 并发可能导致 `FriendRemarkChangeEvent` 的广播内容不正确

把 `remarkField = ` 改为 `// remark field updated in FriendNoticeProcessor.handleRemarkChanged`

并且修改后 remarkField 就没有必要了 get 也可以直接改成 `get() = info.remark`

2022-06-25 05:17 UTC, Nambers commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +        }
> 根据
> 
> https://github.com/mamoe/mirai/blob/1110a6f3fa400b3bc0b6e43acecac548d33537d9/mirai-core/src/commonMain/kotlin/network/notice/priv/FriendNoticeProcessor.kt#L220-L227
> 
> 我认为没必要在这里修改 field, 而且也容易造成并发错误, 并发可能导致 `FriendRemarkChangeEvent` 的广播内容不正确
> 
> 把 `remarkField = ` 改为 `// remark field updated in FriendNoticeProcessor.handleRemarkChanged`
> 
> 并且修改后 remarkField 就没有必要了 get 也可以直接改成 `get() = info.remark`

之前我试过不改但是好像remark本身没有改变? 我待会再试一下如果改了就改成这个

2022-06-25 05:24 UTC, Nambers commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +        }
> 根据
> 
> https://github.com/mamoe/mirai/blob/1110a6f3fa400b3bc0b6e43acecac548d33537d9/mirai-core/src/commonMain/kotlin/network/notice/priv/FriendNoticeProcessor.kt#L220-L227
> 
> 我认为没必要在这里修改 field, 而且也容易造成并发错误, 并发可能导致 `FriendRemarkChangeEvent` 的广播内容不正确
> 
> 把 `remarkField = ` 改为 `// remark field updated in FriendNoticeProcessor.handleRemarkChanged`
> 
> 并且修改后 remarkField 就没有必要了 get 也可以直接改成 `get() = info.remark`

就比如
```kotlin
bot.eventChannel.subscribeAlways<FriendMessageEvent> {
        this.friend.remark = this.message.contentToString()
        assertEquals(this.message.contentToString(), friend.remark)
    }
```
这里的assert我本地测试是fail的, 可能还是要手动先改而不是等服务器发event?

2022-06-25 05:25 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +        }
如果直接改的话, `FriendRemarkChangeEvent` 的 new 和 old 就都会只是 new, 这是不行的

2022-06-25 05:35 UTC, Nambers commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +        }
> 如果直接改的话, `FriendRemarkChangeEvent` 的 new 和 old 就都会只是 new, 这是不行的

那.. 有点难搞, 在setter里等这个包返回后手动broadcast，然后在那边判断new != old 否则不广播?

2022-06-25 11:27 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +        set(value) {
`info.remark`

2022-06-25 11:27 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +                    info::remark.set(value)
`info.remark = `

2022-06-25 11:30 UTC, Nambers commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +        set(value) {
![image](https://user-images.githubusercontent.com/35139537/175771616-deb9cc19-128e-46dc-8d4d-58a1ec45545e.png)
不行欸

2022-06-26 03:09 UTC, Him188 requested changes

2022-06-26 03:09 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +            }
runBlocking 肯定是不行的

2022-06-26 03:14 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +            }
一个解决方法是还原这部分代码到你 kar review 之前的, 你只需要在 NoticeProcessor 里面 if 一下是否有更新就足够了

另外这部分代码也没有检测是不是真的有变更

2022-06-26 03:18 UTC, Nambers commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +            }
主要就是更改remark后，remark的值应该是这次赋值的，还是等那个remarkChangeEvent事件再同步. 如果是这次更改的，就要用runBlocking等sendAndExcept结果，然后按照结果赋值? 如果不是这次赋值的就简单很多，直接发包然后等那边事件同步就好

2022-06-26 04:33 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +            }
目前群设置是不考虑修改是否实际生效. 我建议保持相同行为

至于并发修改问题, 这属于小概率事件, 在目前协议上也可能无法做到区分 (它需要协议上的验证), 可以无需考虑

2022-06-26 04:35 UTC, Nambers commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +            }
> 目前群设置是不考虑修改是否实际生效. 我建议保持相同行为
> 
> 至于并发修改问题, 这属于小概率事件, 在目前协议上也可能无法做到区分 (它需要协议上的验证), 可以无需考虑

okok 也就是说remark改后直接赋值然后广播事件再异步发包，不用阻塞来判断包结果

2022-06-26 04:37 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +            }
群设置的行为是包发完了再广播事件

2022-06-26 04:40 UTC, Nambers commented on mirai-core/src/commonMain/kotlin/contact/FriendImpl.kt
> +            }
> 群设置的行为是包发完了再广播事件

那如果遇到包返回了错误，那是应该把remark改回去然后就不继续广播事件吗

2022-07-03 02:50 UTC, Him188 approved these changes

2022-07-20 07:09 UTC, Him188 commented
请 rebase 到 dev

2022-07-20 14:14 UTC, Nambers commented
> 请 rebase 到 dev

我目前用的merge, 你们到时候square? 还是说必须要rebase(

2022-07-20 15:03 UTC, Him188 commented
尽量 rebase, 你的这个 PR 应该会 squash 合

2022-07-20 15:04 UTC, Nambers commented
rebase 了

> 尽量 rebase, 你的这个 PR 应该会 squash 合

已经rebase了，在修因为merge带来的ci问题

2022-08-14 02:15 UTC, merged