add group level api
mamoe/mirai pull request #2115
Opened 2022-06-24 17:44 UTC by cssxsh

添加群聊等级 api

2022-06-25 05:16 UTC, Karlatemp requested changes

2022-06-25 05:16 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/GroupLevelInfo.kt
> +public data class GroupLevelInfo(
`@MiraiExperimentalApi`

2022-06-25 05:16 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/GroupLevelInfo.kt
> +    public data class LevelName(
`@MiraiExperimentalApi`

2022-06-25 05:16 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/GroupLevelInfo.kt
> +    val levelName: LevelName
根据数据结构是不是使用 `Map<String, String>` 更好

然后提供个方法 `fun getLevelName(lv: Int): String?`

2022-06-25 05:16 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +                        }
不好的设计, `LevelName` 都有 `lvln1xx` 了，而且结构也是不连续的

2022-06-25 05:24 UTC, cssxsh commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +                        }
> 不好的设计, `LevelName` 都有 `lvln1xx` 了，而且结构也是不连续的


设置貌似只有 lvln1~lvln6 是有效的，其他等级在我的测试中无法被设置

2022-06-25 05:26 UTC, cssxsh commented on mirai-core-api/src/commonMain/kotlin/data/GroupLevelInfo.kt
> +    val levelName: LevelName
> 根据数据结构是不是使用 `Map<String, String>` 更好
> 
> 然后提供个方法 `fun getLevelName(lv: Int): String?`


实际上 GroupLevelInfo.LevelName 和 GroupHonorListData.LevelName 结构是相似的，
但从 GroupHonorListData.LevelName 来看 只有 lvln1~lvln6 有效，其他等级貌似是废弃的

2022-06-25 05:33 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/GroupLevelInfo.kt
> +    val levelName: LevelName
如果是这样的话, 那应该把无效的字段剔除掉, 并且添加注释说明对应什么

2022-06-25 05:33 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +                        }
设置里是可以设置单条的， 考虑一下仅设置某一条的情况

2022-06-25 06:09 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/GroupLevelInfo.kt
> +    public data class LevelName(
确实这个应该用 map

2022-06-25 06:13 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/LowLevelApiAccessor.kt
> +    public suspend fun getRawGroupLevelInfo(
真的有必要提供这些 experimental 的 API 么，experimental 的东西插件不能用，直接用 core 的人用着也有隐患。我认为应该直接在 Group 提供高级且稳定的 API，而将这些协议实现隐藏。

这些 low level API 经过这两三年，也确实越来越不好了，它们全塞在 IMirai 导致这个接口越来越大，杂乱且维护难。低级 API 又有很大的使用难度（LowLevelApi 和 Experimental 注解），用户都不敢用。

2022-06-25 06:13 UTC, cssxsh commented on mirai-core/src/commonMain/kotlin/MiraiImpl.kt
> +                        }
> 设置里是可以设置单条的， 考虑一下仅设置某一条的情况

好的

2022-06-25 06:24 UTC, cssxsh commented on mirai-core-api/src/commonMain/kotlin/LowLevelApiAccessor.kt
> +    public suspend fun getRawGroupLevelInfo(
> 

我只是 仿照 getRawGroupHonorListData 和 getRawGroupActiveData 提供新的api，怎样封装标准化我不想去思考（摆烂）

不过或许 应该 可以将 getRawGroupHonorListData  getRawGroupActiveData  getRawGroupLevelInfo
封装到一起，类似 公告 api 弄一个 Group.honor

2022-06-25 17:54 UTC, cssxsh commented
接下来 打算 把 getRawGroupHonorListData 和 getRawGroupActiveData
转移到 active 包
先对api进行一下测试，看看返回的内容

2022-06-26 15:38 UTC, Him188 commented
用户等级叫 level，要不群聊等级叫 rank 吧

2022-06-26 15:42 UTC, cssxsh commented
> 用户等级叫 level，要不群聊等级叫 rank 吧

好的

2022-07-03 04:48 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupHonorFlag.kt
> +public enum class GroupHonorFlag(private val value: Int) {
这个值有可能可以扩展或者由群主自定义之类的吗? 如果是, 那用 inline class 比较好

2022-07-03 04:48 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Member.kt
> +    public val temperature: Int
感觉合起来更好?
 `val rank: MemberRank`

```kotlin
interface MemberRank {
  val activeLevel  // 群活跃等级
  val activePoint // 活跃积分
  val titles // 荣誉标识 (因为语义有称号的意思, 就叫做 title 吧)
  val honorLevel // 群荣誉等级
}
```

2022-07-03 04:48 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/Active.kt
> +    public var rankShow: Boolean
这些并没有必要作为公开 API, 在 Member 里有就可以了

2022-07-03 04:48 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveChart.kt
> +}
数据的键和值分别是什么?

2022-07-03 04:48 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupHonorFlag.kt
> +        public fun deserializeFromInt(value: Int): GroupHonorFlag? = values().find { it.value == value }
`fromInt`

`values()` 每次都会创建一个 Array, 可缓存一下

2022-07-03 06:23 UTC, cssxsh commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupHonorFlag.kt
> +public enum class GroupHonorFlag(private val value: Int) {
> 扩展

有可能 因为群荣誉功能变更，目前系统里有包括龙王，群聊之火，等共五个称号，以后可能会被拓展
我在考虑隐藏 这个 flag，然后通过 isXXX  方法 来判断群员是否拥有称号

2022-07-03 06:24 UTC, cssxsh commented on mirai-core-api/src/commonMain/kotlin/contact/active/Active.kt
> +    public var rankShow: Boolean
> 这些并没有必要作为公开 API, 在 Member 里有就可以了

rankTitles 和 rankShow 都是 对于群而言的设置，可以被管理员更改

2022-07-03 06:25 UTC, cssxsh commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveChart.kt
> +}
> 数据的键和值分别是什么?

疏忽了，忘记写这部分文档

键是 "yyyy-MM-dd" 格式的日期
值是 次数，发言次数，退群人数之类的

2022-07-03 06:58 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupHonorFlag.kt
> +public enum class GroupHonorFlag(private val value: Int) {
那更不好了, 方法越多越难维护

2022-08-24 12:20 UTC, sandtechnology commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupHonorFlag.kt
> +public enum class GroupHonorFlag(private val value: Int) {
> > 扩展
> 
> 有可能 因为群荣誉功能变更，目前系统里有包括龙王，群聊之火，等共五个称号，以后可能会被拓展 我在考虑隐藏 这个 flag，然后通过 isXXX 方法 来判断群员是否拥有称号

应该使用enum然后用isHaveHonor方法来判断比较好

2022-08-25 07:13 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/Active.kt
> +    public suspend fun getChart(): ActiveChart?
suspend, 需要 `@JvmBlockingBridge`. 建议添加到 file 级别

2022-08-25 07:13 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveChart.kt
> + * 活跃度数据图表， Key 是  yyyy-MM 格式的日期，Value 是 数量
```suggestion
 * 活跃度数据图表， 键是 `yyyy-MM` 格式的日期，值是数量
```

2022-08-25 07:13 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveChart.kt
> +public data class ActiveChart(
no data class

2022-08-25 07:13 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveRecord.kt
> +public data class ActiveRecord(
no data class

如果没有绝对的必要, 不提供公开构造器. 若需要构造, 提供 Builder

2022-08-25 07:13 UTC, Him188 commented on mirai-core-api/src/jvmBaseMain/kotlin/contact/active/Active.kt
> +    public fun asStream(): Stream<ActiveRecord>
可以标记 `@JavaFriendlyApi`

2022-08-25 07:14 UTC, Him188 commented
在解决 review 问题后, 请点 'Resolve conversation'

2022-08-26 09:55 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/MemberActive.kt
> +    public val honor: Set<GroupHonorType>
```suggestion
    public val honors: Set<GroupHonorType>
```

2022-08-26 09:55 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/MemberActive.kt
> +public interface MemberActive {
NotStableForInheritance

2022-08-26 09:55 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/Active.kt
> +public expect interface Active {
改叫 GroupActive? 因为有 MemberActive 了

2022-08-26 09:55 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/Active.kt
> + * 设置时，修改将异步发送到服务器
其实我觉得这种异步不是很好（即使历史上有这些设计），它没法获得操作结果。要不改成 `suspend fun setXXX()`? CC @Karlatemp

2022-08-26 09:55 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/MemberActiveImpl.kt
> +internal value class MemberActiveImpl(private val memberInfo: MemberInfo) : MemberActive {
这个 value class 反而会影响性能，每次使用时都会 box

2022-08-26 10:02 UTC, Him188 reviewed
然后添加 `@since 2.13` 就可以了

2022-08-26 10:02 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveRecord.kt
> +    public val sender: NormalMember?,
```suggestion
    public val member: NormalMember?,
```

2022-08-26 10:02 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveRecord.kt
> +    public val senderId: Long,
```suggestion
    public val memberId: Long,
```

2022-08-26 10:02 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveRecord.kt
> +    public val senderName: String,
```suggestion
    public val memberName: String,
```

2022-08-26 10:02 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveRecord.kt
> +    public val continuation: Int,
```suggestion
    public val periodDays: Int,
```

2022-08-26 10:02 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveRecord.kt
> +    public val sentences: Int
```suggestion
    public val messagesCount: Int
```

2022-08-26 10:02 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/GroupHonorListData.kt
>      MANAGE(9);          // 管理头衔
我觉得把这个 enum 变成 value class，不然它协议变了还得改

2022-08-26 12:47 UTC, cssxsh commented
关联的 issue 应该还有这个 https://github.com/mamoe/mirai/issues/2086

2022-08-26 13:46 UTC, Moyuyanli commented
这是好了吗？

2022-08-26 17:04 UTC, Him188 commented
不要 force push

2022-08-27 05:55 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Member.kt
> +    public val rankTitle: String get() = group.active.rankTitles[active.rank].orEmpty()
我觉得不存在时给 null 比较好

2022-08-27 05:55 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/MemberActive.kt
> +     * 这个等级是在 PC端 成员管理功能中显示的等级
```suggestion
     * 这个等级是在 PC 端成员管理功能中显示的等级
```

2022-08-27 05:55 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/MemberActive.kt
> +     * 这个积分是在 PC端 成员管理功能中显示的积分，和手机端显示的 群荣誉活跃积分 不同
```suggestion
     * 这个积分是在 PC 端成员管理功能中显示的积分，和手机端显示的群荣誉活跃积分不同
```

2022-08-27 05:55 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupActive.kt
> +     * 等级头衔列表，key 是 等级，value 是 头衔
```suggestion
     * 等级头衔列表，键是等级，值是头衔
```

2022-08-27 05:55 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/ActiveHonorCurrent.kt
> +    public val count: Int,
```suggestion
    public val termDays: Int,
```
term — 任期

2022-08-27 05:56 UTC, Him188 commented
> 这是好了吗？

2.13 会好, 预计一周内就会发版了

2022-08-27 06:07 UTC, cssxsh commented on mirai-core-api/src/commonMain/kotlin/contact/Member.kt
> +    public val rankTitle: String get() = group.active.rankTitles[active.rank].orEmpty()
> 我觉得不存在时给 null 比较好

群成员入群就会是 rank=1 的 状态，而 rankTitles 也是有默认值的，除非解析错误之类的，不然肯定是 有值的

2022-08-27 06:16 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Member.kt
> +    public val rankTitle: String get() = group.active.rankTitles[active.rank].orEmpty()
OK, 那确实给 empty 更合适, 可以备注一下

2022-08-29 15:36 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/active/Active.kt
> + * 设置时，修改将异步发送到服务器
qs

2022-08-29 15:59 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupActive.kt
> +    public var honorShow: Boolean
感觉 `isHonorVisible` 会更好

2022-08-29 15:59 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupActive.kt
> +    public suspend fun getChart(): ActiveChart?
`queryChart()`

2022-08-29 15:59 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupActive.kt
> +    public suspend fun getHonorList(type: GroupHonorType): ActiveHonorList?
`queryHonorHistory`

2022-08-29 15:59 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/GroupInfo.kt
> +
`isTitleVisible`

2022-08-29 15:59 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/info/MemberInfoImpl.kt
> +                    }
```
} catch (ignored: Throwable) {}
```

2022-08-29 16:17 UTC, cssxsh commented on mirai-core/src/commonMain/kotlin/contact/info/MemberInfoImpl.kt
> +                    }
> ```
> } catch (ignored: Throwable) {}
> ```

这样写有什么特殊作用吗，kotlin `_` 忽略 变量名的写法我觉得挺好看的
如果是方便检索, 或许可以改成这样？
```
} catch (_: Throwable) {
    // ignored
}
```

2022-08-29 16:21 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/info/MemberInfoImpl.kt
> +                    }
以ignore为参数名不需要 // 抑制idea的警告

2022-08-29 16:22 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/info/MemberInfoImpl.kt
> +                    }
`_` 确实是 Kotlin 官方推荐的做法，大概是 1.7.0 才有的吧，underscore 是一个不可被引用的符号

2022-09-07 05:25 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/MemberMedalDetail.kt
> +    public val worn: MemberMedalType,
```suggestion
    public val wearing: MemberMedalType,
```

2022-09-07 05:25 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/MemberMedalDetail.kt
> +public class MemberMedalDetail internal constructor(
```suggestion
public class MemberMedalInfo internal constructor(
```
前面的 Active 命名是 MemberActiveInfo, 这里也用 Info 命名比较好

2022-09-07 05:25 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/active/GroupActive.kt
> +    public var temperatureTitles: Map<Int, String>
写 val 和 suspend fun setXxx 比较好. 另外可以不需要 experimental

2022-09-07 05:25 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/GroupHonorType.kt
> +}
建议使用 value class, 这会是 ABI change 但 `MemberHonorChangeEvent` 是 experimental 就没事.

建议在修改之后也去掉 `MemberHonorChangeEvent` 的 experimental 标记, 提供稳定 API.

2022-09-13 01:57 UTC, Him188 commented
完成修改后请点 'Resolve conversation'!

2022-09-13 02:05 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/GroupHonorType.kt
>      }
Kotlin 会 mangle 所有使用了 inline class 的函数, 需要单独给他们加一个 `@JvmName` 才能让 Java 看到返回 backing field `value` 的 Int 的函数

然后我猜你是想弄 `public static final` 的字段, 那应该使用 `@JvmField`

2022-09-16 03:58 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/GroupHonorType.kt
>      }
@cssxsh 我改好了, 可以设置 PR 允许 maintainer 修改么

2022-09-16 05:37 UTC, Him188 approved these changes

2022-09-16 10:06 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/GroupHonorType.kt
> +        public const val TALKATIVE_ID: Int = 1
这些用 `ID_XXX` 会不会更好一点, 这更方便 ide 补全

2022-09-16 10:06 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/data/GroupInfo.kt
> +
`isXXXVisible`

2022-09-16 10:06 UTC, Karlatemp commented on mirai-core-mock/src/internal/contact/active/MockGroupActive.kt
> +    }
非 mock 直接api应该有权限检查

2022-09-16 10:06 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
> +    val lastTalkative = atomic(members.find { GroupHonorType.TALKATIVE in it.active.honors })
是没有根据 group.active **直接**搜索 lastTalkative 的方法吗

2022-09-20 10:52 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/GroupHonorType.kt
> +        public const val TALKATIVE_ID: Int = 1
我觉得不用, IDEA 会根据语境需要的类型和字段类型排序, 而且会学习你经常选的东西

2022-09-20 10:57 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
> +    val lastTalkative = atomic(members.find { GroupHonorType.TALKATIVE in it.active.honors })
估计是的

2022-09-20 14:20 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/active/GroupActiveImpl.kt
> +                    { "Failed to set honor show for group ${group.id}" },
err msg没有改

2022-09-20 14:20 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/active/GroupActiveImpl.kt
> +                    { "Failed to set title show for group ${group.id}" },
err msg

2022-09-20 14:20 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/active/GroupActiveImpl.kt
> +                    { "Failed to set temperature show for group ${group.id}" },
-

2022-09-20 14:20 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/active/GroupActiveImpl.kt
> +                    { "Failed to flush member active for group ${group.id}" },
Failed to refresh?

2022-09-21 14:41 UTC, Karlatemp approved these changes

2022-09-21 15:18 UTC, merged

2023-01-24 08:02 UTC, aleck099 commented
@cssxsh 在 ANDROID_PAD 协议下获取的所有rank都是 1 级
是不是因为ANDROID_PAD不支持ranks

2023-01-24 08:20 UTC, aleck099 commented
在 ANDROID_PHONE 协议下获取到的rank也全是 1 级

2023-01-24 13:32 UTC, cssxsh commented
> @cssxsh 在 ANDROID_PAD 协议下获取的所有rank都是 1 级 是不是因为ANDROID_PAD不支持ranks

`rank` (1-6) 是旧版的群等级，目前处于半废弃状态，官方客户端中只有pc客户端能看到
而且新群一般都没有这个等级了

建议你使用 `temperature` (1-100) 这个手机端中显示的活跃度等级