[core] Introduce `Flow<T>.toStream()` for simply implement `Streamable`
mamoe/mirai pull request #2259
Opened 2022-09-26 15:44 UTC by Karlatemp

2022-09-27 13:57 UTC, Him188 requested changes

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +        var nextStep: Continuation<Unit>? = run {
它应该 lazy 初始化 (可使用 `lateinitMutableProperty`

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +    }
我还是觉得不应该改变异常类型

改变异常类型将导致行为不确定, 且调用方无法处理真实异常. 为了 stacktrace 而改变类型显然是不值得的

Kotlin 的协程库是通过 `kotlinx.coroutines.internal.recoverFromStackFrame` 来恢复调用栈的. 它会尝试"复制"一份实例(可能反射构造器), 然后通过协程创建时的 `CoroutineStackFrame` 信息恢复. See also  `kotlin.coroutines.jvm.internal.CoroutineStackFrame`

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +        }
这个 `NULL_PLACEHOLDER` 看起来没有意义

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +                    }
```suggestion
                    suspendCancellableCoroutine<Unit> { cont ->
                        nextStep = cont
                        queue.put(boxValue(item))
                    }
```

do you mean 'cont' for 'continuation'?

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +        private val queue = ArrayBlockingQueue<Any?>(4)
size 为什么是 4? 1 就够了吧

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +                        }
```suggestion
                        suspendCoroutineUninterceptedOrReturn<Unit> { cont ->
                            nextStep = cont
                            queue.put(boxValue(item))
                            COROUTINE_SUSPENDED
                        }
```

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +    ): Stream<T> {
应当说明 flow 的 collect 会在哪个线程运行. 因为 collect 可能会抛出异常.

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +            return@run (suspend {
如果是相对立的分支处理, 建议使用 if-else

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +            return true
如果是相对立的分支处理, 建议使用 if-else

2022-09-27 13:57 UTC, Him188 commented on mirai-core-api/src/jvmBaseMain/kotlin/utils/Streamable.kt
> +     * ```
令 `nextStep` lazy 初始化后就不需要了

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +            return true
我不是很理解这个叫做 `complete` 方法做了什么, 叫做 `complete` 的它有副作用, 你可能想叫 `tryComplete`.

2022-09-27 13:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +            if (unintercepted) {
似乎没有理由允许 unintercepted

2022-09-27 14:24 UTC, Karlatemp commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +        }
queue不允许放入null

2022-09-27 14:25 UTC, Karlatemp commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +        private val queue = ArrayBlockingQueue<Any?>(4)
qs

2022-09-27 14:26 UTC, Karlatemp commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +            return true
我忘记重命名了

2022-09-27 14:27 UTC, Karlatemp commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +        var nextStep: Continuation<Unit>? = run {
不需要，continuation本来就是懒启动

2022-09-27 14:28 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +    ): Stream<T> {
可以先不解决这个, 明天我再仔细看看

2022-09-28 14:42 UTC, Karlatemp commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +    }
转换出来的stream是要给Java使用的，那么应该按照java的设计来

1. jdk 自身的异步错误也会全部包装成 ExecutionException
2. 反射也会包装成 InvocationTargetException
3. 另外再加上 java.net.http 的实现, 她的逻辑也是不管什么错误也是 IOException
4. 错误类型的转换在 java 的架构中很常见，特别是这种只能抛出 unchecked exception 的情况下

----

按照你所说的不应该转换类型，但是Java语法层面就不能捕获kotlin直接抛出的 checked exception. 为了体验不如全部包装一层

2022-09-29 01:40 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +    }
可以包装, 但那么你就应该全都包装, 统一行为

2022-10-20 12:35 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Streams.kt
> +        unintercepted: Boolean = context[ContinuationInterceptor] == null,
似乎没有理由 unintercepted

2022-10-29 10:22 UTC, Him188 approved these changes

2022-10-29 10:22 UTC, Him188 commented on mirai-core-utils/src/jvmBaseTest/kotlin/KotlinFlowToJdkStreamTest.kt
> +            delay(1000) // Suspended
`yield()` 就可以 suspend 了，不过需要保证当前 context 里有 Dispatcher

2022-10-31 13:09 UTC, merged