[console] Update console logging system
mamoe/mirai pull request #2341
Opened 2022-11-10 15:29 UTC by Karlatemp

# 主修改

- [X] 优化 MiraiLogger (in console) 性能
- [X] SLF4J 支持

# 配置文件修改

> 修改均为默认配置, 先前已经生成的配置不会进行修改

### `Logger.yml`

```diff
 # 默认日志输出等级
 # 可选值: ALL, VERBOSE, DEBUG, INFO, WARNING, ERROR, NONE
 defaultPriority: INFO
 # 特定日志记录器输出等级
 loggers: 
   example.logger: NONE
   console.debug: NONE
   Bot: ALL
+  org.eclipse.aether.internal: INFO
+  org.apache.http.wire: INFO

+# 是否启动外部日志框架桥接
+binding: 
+  slf4j: true
```

# ABI Changes

> 注: 实际上 console 并没有直接的 abi changes

依赖更新: `org.slf4j:slf4j-api:1.7.32` -> `2.0.3`

此依赖的更新只会影响 `slf4j-api` 的对接, 并不会影响 `slf4j-api` 的单纯使用

> 即不会对插件有任何影响, 只会对部分对 console 进行高度自定义的会有少许影响

2022-11-19 19:02 UTC, Him188 commented on mirai-console/backend/mirai-console/src/internal/logging/externalbind/slf4j/MiraiConsoleSLF4JService.kt
> +            // region relay events
replay？

2022-11-19 19:02 UTC, Him188 commented on mirai-console/backend/mirai-console/test/logging/TestALC.kt
> +internal class TestALC {
AbstractLoggerControllerTest

2022-11-19 19:02 UTC, Him188 commented on mirai-core-all/build.gradle.kts
> +    api(`slf4j-api`) // It is required for mirai-console to avoid classpath conflict
能 implementation 么

2022-11-19 22:48 UTC, Karlatemp commented on mirai-core-all/build.gradle.kts
> +    api(`slf4j-api`) // It is required for mirai-console to avoid classpath conflict
implementation我不知道gradle会怎么处理所以我保持一致用了 api

2022-11-20 00:52 UTC, Him188 commented on mirai-core-all/build.gradle.kts
> +    api(`slf4j-api`) // It is required for mirai-console to avoid classpath conflict
你是考虑 shadow 么，可以改 implementation

2022-11-20 02:46 UTC, Karlatemp commented on mirai-core-all/build.gradle.kts
> +    api(`slf4j-api`) // It is required for mirai-console to avoid classpath conflict
考虑直接其他项目引用 -all 和 shadow 两个

2022-11-20 12:25 UTC, Him188 commented on mirai-core-all/build.gradle.kts
> +    api(`slf4j-api`) // It is required for mirai-console to avoid classpath conflict
?

2022-11-20 12:43 UTC, Karlatemp commented on mirai-core-all/build.gradle.kts
> +    api(`slf4j-api`) // It is required for mirai-console to avoid classpath conflict
就是别的项目直接使用 `mirai-core-all` 的话不知道 gradle 会怎么处理

2022-11-20 13:14 UTC, Him188 commented on mirai-core-all/build.gradle.kts
> +    api(`slf4j-api`) // It is required for mirai-console to avoid classpath conflict
当做普通项目使用，不会使用 shadow 的

2022-11-20 15:22 UTC, Him188 requested changes

2022-11-20 15:22 UTC, Him188 commented on mirai-core-all/build.gradle.kts
> +    "shadowOnly"(`slf4j-api`) // It is required for mirai-console to avoid classpath conflict
shadow 改了, 所以你这个方法会用不了

2022-11-20 15:26 UTC, Karlatemp commented on mirai-core-all/build.gradle.kts
> +    "shadowOnly"(`slf4j-api`) // It is required for mirai-console to avoid classpath conflict
那我需要等那个pr合并后才能确定最后怎么改

2022-12-03 00:46 UTC, Him188 approved these changes

2022-12-03 00:47 UTC, Him188 commented on mirai-core-all/build.gradle.kts
> +    implementation(`slf4j-api`) // Required by mirai-console
这个是不会 shadow 的, 你需要 shadow 的话得用 `relocateImplementation`

2022-12-03 04:15 UTC, Karlatemp commented on mirai-core-all/build.gradle.kts
> +    implementation(`slf4j-api`) // Required by mirai-console
没关系，只需要 -all.jar shadow了就行

2022-12-17 20:33 UTC, merged