Generate and handle tgtgtKey correctly, fix #2418
mamoe/mirai pull request #2419
Opened 2023-01-11 20:03 UTC by sandtechnology

2023-01-11 21:08 UTC, Him188 requested changes

2023-01-11 21:08 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                writeShort((if (client.wLoginSigInfoInitialized && client.wLoginSigInfo.noPicSig != null) (if (allowSlider) 0x18 else 0x17) + 1 else (if (allowSlider) 0x18 else 0x17)).toShort()) // c
```suggestion
                var count = if (allowSlider) 0x18 else 0x17
                if (client.wLoginSigInfoInitialized && client.wLoginSigInfo.noPicSig != null) {
                    count++
                }
                writeShort(count.toShort()) // count of TLVs, probably ignored by server?
```

2023-01-11 21:08 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                }
看起来会影响 count?

2023-01-11 21:09 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                writeShort((if (client.wLoginSigInfoInitialized && client.wLoginSigInfo.noPicSig != null) (if (allowSlider) 0x18 else 0x17) + 1 else (if (allowSlider) 0x18 else 0x17)).toShort()) // c
if 太复杂了

2023-01-11 22:07 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                writeShort((if (client.wLoginSigInfoInitialized && client.wLoginSigInfo.noPicSig != null) (if (allowSlider) 0x18 else 0x17) + 1 else (if (allowSlider) 0x18 else 0x17)).toShort()) // c
这个 if 我的建议是先写个占位符，然后最后覆盖掉这个值

2023-01-11 23:47 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                writeShort((if (client.wLoginSigInfoInitialized && client.wLoginSigInfo.noPicSig != null) (if (allowSlider) 0x18 else 0x17) + 1 else (if (allowSlider) 0x18 else 0x17)).toShort()) // c
那当然, 最好的方法是写个 `writeTlvs {}`, 在 DSL scope 中 count. 但是基于现有代码的话, 就不是很好改了.

把数量放在最开始计算, 多加一点人脑思维也能应付这小几十行代码了, 可以不需要做重构

2023-01-11 23:49 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                writeShort((if (client.wLoginSigInfoInitialized && client.wLoginSigInfo.noPicSig != null) (if (allowSlider) 0x18 else 0x17) + 1 else (if (allowSlider) 0x18 else 0x17)).toShort()) // c
不过如果 @sandtechnology 想重构玩也是可以的

2023-01-12 03:56 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                }
上面就已经按这个情况预先算好了（

2023-01-12 04:00 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                writeShort((if (client.wLoginSigInfoInitialized && client.wLoginSigInfo.noPicSig != null) (if (allowSlider) 0x18 else 0x17) + 1 else (if (allowSlider) 0x18 else 0x17)).toShort()) // c
目前tlv只有几个class用到 应该还没有重构的必要 我加个注释吧然后放个临时的变量吧

2023-01-12 10:42 UTC, Karlatemp commented
我还是认为先写入占位符事比较好的方式

2023-01-12 10:46 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
加个 legacy fallback? 确定全部protocol可用吗

2023-01-12 10:46 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                    }
创建个方法比较好？ @Him188

2023-01-12 10:49 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
因为原先的方式就是错的 所以说这里并没有fallback的必要 目前只测试了安卓协议 让我试试其他的吧

2023-01-12 11:14 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
Pad：code=45, title=禁止登录, message=您好，您当前使用的版本过低，前往QQ官网im.qq.com下载新版QQ。（无法测试）
Watch：成功，存在对应字段，且数据正常
IPAD: 成功，存在对应字段，且数据正常
MACOS：成功，存在对应字段，且数据正常

2023-01-12 11:23 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
在使用来自MiraiGo的更新字段后 pad测试也是正常的

2023-01-12 11:25 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
因此 确定全部协议可用（除了pad需要人进行更新外

2023-01-12 12:05 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                    }
都行，在还没有出现复用情况时不必要优化

2023-01-12 12:26 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                    }
> 都行，在还没有出现复用情况时不必要优化

快速登录里面也用到了 我加一下吧

2023-01-12 23:11 UTC, Him188 approved these changes

2023-01-13 23:36 UTC, merged