QRCode login support
mamoe/mirai pull request #2502
Opened 2023-02-15 05:30 UTC by StageGuard

- [x] protocol
- [ ] api
- [ ] test
- [ ] document

2023-02-15 06:24 UTC, StageGuard commented
![image](https://user-images.githubusercontent.com/45701251/218948706-c49aba69-7658-43b6-89af-179acfeff160.png)
已经可以登录，但是还有其他问题：
* Logger name 依旧显示为 `Bot 0`。
* `wtlogin.trans_emp` 协议不稳定，经常无法解析。

2023-02-17 16:00 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
> +                        when(protocol) {
格式化

2023-02-17 16:00 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
> +                        })
第二次判断可以直接 `error("assertion")`

2023-02-17 16:00 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
> +                        tlv.getOrFail(0x17) { "missing tlv 0x17 while parsing wtlogin.trans_emp with command 0x31." }
```
val data = tlv.getOrFail(0x17) {
  "missing tlv 0x17 while parsing wtlogin.trans_emp with command 0x31."
}
```

2023-02-17 16:00 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
> +                            tlv.getOrFail(0x1e) { "missing tlv 0x1e while parsing wtlogin.trans_emp with command 0x12." }
same

2023-02-19 05:40 UTC, sandtechnology requested changes

2023-02-19 05:40 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/components/PacketCodec.kt
> +            if (flag3 != 0) {
这里其实可以直接判断flag3Exception是不是null 然后下面kt就不需要!!了

2023-02-19 05:40 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/components/PacketCodec.kt
> +                    PacketLogger.warning(
我还是觉得这里没必要把异常写进去 抛出路径就这里（
附带抛出的位置就好？比如前面加个[PacketCodec.decodeRaw]

2023-02-19 05:40 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
> +        fun QueryQRCodeStatus(
应该要首字母小写？

2023-02-19 05:40 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
> +        fun FetchQRCode(
应该要首字母小写？

2023-02-19 05:40 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/components/QRCodeLoginProcessor.kt
> +                error("TransEmpResponse is not QRCodeStatus or QRCodeConfirmed.")
这里应该可以给出实际的类型，以帮助debug？

2023-02-19 05:40 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/components/PacketCodec.kt
> +    override fun decodeRaw(client: QQAndroidBot, ssoSession: SsoSession, input: ByteReadPacket): RawIncomingPacket = input.run {
这样修改后 ssoSession 是 unused var，应该撤回修改？

2023-02-19 06:25 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/network/components/PacketCodec.kt
> +    override fun decodeRaw(client: QQAndroidBot, ssoSession: SsoSession, input: ByteReadPacket): RawIncomingPacket = input.run {
哪还有别的判断 command 的方案吗

2023-02-19 06:55 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/components/PacketCodec.kt
> +    override fun decodeRaw(client: QQAndroidBot, ssoSession: SsoSession, input: ByteReadPacket): RawIncomingPacket = input.run {
> 哪还有别的判断 command 的方案吗

没有啊 我说你这可以直接把ssoSession 删了 因为这里你是直接读command name判断的（

2023-02-20 00:08 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
> +        fun QueryQRCodeStatus(
我觉得这个比较像 builder，为了和 operator fun invoke 的包保持一致的风格我就大写了

2023-02-20 08:39 UTC, msojocs commented
无法自行实现QR处理方案

![image](https://user-images.githubusercontent.com/20937135/220054640-6f57deb0-6a3f-45cb-906a-1e52127f2402.png)

2023-02-20 14:38 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt
> +        fun QueryQRCodeStatus(
这种满足特殊情况 以 function 代替 constructor, 是可行的

2023-02-24 01:41 UTC, zhaodice commented
~~看了一下代码，好像没有很好的API获取 二维码图片路径~~ , onFetchQRCode 似乎就可以自定义，看错了

2023-03-02 12:33 UTC, Him188 requested changes

2023-03-02 12:33 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +}
为什么要有这些东西?

2023-03-02 12:33 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +}
为什么不叫更恰当的 session 呢

2023-03-02 12:33 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +public interface BotAuthorizationResult
其他 API 都叫 `Auth`, 但这个叫 `Authorization`

2023-03-02 12:34 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +}
或者它不应该出现在 public api

2023-03-02 13:00 UTC, Him188 requested changes

2023-03-02 13:00 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/handler/selector/SelectorRequireReconnectException.kt
> +internal expect class SelectorRequireReconnectException() : NetworkException
我觉得这个应该继承 LoginFailedException, 因为它不能用于其他用途

2023-03-02 13:00 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/handler/selector/SelectorRequireReconnectException.kt
> +internal expect class SelectorRequireReconnectException() : NetworkException
A special exception that instructs selector to restart network connection

2023-03-02 13:00 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/BotAccount.kt
> +internal class BotAccount(
话说这个会不会导致内存泄露?

2023-03-02 13:00 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/LoginSolver.kt
> +
它为什么还在这里呢, 按设计应该要挪到 authorization?

2023-03-02 13:00 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/network/LoginFailedException.kt
> +    public val expected: Long,
@since 2.15

2023-03-02 13:00 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/network/LoginFailedException.kt
> +    public val expected: Long,
@since 2.15

2023-03-02 13:00 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/network/LoginFailedException.kt
> +    public val expected: Long,
`@since 2.15`

2023-03-02 13:00 UTC, Him188 commented on mirai-core/src/commonTest/kotlin/network/framework/AbstractRealNetworkHandlerTest.kt
> +
TODO?

2023-03-02 14:33 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/BotAccount.kt
> +internal class BotAccount(
不会吧, 也不应该有别的地方会引用 account 导致无法释放

2023-03-03 20:28 UTC, Him188 commented
提醒一下，
不要 force push

2023-03-09 12:25 UTC, cssxsh commented on mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt
> +                supportsQRLogin = false,
IPAD 也是可以扫码的吧，隔壁 MiraiGo 默认的协议就是 IPAD

2023-03-09 12:34 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt
> +                supportsQRLogin = false,
这个没注意，之后测试一下

2023-03-11 20:52 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +}
看起来是可以合起来成一个类的

2023-03-11 20:52 UTC, Him188 commented on mirai-core-api/src/jvmMain/kotlin/utils/LoginSolver.jvm.kt
> +                        "[QRCodeLogin] Failed to export qrcode image. Please try to scan the char-image after disabling custom terminal style indeed.",
```suggestion
                        "[QRCodeLogin] Failed to export qrcode image. Please try to scan the char-image after disabling custom terminal style.",
```

2023-03-11 20:52 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/BotAccount.kt
> +internal class BotAccount(
```
    var accountSecretsKeyBuffer: SecretsProtection.EscapedByteBuffer? = null
```

在 native alloc 的 buffer 也能 GC?

2023-03-11 20:55 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/components/PacketCodec.kt
> +                    PacketLogger.warning(
带个 trace 是好的

2023-03-11 20:59 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +}
看起来不行

2023-03-11 21:05 UTC, Him188 requested changes

2023-03-11 21:05 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
> +    override suspend fun login(handler: NetworkHandler) {
太复杂了, 我争取明天早上或者中午找个时间整理下

2023-03-11 23:17 UTC, qfys521 commented on mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt
> +                supportsQRLogin = false,
pad是可以扫码登录。

2023-03-12 02:18 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/BotAccount.kt
> +internal class BotAccount(
为什么不

2023-03-12 11:30 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/BotAccount.kt
> +internal class BotAccount(
native 的不是不参与 GC 么，不太清楚

2023-03-13 04:34 UTC, Karlatemp reviewed
1. 给productor也添加相关测试
2. productor 感觉更像是通用工具类，换个包更好

2023-03-13 04:34 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/auth/Latch.kt
> +    }
携程用非携程锁？

2023-03-13 10:34 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/auth/Latch.kt
> +    }
确实，这个只是临时版本，昨天没时间写了

2023-03-13 10:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/auth/Latch.kt
> +    }
如果你觉得没问题的话我就去优化和覆盖 test

2023-03-13 10:36 UTC, Him188 commented
TODO:
- [ ] OnDemandProducer test
- [ ] 登录的 test 如果还有需要
- [ ] 检查 Latch 实现

2023-03-18 13:52 UTC, merged