Add fallback solution for Services
mamoe/mirai pull request #2511
Opened 2023-02-16 20:35 UTC by Nambers

move `Services` from `Native` to `CommonMain` in order to add a additional `fallback` solution to find Services, and enable an easy way to override implementations.

~todo: when "mirai.service.loader" != "jdk" / "fallback"~

2023-02-19 11:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Services.kt
> +}
这里应当抛出 IllegalStateException

kotlinx-coroutines 实现:
```kotlin
internal actual val DEBUG = systemProp(DEBUG_PROPERTY_NAME).let { value ->
    when (value) {
        DEBUG_PROPERTY_VALUE_AUTO, null -> ASSERTIONS_ENABLED
        DEBUG_PROPERTY_VALUE_ON, "" -> true
        DEBUG_PROPERTY_VALUE_OFF -> false
        else -> error("System property '$DEBUG_PROPERTY_NAME' has unrecognized value '$value'")
    }
}
```

2023-02-19 11:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Services.kt
> +    }
这个代码现在有点太复杂了, 能重构一下吗?

2023-02-19 11:57 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Services.kt
> +}
这个没有必要实现为两个 lambda inline, 用 kotlinx-coroutines 那样的一个属性, 然后在使用处 `when` 是会让代码更简单的

2023-02-21 00:16 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Services.kt
> +    fun getFALLBACKService(clazz: KClass<out T>) =
```suggestion
    fun getFallbackService(clazz: KClass<out T>) =
```

2023-02-21 00:16 UTC, Him188 commented on mirai-core-utils/src/jvmBaseMain/kotlin/Services.kt
> +private fun <T : Any> getJDKServices(clazz: KClass<out T>): ServiceLoader<out T> = ServiceLoader.load(clazz.java)
```suggestion
private fun <T : Any> getJdkServices(clazz: KClass<out T>): ServiceLoader<out T> = ServiceLoader.load(clazz.java)
```
Kotlin 命名习惯是两字母缩写就用大写；三字母及以上首字母大写，其他字符小写。
IDEA 实现的一些 intention 是支持这个习惯的，例如把 `fun getID()` 转换为 `val`，IDE 会给出 `val id` 
`fun getJDK()` 则会变成 `val jdK` （我以前遇到过这种问题，但现在写的示例可能不准确）

2023-02-21 14:29 UTC, Karlatemp commented
浅浅提一下,,, 这个好像,, 没把 native 的 service 注册移动到 common 吧?

2023-02-21 14:34 UTC, Karlatemp commented on mirai-core-utils/src/jvmBaseMain/kotlin/Services.kt
> +private fun <T : Any> getJdkServices(clazz: KClass<out T>): ServiceLoader<out T> = ServiceLoader.load(clazz.java)
// Suggest:

`loadServiceByJdk`

2023-02-21 14:34 UTC, Karlatemp commented on mirai-core-utils/src/jvmBaseMain/kotlin/Services.kt
> +    fun getFallbackService(clazz: KClass<out T>) =
suggest:

loadFallbackService

2023-02-21 14:34 UTC, Karlatemp commented on mirai-core-utils/src/jvmBaseMain/kotlin/Services.kt
>          ?: throw NoSuchElementException("Could not find an implementation for service class ${clazz.qualifiedName}").apply {
此部分逻辑和 `loadServices(): Sequence` 的效果不一致

2023-02-22 01:19 UTC, Nambers commented on mirai-core-utils/src/jvmBaseMain/kotlin/Services.kt
>          ?: throw NoSuchElementException("Could not find an implementation for service class ${clazz.qualifiedName}").apply {
当 loader 是 fallback 的时候, 是否需要获取到 jdk 部分的 services?

2023-02-24 14:37 UTC, Karlatemp reviewed
还有个疑问就是

jvm 的平台 Services 是空的吧

2023-02-24 14:41 UTC, Nambers commented
> 还有个疑问就是
> 
> 
> 
> jvm 的平台 Services 是空的吧

目前还没注册 Servicrs 进去，之前188是说用这一套替代jdk自己的serviceLoader，以及可以用一些方式覆盖实现

2023-02-24 21:48 UTC, Him188 commented
e
我的意思是也要给JVM注册，作为fallback，同时解决一些其他问题

2023-03-01 18:09 UTC, Him188 approved these changes

2023-03-10 01:45 UTC, Him188 requested changes

2023-03-10 01:45 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Services.kt
> +    internal fun implementations1(baseClass: String) = lock.withLock { registered[baseClass]?.toList().orEmpty() }
不要有奇怪的命名

2023-03-10 11:42 UTC, Him188 requested changes

2023-03-10 11:42 UTC, Him188 commented on mirai-core-utils/src/commonMain/kotlin/Services.kt
> +    internal fun implementations1(baseClass: String) = lock.withLock { registered[baseClass]?.toList().orEmpty() }
我说的其实是 implementations1

2023-03-11 10:12 UTC, merged