[core] Fix message source logic
mamoe/mirai pull request #2513
Opened 2023-02-17 15:31 UTC by Karlatemp

- Fix quote replying
- Fix MessageSource.time

2023-02-19 10:53 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/message/source/outgoingSourceImpl.kt
> +    val elements = MessageProtocolFacade.encode(originalMessage, subject, withGeneralFlags = false)
这里改成false没关系吗（

2023-02-19 11:16 UTC, cssxsh commented
这个 #2122 有可能顺便修了吗

2023-02-19 14:32 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/source/outgoingSourceImpl.kt
> +    val elements = MessageProtocolFacade.encode(originalMessage, subject, withGeneralFlags = false)
没关系

2023-02-19 14:47 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/message/source/outgoingSourceImpl.kt
> +    val elements = MessageProtocolFacade.encode(originalMessage, subject, withGeneralFlags = false)
> 没关系

但是不是会漏闪照之类的flag吗（
我跟下去看起来是会影响的（如果进行复读和重发
改这个感觉有点意义不明

2023-02-19 14:49 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/source/outgoingSourceImpl.kt
> +    val elements = MessageProtocolFacade.encode(originalMessage, subject, withGeneralFlags = false)
不会，客户端发送的回复的source也没有这些东西

2023-03-18 20:26 UTC, Him188 commented
为什么 snapshots failed 了呢

2023-03-18 20:27 UTC, Him188 commented
懂了,  branch 名字包含 `/`

2023-03-19 14:54 UTC, Him188 requested changes

2023-03-19 14:54 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/protocol/impl/QuoteReplyProtocol.kt
> +                    yield(sourceCommon.fromId != 80000000L)
```suggestion
                    yield(sourceCommon.fromId != 80000000L) // #2501
```

2023-03-19 14:54 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/protocol/impl/QuoteReplyProtocol.kt
> +                    yield(sourceCommon.fromId != 80000000L)
弄一个函数写这个, 不要用 sequence

2023-03-19 14:54 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/roaming/RoamingMessagesImplGroup.kt
> +                        .sortedByDescending { it.msgHead.msgSeq } // Ensure caller receiver newer messages first
```suggestion
                        .sortedByDescending { it.msgHead.msgSeq } // Ensure caller receives newer messages first
```

2023-03-19 14:54 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/protocol/impl/GeneralMessageSenderProtocol.kt
>          ): Boolean {
看起来不需要传 index 参数, 应该直接在 lambda 里使用

2023-03-19 14:54 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/protocol/impl/GeneralMessageSenderProtocol.kt
> +                ) return@sendAllPackets false
```suggestion
                if (!sendSinglePacket(
                        bot, packet, step, contact,
                    ) { packetResponseConsumer(index, it) }
                ) return@sendAllPackets false
```

2023-03-19 14:54 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/protocol/impl/GeneralMessageSenderProtocol.kt
> +                (sourceAwait as OutgoingMessageSourceInternal).time = finalTime
```suggestion
            // Patch time to be actual server time
            var finalTime = bot.clock.server.currentTimeSeconds().toInt()
            val sendPacketOk = sendAllPackets(bot, step, contact, packets) { idx, rsp ->
                if (rsp is MessageSvcPbSendMsg.Response.SUCCESS) {
                    finalTime = rsp.sendTime
                }
            }
            if (sendPacketOk) {
                val sourceAwait = source?.await() ?: error("Internal error: source is not initialized")
                (sourceAwait as OutgoingMessageSourceInternal).time = finalTime
```

2023-03-21 14:49 UTC, Him188 commented
dev 修了发 snapshot

2023-03-21 15:03 UTC, Him188 commented
> 这个 #2122 有可能顺便修了吗

@Karlatemp

2023-03-21 15:04 UTC, Karlatemp commented
> > 这个 #2122 有可能顺便修了吗

看这个 issue 的 comments

2023-03-29 14:20 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/MessageSource.kt
> +public fun getKindLegacy(source: OnlineMessageSource): MessageSourceKind = source.kind
这会导致 `import` 的变红, 但也没办法了

2023-03-29 14:23 UTC, Him188 approved these changes

2023-03-29 14:31 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/source/incomingSourceImpl.kt
>          group
这地方好像改错了，迟点再看一下

2023-03-29 14:32 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/source/incomingSourceImpl.kt
>          group
哦没有错，看成原来找两次 group 了

2023-03-29 14:43 UTC, Him188 commented
你可以合

2023-03-29 15:28 UTC, merged