Add encryption SPI & T544 support
mamoe/mirai pull request #2566
Opened 2023-03-10 15:41 UTC by sandtechnology

#2562 初版实现(
参考着现有的 SPI 写了一下
T544部分参考自MiraiGo

2023-03-10 15:56 UTC, zhaodice commented
这个相当于假设了只有doTLVEncrypt（TLV加密），以后可能会有更多的算法，比如目前登录的包就有两种需要解决的算法
一种是算sign的，一种是算energy的

2023-03-10 16:23 UTC, Karlatemp requested changes

2023-03-10 16:23 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +public interface EncryptWorkerService : BaseService {
should not be api, move to core

2023-03-11 01:00 UTC, GreyWolf007 commented
tlv544在登陆那块的,明显的TX自己写了BUG, 8字节的账号只取了前4字节,导致后面多出来4字节的0,这个TX在登陆时候不验证的,后续版本应该会修复

2023-03-11 01:02 UTC, GreyWolf007 commented
tlv544在登陆那块的,明显的TX自己写了BUG, 8字节的账号只取了前4字节,导致后面多出来4字节的0,这个TX在登陆时候不验证的,后续版本应该会修复

2023-03-11 01:18 UTC, zhaodice commented
> tlv544在登陆那块的,明显的TX自己写了BUG, 8字节的账号只取了前4字节,导致后面多出来4字节的0,这个TX在登陆时候不验证的,后续版本应该会修复

https://github.com/Mrs4s/MiraiGo/commit/9760f01de14c1c0cb7956ec979273f60be2415d2

要验证的，就是加了这个0字节才能登陆，不加就是版本过低

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin15.kt
> +                runBlocking {
no runBlocking

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin10.kt
> +                    runBlocking {
no runBlocking

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin2.kt
> +                    runBlocking {
no runBlocking

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin2.kt
> +                    runBlocking {
no runBocking

顺便好像有很多重复 (useAndroid)?

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin7.kt
> +                    runBlocking {
no runBlocking

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/login/wtlogin/WtLogin9.kt
> +                    runBlocking {
no runBlocking

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +@file:Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")
这个要放在注释下面, package 上面

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +    @Throws(IllegalStateException::class, CancellationException::class)
不需要标注这个, 因为它们不是受检异常, 而且这也不需要提供 Java 支持

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +        @Throws(IllegalStateException::class, CancellationException::class)
不许要标注

2023-03-29 14:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +
不要用这种 delegate 方式, 弄一个变量 val instance 比较好, 实际上把它弄成 Component 放 bot 里更好, 适合 test (虽然这可能没有 test)

2023-04-15 06:41 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +
这个的话在SPIServiceLoader里面就是instance的方式 所以这里这么写其实没问题

2023-04-15 10:30 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +
我的意思是不要让 companion object 实现 `EncryptWorkerService`，直接暴露一个 instance 属性就行

2023-04-15 10:31 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +
因为现在这样会增加维护负担

2023-04-15 11:20 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +
但是KT说不能这么搞（
![image](https://user-images.githubusercontent.com/20417547/232210802-578138f3-9397-4fcf-9a58-a861528a4842.png)

2023-04-15 11:34 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +
mirai 用的新 native GC, 可以忽略

2023-04-15 11:38 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptWorkerService.kt
> +
其实要解决它的话, 你可以把它变成 aotmic 的

```kotlin
private var instance: EncryptWorkder by atomic(null)
```

2023-04-15 14:43 UTC, sandtechnology commented
Rebase了一下 等个CI Pass（

2023-04-16 14:43 UTC, Karlatemp approved these changes
lgtm

2023-04-16 14:43 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/Tlv.kt
> +        }
`buildPacket{}.use{it.readBytes()}` better

2023-04-16 14:43 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/Tlv.kt
> +internal fun TlvMapWriter.t544ForToken( // 1348
或许可以在没有结果的时候跳过这个tlv?

2023-04-16 14:44 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/Tlv.kt
> +internal fun TlvMapWriter.t544ForToken( // 1348
当强制验证的时候有没有都没区别（

2023-04-16 14:50 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/Tlv.kt
> +internal fun TlvMapWriter.t544ForToken( // 1348
这里为了方便代码维护就没写跳过 不过有没有这个tlv可能是判断风控的一种途径 我觉得还是带上好了（

2023-05-27 15:28 UTC, Him188 approved these changes

2023-05-27 15:39 UTC, sandtechnology commented
根据最新的策略 可能需要加入新接口 doSignCalc，是在此PR加入还是？

2023-05-27 15:48 UTC, Karlatemp reviewed
需要传递 bot 对象本身以获得其他信息

2023-05-27 15:48 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/spi/EncryptService.kt
> +         */
多余的

2023-05-27 15:48 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/spi/EncryptService.kt
> +     */
多余的

2023-05-27 15:58 UTC, sandtechnology commented
> 需要传递 bot 对象本身以获得其他信息

这是不应该的 接口不应该能访问bot对象 只提供必须信息即可

2023-05-27 16:22 UTC, Karlatemp commented
> 这是不应该的 接口不应该能访问bot对象 只提供必须信息即可

selected protocol

2023-05-27 16:46 UTC, sandtechnology commented
> > 这是不应该的 接口不应该能访问bot对象 只提供必须信息即可
> 
> selected protocol



> > 这是不应该的 接口不应该能访问bot对象 只提供必须信息即可
> 
> selected protocol

那context提供进去就好了吧（

2023-05-27 17:06 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptService.kt
> +     */
这里完全不多余，不然没人知道有哪些keys

2023-05-27 17:06 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptService.kt
> +         */
我觉得这并不多余

2023-05-28 05:29 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/spi/EncryptService.kt
> +     */
读者不是弱智

2023-05-28 05:30 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/spi/EncryptService.kt
> +         */
多余的

2023-05-28 11:12 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptService.kt
> +     */
注释更详细是没有坏处的

2023-05-28 11:13 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/spi/EncryptService.kt
> +         */
这绝对不是多余的，如果删掉这些，使用的人甚至没法通过IDE库源码看，必须clone mirai进行搜索才能知道可能得值有哪些

2023-06-03 12:48 UTC, Him188 commented
> 根据最新的策略 可能需要加入新接口 doSignCalc，是在此PR加入还是？

新的吧

2023-06-03 23:01 UTC, merged