fix: ProducerReady
mamoe/mirai pull request #2633
Opened 2023-04-17 13:54 UTC by cssxsh

按照状态图的设计，`Producer` 线程的启动时间点应为 ProducerReady -> Producing
故将原本 `init` 的行为改为主动调用

close #2623

2023-04-17 17:10 UTC, Him188 requested changes

2023-04-17 17:10 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/auth/CoroutineOnDemandValueScope.kt
> +        val ready = coroutineScope.launch(start = CoroutineStart.LAZY) {
```suggestion
        private val ready = coroutineScope.launch(start = CoroutineStart.LAZY) {
```

2023-04-17 17:10 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/auth/CoroutineOnDemandValueScope.kt
> +            (state.producer as Producer).ready.start()
这句话是线程不安全的, 之后我想想改怎么改

2023-04-21 13:56 UTC, lanybass commented
想好没。。。

2023-04-21 14:15 UTC, Him188 commented
最近太忙

2023-05-04 15:36 UTC, closed without merging