Update docs
mamoe/mirai pull request #2639
Opened 2023-04-19 15:15 UTC by cssxsh

还没写完

2023-04-23 13:33 UTC, Him188 commented
写完了 request  review 一下

2023-04-23 16:55 UTC, Karlatemp commented
/docs/.conf/nav.js

2023-04-26 04:49 UTC, cssxsh commented
> 写完了 request review 一下

差不多了

2023-04-26 14:38 UTC, Karlatemp commented on docs/Bots.md
> +    fun newBot(qq: Long, authorization: BotAuthorization, configuration: BotConfiguration)
// 在 2.15.0 中加入

2023-04-26 14:38 UTC, Karlatemp commented on docs/Bots.md
> +}
error & // 在 2.15.0 中加入

2023-04-26 14:38 UTC, Karlatemp commented on docs/Question.md
似乎没有索引引导查看 Questions

2023-04-29 15:01 UTC, Karlatemp commented on docs/Bots.md
> +});
添加 `BotFactory.INSTANCE.newBot(qq, password, configuration ->{})` 避免 `// 在 2.15.0 加入` 被认为是 lambda 在 2.15.0 加入

2023-04-29 15:01 UTC, Karlatemp commented on docs/ConsoleTerminal.md
> +
通过引用 `> xxx` 是否会更好?

```
重要：关闭 Mirai Console 需要通过 `stop` 命令关闭。
直接关闭窗口会导致数据损坏、数据丢失、系统崩溃等错误。
```

2023-04-29 15:01 UTC, Karlatemp commented on docs/Questions.md
> +MCL查询更新信息失败，你可以尝试编辑 `config.json` 更换 [`mirai_repo`](https://github.com/project-mirai/mirai-repo-mirror#%E4%BB%93%E5%BA%93%E9%95%9C%E5%83%8F)
中文与英文之间需要有空格

使用全名 mirai-console-loader 更好

2023-04-29 15:01 UTC, Karlatemp commented on docs/Questions.md
> +   如果插件的指令是对接的 `Mirai Console` 的指令接口，那它就需要 `chat-command`
不要直接引用下载地址, 

`https://github.com/project-mirai/chat-command/releases/latest`

2023-04-29 15:01 UTC, Karlatemp commented on docs/Questions.md
> +   默认情况下所有用户都是没有权限的，聊天框下无法使用指令
Addition / PS: 如果使用了 LuckPerms-Mirai, 可通过在控制台执行 `/lp verbose on` 查看权限检测情况

2023-04-29 15:01 UTC, Karlatemp commented on docs/Questions.md
> +用指令 `/status`
Mirai Console

2023-04-29 15:01 UTC, Karlatemp commented on docs/Questions.md
> +IDEA 太旧了，没法解析新版 kotlin, 最好升级到最新版
IDEA 版本过于老旧，无法分析新版本的 kotlin 依赖，请尝试升级 IDEA 后重试

2023-05-01 05:41 UTC, Karlatemp commented
可以把 https://github.com/mamoe/mirai/issues/2402#issuecomment-1368473584 的内容也加入到适当的位置

2023-05-01 08:04 UTC, Him188 commented
KotlinPlatformType 有 class，别用 String，看 mirai 现在写的（configureJvmTargetsHierarchical()）

2023-05-04 15:53 UTC, Him188 requested changes
主要是格式问题

2023-05-04 15:53 UTC, Him188 commented on docs/ConsoleTerminal.md
> +> 直接关闭窗口会导致数据损坏、数据丢失、系统崩溃等错误。
```suggestion
**重要**：关闭 Mirai Console 需要通过 `stop` 命令关闭。
直接关闭窗口会导致数据损坏、数据丢失、系统崩溃等错误。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Bots.md
> +});
说明一下各种构造方式的区别, 比如 "使用密码登录", "使用二维码登录"

2023-05-04 15:53 UTC, Him188 commented on docs/Preparations.md
> +- 桌面 JVM：最低 Java 8，但推荐 Java 17（要使用一键启动器，需要 11+）
```suggestion
- 桌面 JVM：最低 Java 8，但推荐 Java 17（要使用一键启动器，需要 11 及以上）
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +你可能需要安装插件 https://github.com/project-mirai/mirai-api-http
```suggestion
可能需要安装插件 <https://github.com/project-mirai/mirai-api-http>。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +你可能需要 安装插件/引入依赖 https://github.com/project-mirai/mirai-silk-converter
```suggestion
你可能需要安装插件或引入依赖 <https://github.com/project-mirai/mirai-silk-converter>。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +这些是服务器返回的信息，它表示你的 `BOT` 账号被登录风控了
```suggestion
这些是服务器返回的信息，它表示你的账号被登录风控了  
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +另外，密码登录中是否出现`滑块验证`或`短信验证`都是不可控的，这取决于腾讯的服务器要求你完成什么验证，没有办法自由选择。
```suggestion
密码登录中是否出现滑块验证或短信验证都是不可控的，这取决于腾讯的服务器要求你完成什么验证，没有办法自由选择。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +风控没有100%稳定的解决方法，你可以关注 [论坛公告帖 - 无法登录的临时处理方案](https://mirai.mamoe.net/topic/223)
```suggestion
风控没有 100% 稳定的解决方法，你可以关注 [论坛公告帖 - 无法登录的临时处理方案](https://mirai.mamoe.net/topic/223)。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +   如果插件的指令是对接的 `Mirai Console` 的指令接口，那它就需要 `chat-command`
```suggestion
   如果插件的指令是对接的 Mirai Console 的指令接口，那它就需要 `chat-command`
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +   PS: 如果使用了 `LuckPerms-Mirai`, 可通过在控制台执行 /lp verbose on 查看权限检测情况
```suggestion
   备注：如果使用了 LuckPerms-Mirai，可通过在控制台执行 /lp verbose on 查看权限检测情况
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +可以启动 `Mirai Console` 的情况下:
```suggestion
可以启动 Mirai Console 的情况下:  
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +`Mirai Console` 的组件在 `libs` 文件夹下, 文件名包含 `版本信息`
```suggestion
Mirai Console 的组件在 `libs` 文件夹下, 文件名包含 `版本信息`  。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +`Linux/MacOS` 的启动脚本是 `mcl` (没有后缀的那个文件)
```suggestion
编辑启动脚本 `mcl.cmd`，在 `-jar` 前面加上 `-D...`，例如 `-Dmirai.no-desktop=true -jar mcl...`。

Linux 和 macOS 的启动脚本是 `mcl` (没有后缀的那个文件)。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +IDEA 版本过于老旧，无法分析新版本的 kotlin 依赖，请尝试升级 IDEA 后重试
```suggestion
IDEA 版本过于老旧，无法分析新版本的 Kotlin 依赖，请尝试升级 IDEA 后重试。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +
```suggestion
`SignEvent` 或者 `NudgeEvent`：

总的来说 `MACOS` 和 `ANDROID_WATCH` 相对其他协议会缺少一些事件的接收。
对于这些协议来说是不会收到的，因为这在他们对应官方客户端版本里本来就没有这些功能。

```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +另外如果消息是 `转发消息` 或 `卡片消息` 等特殊消息, 也有可能因为风控无法接收和发出
```suggestion
`GroupMessageEvent`：

群事件收不到可能是因为你将群设置为 `屏蔽群` 或者 `收入了群助手`。
另外如果消息是 `转发消息` 或 `卡片消息` 等特殊消息, 也有可能因为风控无法接收和发出。
```

2023-05-04 15:53 UTC, Him188 commented on docs/UserManual.md
> +你可以先阅读 [常见问题](Questions.md)
```suggestion
请先阅读 [常见问题](Questions.md)  。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +用指令 `/status`
```suggestion
使用指令 `/status`  。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +注意，文件中有一个账号为 `12345` 的示例，请注意确认修改的配置对应的账号，不要修改错了示例
```suggestion
对于手动密码登录，第三个参数就是协议, 例如 `login 12345 114514 MACOS`  

对于自动密码登录，可以使用指令修改，例如 `autoLogin setConfig 12345 protocol MACOS`，
也可以在 `Mirai Console` 关闭的情况下, 编辑 `config/Console/AutoLogin.yml` 文件。

注意，文件中有一个账号为 `12345` 的示例，请注意确认修改的配置对应的账号，不要修改错了示例。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +没有安装 `java`
```suggestion
没有安装 Java。
```

2023-05-04 15:53 UTC, Him188 commented on docs/Questions.md
> +更换 [`mirai_repo`](https://github.com/project-mirai/mirai-repo-mirror#%E4%BB%93%E5%BA%93%E9%95%9C%E5%83%8F)
```suggestion
[MCL](https://github.com/iTXTech/mirai-console-loader) 查询更新信息失败，可以尝试编辑 `config.json`，
更换 [mirai repo](https://github.com/project-mirai/mirai-repo-mirror#%E4%BB%93%E5%BA%93%E9%95%9C%E5%83%8F)。
```

2023-05-05 15:57 UTC, ObcbO commented
> KotlinPlatformType 有 class，别用 String，看 mirai 现在写的（configureJvmTargetsHierarchical()）

大佬能帮忙看下吗（
https://mirai.mamoe.net/topic/2233/gradle%E5%BC%95%E5%85%A5%E4%BE%9D%E8%B5%96%E9%94%99%E8%AF%AF/3

2023-05-06 10:58 UTC, Him188 approved these changes

2023-05-06 11:18 UTC, Karlatemp approved these changes

2023-05-06 12:13 UTC, merged