[core] provide `isFirstLogin` and `getReLoginCause` in `BotAuthInfo`
mamoe/mirai pull request #2664
Opened 2023-05-10 12:41 UTC by StageGuard

2023-05-10 12:57 UTC, Him188 requested changes
missing tests

2023-05-10 12:57 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
> +    private var isFirstLogin: Boolean = true
只需要监听 state 变化, 到 OK 了就是非 first login 了

2023-05-10 12:57 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
> +                    reLoginCause = e
既在 state observe 更新, 又在这里更新, 不是很好, 这句话可能没必要

2023-05-10 12:57 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public val reLoginCause: Throwable?
missing  docs

需要说明 first login 是什么意思 (第一次调用 bot.login 时进行的登录过程)

`reLoginCause` 我觉得不如叫 `lastOfflineCause`?, 需要列举所有可能的异常列表 (preferably 增加测试), 并且不能暴露内部异常例如 NetworkException. 需要保证暴露的异常为在 API 有的 (`NetworkException.unwrapForPublic()`. 

我觉得最好是增加一层处理, 增加 `lastOfflineCause` 与 `lastOfflineCauseException`, 前者为一个 sealed class (enum 也可以考虑, 但感觉不如 sealed class 在这种情况下灵活), 帮 API caller 分析好异常的原因 (例如被 ban, 或者网络错误). 因为用户拿到异常一定是要判断他们的类型, 而这会比较不稳定. 实际上不提供获取 exception 都是可以的.

2023-05-10 12:59 UTC, StageGuard commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public val reLoginCause: Throwable?
ok

2023-05-11 08:18 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
> +                    reLoginCause = e
这个是需要的，

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public class ForceOffline(
`@MiraiInternalApi constructor`

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public class MsfOffline(
`@MiraiInternalApi constructor`

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public class NetworkError(
`@MiraiInternalApi constructor`

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public class FastLoginError(
`@MiraiInternalApi constructor`

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public class Unknown(
`@MiraiInternalApi constructor`

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public open val message: String?
abstract val

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +@NotStableForInheritance
没必要, sealed  class 只能在当前模块内实现

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public val reAuthCause: ReAuthCause?
我还是觉得不如叫 lastFailure, ReAuth 听起来很怪

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> + * @see Unknown
这些没有必要, 因为 sealed class 的 hierarchy 是很明确的. 现在在这里列举了这些, 以后加新东西还得给这里补上

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 是否是首次登录
```suggestion
     * 是否是首次登录。
```

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 导致重新进入认证流程的原因
```suggestion
     * 导致重新进入[认证流程][BotAuthorization.authorize]的原因。
```

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 重新进入认证流程一般是第二次或多次进入认证流程，除了 [FastLoginError]。
我没看懂这句话, "除了" 是除了重新进入流程, 还是除了第二次, 还是除了多次?

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 若设置了 [BotConfiguration.autoReconnectOnForceOffline] 则 mirai 会尝试重新登录。
如果有 `ForceOffline` 这个 cause 传给用户那这个属性肯定就是 `true` 吧
```suggestion
     * 会因此原因进行登录就说明 [BotConfiguration.autoReconnectOnForceOffline] 为 `true`。若该属性为 `false` 时则 mirai 不会自动在被挤下线时重新登录。
```

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 被挤下线后当前的 session 会失效，登录时会重新与服务器认证 Bot 账号信息。
```suggestion
     * 被挤下线后当前的 session 会失效，因此需要重新登录。
```
另外这句话看起来应该跟在 147 行之后.

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 被服务器断开下线后当前的 session 会失效，登录时会重新与服务器认证 Bot 账号信息。
与 `ForceOffline` 类似, 修改一下解释比较好

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 由于其他原因（账号被封禁，被其他客户端手动下线等）导致 Bot 掉线。
```suggestion
     * Bot 因其他原因被服务器断开。这些原因包括账号被封禁、被其他客户端手动下线等。
```

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * Bot 账号首次在 mirai [登录][Bot.login] 成功后，会保存登录 session 信息用于下次登录。
```suggestion
     * Bot 账号首次在 [登录][Bot.login] 成功后，会保存登录 session 信息用于下次登录。
```

2023-05-11 09:28 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 所以 “快速登陆失败后使用 [BotAuthorization] 定义的流程进行登录” 可以被认为是重新与服务器认证。
这段话很难懂, 即使我熟悉内部流程都看不太懂

应减少长句, 更换词语而避免对词语的解释, 更换句子表述方式而减少在句中引用解释其他句子.

2023-05-11 09:42 UTC, StageGuard commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 若设置了 [BotConfiguration.autoReconnectOnForceOffline] 则 mirai 会尝试重新登录。
我觉得这个描述不太好，因为这里是 `authorize` 过程而不是 `login` 过程，只需要说明 ForceOffline 导致的 authorize 原因即可

2023-05-11 09:43 UTC, StageGuard commented
怎么 commit suggestion 会会直接 apply suggestion，我还以为是添加评论

2023-05-11 10:04 UTC, StageGuard commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public val reAuthCause: ReAuthCause?
我认为 lastFailure 比较怪，属性名不能体现出是什么 failure

2023-05-11 10:14 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
> +    var reAuthCause: ReAuthCause?
看了内部实现，这应该叫做 lastOfflineReaon 更好

2023-05-11 10:14 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 被挤下线后当前的 session 会失效，登录时会重新与服务器认证 Bot 账号信息。
Bot 被挤下线

当 Bot 账号在其他客户端使用相同（或相似）协议登录时，Bot 会下线。

当 `BotConf.autoOnForceOffline` 为 `true` 时，mirai 会以此原因尝试重新进入登录流程。

2023-05-11 10:14 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     * 被挤下线后当前的 session 会失效，登录时会重新与服务器认证 Bot 账号信息。
对于 session 的解释似乎是多余的

2023-05-11 10:14 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +    public val reAuthCause: ReAuthCause?
`@NotNull val authReason: AuthReason` 可能更好, 并添加 `InitialLogin` 这可以直接在 firstTimeLogin 使用

2023-05-11 10:14 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/auth/BotAuthorization.kt
> +     */
Bot 首次登录时会尝试使用 `accout.secrets` 登录, 如果无法登录会以此原因进入初次登录流程

2023-05-12 15:52 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
>              }
这地方似乎会把之前的 last error 给覆盖掉

2023-05-12 15:54 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
>              }
只有首次登录(state从来未变成OK)才会有可能是FreshLogin

2023-05-12 15:57 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
>              }
不是初始状态就是FreshLogin吗为什么要再覆盖一次，以及考虑过直接 user bot.login 的情况吗

2023-05-12 15:59 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
>              }
初始状态本来打算是写 delegate not null 的，不知道为啥写成 FreshLogin 了

2023-05-27 14:35 UTC, Him188 approved these changes

2023-05-27 14:36 UTC, Him188 commented
@StageGuard 有地方 build fail 了, 修一下?

2023-05-27 14:39 UTC, StageGuard commented
> @StageGuard 有地方 build fail 了, 修一下?

我的 IDE 会把 kotlin.jvm.* import 删掉，不知道为什么，大概是因为这个

2023-05-27 15:36 UTC, Karlatemp approved these changes

2023-05-27 15:36 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/network/components/SsoProcessor.kt
> -
减少无意义修改

2023-06-18 13:11 UTC, Karlatemp approved these changes

2023-06-20 13:22 UTC, merged