feat: check in load plugin
mamoe/mirai pull request #2703
Opened 2023-06-21 07:53 UTC by cssxsh

close #2136

2023-06-21 08:43 UTC, cssxsh commented on mirai-console/backend/mirai-console/src/plugin/jvm/JvmPluginDescription.kt
> +        }
这段的目的是可以使用 dependsOn 代替 consoleRequirement
然后就可以避免低版本 mirai-console 直接炸掉

不过好像有点多余？

2023-06-23 05:43 UTC, Karlatemp commented
consoleRequirement 方法似乎是多余的, dependsOn 已经能表示 console require 了吧

2023-06-26 13:43 UTC, cssxsh commented
> dependsOn

dependsOn 有多个同名函数，适合拓展 console version 判断的只有 (必须指定 versionRequirement)
```
    @ILoveKuriyamaMiraiForever
    public fun dependsOn(
        @ResolveContext(PLUGIN_ID) pluginId: String,
        @ResolveContext(VERSION_REQUIREMENT) versionRequirement: String,
        isOptional: Boolean = false,
    ): JvmPluginDescriptionBuilder = apply {
        // XXX: 兼容性
        if (pluginId == "net.mamoe.mirai.console" || pluginId == "net.mamoe.mirai") {
            consoleRequirement = versionRequirement
            return@apply
        }
        this.dependencies.add(PluginDependency(pluginId, versionRequirement, isOptional))
    }
```
而且参数名已经敲定了 pluginId

2023-06-26 16:18 UTC, Karlatemp commented
dependsOn 是最符合直觉也可以直接扩展的，没人规定不能存在特殊值，plugin id 可以把 `net.mamoe.mirai-console` 用作特殊值

2023-07-01 07:18 UTC, Him188 requested changes
另外看起来没有支持 YAML 加载

2023-07-01 07:18 UTC, Him188 commented on mirai-console/backend/mirai-console/src/plugin/description/PluginDescription.kt
> +     * 如开发时依赖该插件版本 2.15.0, 则将版本限制设置为 `[2.15.0, 2.16.0)`, 表示大于等于 `2.15.0`, 小于 `2.16.0`.
```suggestion
     * 如开发时依赖该插件版本 2.15.0, 则将版本限制设置为 `[2.15.0, 3.0.0)`, 表示大于等于 `2.15.0`, 小于 `3.0.0`.
```

如果只写 `[2.15.0, 2.16.0)`, 那开发者每个版本都需要更新, 然而一般来说 console 不会有 breaking change 导致插件需要更新. 因此我觉得限制到 3.0 (潜在 breaking change) 以前就可以了, 这样开发者的维护付出会比较小.

2023-07-01 07:18 UTC, Him188 commented on mirai-console/backend/mirai-console/src/plugin/jvm/JvmPluginDescription.kt
> + *
我觉得这个设计不好, 有点 implicit. 可以加一个 `requiresConsole("[2.16.0, 3.0.0)")` 专门用来设置对 console 的限制

2023-07-01 08:07 UTC, Karlatemp commented on mirai-console/backend/mirai-console/src/plugin/jvm/JvmPluginDescription.kt
> + *
我觉得这没什么大问题，也有别的框架把框架本体识别成插件供使用的，比如 mc Forge 就把 forge 本身放入了 modlist 里

`net.mamoe.mirai.console` 对于开发者来说并不是特别难记忆的内容, 不过这里 `net.mamoe.mirai-console` 应该会更好 (same as maven dependency name)

这里 `net.mamoe.mirai-console` 就是 console 的 id, 和平时的 plugin id 行为一致, 这个 id 并没有特殊到完全不属于插件系统中

相反我觉得添加 requireConsole 才是不好的, 这会造成混乱, 包括具体实现上的混乱以及用户侧使用上的混乱, 统一用 dependsOn 可以减少用户的混乱, 同时减少后端实现难度

2023-07-01 12:06 UTC, Him188 commented on mirai-console/backend/mirai-console/src/plugin/jvm/JvmPluginDescription.kt
> + *
那需要去掉新加的那个属性，来兼容序列化

2023-07-25 11:08 UTC, Him188 approved these changes

2023-07-26 08:27 UTC, merged