add: AnimatedStickerProtocol
mamoe/mirai pull request #2722
Opened 2023-07-03 18:37 UTC by cssxsh

2023-07-20 08:50 UTC, Karlatemp commented
```
<html><body>
<!--StartFragment-->

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 348 out of bounds for length 348[m |  
-- | --


	... 45 more[m<!--EndFragment-->
</body>
</html>
```

2023-07-20 12:57 UTC, Karlatemp commented
```
java.lang.IllegalArgumentException: Polymorphic serializer for class net.mamoe.mirai.message.data.SuperFace has property 'type' that conflicts with JSON class discriminator. You can either change class discriminator in JsonConfiguration, rename property with @SerialName annotation or fall back to array polymorphism	
```

2023-07-24 13:56 UTC, Karlatemp reviewed
TestMiraiCode
MessageVisitorTest

2023-08-06 16:51 UTC, Karlatemp approved these changes

2023-08-14 02:53 UTC, Him188 requested changes

2023-08-14 02:53 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/SuperFace.kt
> +public data class SuperFace @MiraiInternalApi constructor(
No data class
https://kotlinlang.org/docs/jvm-api-guidelines-backward-compatibility.html#don-t-use-data-classes-in-an-api

2023-08-14 02:53 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/SuperFace.kt
> +        public fun from(face: Face): SuperFace {
我觉得需要提供一个返回 null 的版本

2023-08-24 02:41 UTC, Him188 approved these changes
标一下 since 就可以了

还有 CI fail 了

2023-09-03 14:21 UTC, merged