feature: add `ShortVideo` message support
mamoe/mirai pull request #2739
Opened 2023-07-17 04:29 UTC by StageGuard

2023-07-29 06:11 UTC, Him188 commented
好了叫我 review 一下

2023-08-03 10:25 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/Contact.kt
> +     * **无论上传是否成功都不会关闭 [resource]. 需要调用方手动关闭资源**
这一句最好去掉，还有 auto closable resource 呢

2023-08-03 10:25 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/contact/Contact.kt
> +     * @param fileName 期望上传的文件名，若为 `null` 则默认为视频资源的 [ExternalResource.md5].
```
文件名，如为 `null` 这根据 [video] 自动生成
```

2023-08-03 10:25 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/code/internal/impl.kt
> +    },
这种状态复杂的不需要 mirai code 实现

2023-08-03 10:25 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> +        }
```suggestion
        public val instance: InternalShortVideoProtocol by lazy {
            Mirai // initialize MiraiImpl first
            loadService(
                InternalShortVideoProtocol::class,
                "net.mamoe.mirai.internal.message.InternalShortVideoProtocolImpl"
            )
        }
```

2023-08-03 10:25 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/AbstractContact.kt
> +        }.readBytes().toExternalResource().use { resource ->
High memory usage

2023-08-03 10:25 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt
> +    }
不太适合放这里，换通用的

2023-08-03 10:32 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/contact/AbstractContact.kt
> +        }.readBytes().toExternalResource().use { resource ->
这块要怎么优化呢，packet能引用么

2023-08-03 10:33 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/AbstractContact.kt
> +        }.readBytes().toExternalResource().use { resource ->
继承 AbstractExternalResource 啊

2023-08-03 10:43 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Contact.kt
> +     * **无论上传是否成功都不会关闭 [resource]. 需要调用方手动关闭资源**
它这个是跟上面 `uploadImage` 对齐的

2023-08-03 10:47 UTC, StageGuard commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> +        }
直接从image那里copy的，一块加上吧

2023-08-03 10:48 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt
> +    }
refine context这个设计不是太好，打算之后重新设计一下，

2023-08-03 11:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/events/ShortVideoUploadEvent.kt
> +public data class BeforeShortVideoUploadEvent @MiraiInternalApi constructor(
```suggestion
public class BeforeShortVideoUploadEvent @MiraiInternalApi constructor(
```

2023-08-03 11:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/events/ShortVideoUploadEvent.kt
> +    public data class Succeed @MiraiInternalApi constructor(
```suggestion
    public class Succeed @MiraiInternalApi constructor(
```

2023-08-03 11:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/events/ShortVideoUploadEvent.kt
> +    public data class Failed @MiraiInternalApi constructor(
```suggestion
    public class Failed @MiraiInternalApi constructor(
```

2023-08-03 11:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/code/internal/impl.kt
> +    "svideo" to MiraiCodeParser(
我觉得没必要缩写成这个，就叫 shortvideo 吧

2023-08-03 11:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> +public interface ShortVideo : MessageContent, ConstrainSingle, CodableMessage {
`@NotSrtableForInheritance`

2023-08-03 11:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/AbstractContact.kt
> +        }.readBytes().toExternalResource().use { resource ->
自己实现一个 ExternalResource

2023-08-03 11:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/AbstractContact.kt
> +        }
没有广播事件

2023-08-03 11:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
> +            source?.fromId ?: first().msgHead.fromUin,
`first()` 看起来有概率抛异常

2023-08-03 11:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt
> +        }.cast<Contact>()
不要用 cast，必须要强转的时候就用 `as`，你这里不需要这个 cast

2023-08-03 11:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt
> +        }.cast<User>()
no cast

2023-08-03 11:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt
> +    }
别忘了

2023-08-03 11:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt
> +}
给 thumb 抽一个对象吧，这样以后可能好改一点

2023-08-04 04:29 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/code/internal/impl.kt
revert

2023-08-04 04:29 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> + *
delete

2023-08-04 04:29 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> + * [OnlineShortVideo] 仅可以从事件中的[消息链][MessageChain]接收, 不可手动构造. 若需要手动构造, 请使用 [ShortVideo.Builder] 构造 [离线短视频][OfflineShortVideo].
若需要手动构造.... 不适合放这里

2023-08-04 04:29 UTC, Karlatemp commented on mirai-core-api/src/jvmBaseMain/kotlin/contact/Contact.kt
> +     * @param fileName 文件名，如为 `null` 这根据 [video] 自动生成。
咱打错字了也不看一下就直接复制）

2023-08-04 04:29 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/AbstractContact.kt
> +    }
```
): ShortVideo = thumbnail.useAutoClosable {
video.useAutoClosable {
// .......
}
}
```

2023-08-04 04:29 UTC, Karlatemp commented on mirai-core/src/jvmBaseMain/kotlin/utils/ExternalResourceImpl.kt
> +    override val sha1: ByteArray by lazy { combine().sha1() }
忘了 InputStream.md5() 会不会关流了, 确认一下

2023-08-04 04:32 UTC, StageGuard commented on mirai-core/src/jvmBaseMain/kotlin/utils/ExternalResourceImpl.kt
> +    override val sha1: ByteArray by lazy { combine().sha1() }
会

2023-08-04 04:35 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/contact/AbstractContact.kt
> +    }
这个需要 auto close 么，我看 uploadImage 那边也没 auto close，这个应该是用户决定的吧

2023-08-04 04:39 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ExternalResourceImpl.kt
> +internal expect fun CombinedExternalResource(vararg resources: ExternalResource): ExternalResource
没必要 expect，直接在common写就行

2023-08-04 04:40 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/AbstractContact.kt
> +    }
那说明uploadImage可能有个bug，它理应要auto

2023-08-04 04:42 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> + *
我觉得有这个说明更好

2023-08-04 04:49 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/utils/ExternalResourceImpl.kt
> +internal expect fun CombinedExternalResource(vararg resources: ExternalResource): ExternalResource
那就要在 commonMain 里使用 InputStream 了

2023-08-04 08:34 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/utils/ExternalResourceImpl.kt
> +internal expect fun CombinedExternalResource(vararg resources: ExternalResource): ExternalResource
没有需要避免在 common 使用的理由

2023-08-06 14:00 UTC, Karlatemp approved these changes
short video.

关于 redefine 的修改还没看

2023-08-06 18:58 UTC, Him188 commented
这周末看一下

2023-08-12 05:46 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Contact.kt
> +        fileName: String? = null
mirai 已有 API 的命名为 `filename`, 可以统一一下

2023-08-12 05:46 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/events/ShortVideoUploadEvent.kt
> +@OptIn(MiraiInternalApi::class)
```suggestion
 *
 * @see Contact.uploadShortVideo 上传短视频. 为广播这个事件的唯一途径
 * @since 2.16
 */
@OptIn(MiraiInternalApi::class)
```

2023-08-12 05:46 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/event/events/ShortVideoUploadEvent.kt
> + */
```suggestion
 *
 * @see Succeed
 * @see Failed
 * @since 2.16
 */
```

2023-08-12 05:46 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> + *
```suggestion
 * ## 从服务器接收
 * 通过监听消息接收的短视频消息可直接转换为 [OnlineShortVideo].
 * ```kotlin
 * val video: OnlineShortVideo = event.message[OnlineShortVideo]
 * ```
```

2023-08-12 05:46 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> +        public var fileMd5: ByteArray = EMPTY_BYTE_ARRAY
我觉得它应该放到 `OfflineShortVideo` 里面,  `build` 可以返回 `OfflineShortVideo`, 因为 Online 的是不开放构造的

2023-08-12 05:46 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> +        public var thumbnailSize: Long = 0
```suggestion
        /**
         * 缩略图文件 MD5，仅通过 [Contact.uploadShortVideo] 获取的 [OfflineShortVideo] 获取.
         */
        public var thumbnailMd5: ByteArray = EMPTY_BYTE_ARRAY

        /**
         * 缩略图文件大小，仅通过 [Contact.uploadShortVideo] 获取的 [OfflineShortVideo] 获取.
         */
        public var thumbnailSize: Long = 0
```

2023-08-12 05:46 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> +        public var thumbnailSize: Long = 0
"仅通过"是什么意思? 意思是用户不应该自己指定这个值?

2023-08-12 05:46 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> +            }
既然这些都是必要参数, 那就不适合用 builder 模式(目前参数数量还不是特别多). 因为 builder 模式会导致参数都是可选提供的, 但你在 build 时又要求必须提供. 这就导致开发容易遗漏, 将一个能在静态编译阶段能检查的问题滞后到了运行时. 
我觉得将他们改为 newBuilder 提供比较好, 这虽然会导致 newBuilder 会有 6 个参数, 但我觉得是可以接受的 (对于 Kotlin 可以带参数名传参, 对于 Java 没办法)

2023-08-12 05:46 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> + * 内部短视频协议实现
```suggestion
 * 内部短视频协议实现, 请不要使用此接口
```

2023-08-12 05:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/roaming/TimeBasedRoamingMessagesImpl.kt
> +                                contact.bot,
大 lambda 要给 it 命名

2023-08-12 05:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/roaming/TimeBasedRoamingMessagesImpl.kt
>                          }
有代码重复, 之前可以那样写是因为就一行

2023-08-12 05:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
>      refineContext: RefineContext = EmptyRefineContext,
它应该加到 refine context 我觉得

2023-08-12 08:50 UTC, StageGuard commented on mirai-core-api/src/commonMain/kotlin/message/data/ShortVideo.kt
> +        public var thumbnailSize: Long = 0
这两个参数现在已经无意义了，原本是在解析 mirai 码时使用的，但是短视频消息的 mirai 码去掉了。
thumbnailMd5 和 thumbnailSize 是使构建的 OfflineShortVideo 在协议上更精确的参数，就像 Image 的 width 和 height 一样，但是在接口上 thumbnail 的信息是隐藏的。

2023-08-12 08:58 UTC, StageGuard commented on mirai-core/src/commonMain/kotlin/message/ReceiveMessageHandler.kt
>      refineContext: RefineContext = EmptyRefineContext,
那实际上 groupIdOrZero 和 messageSourceKind 也应该加到那里，正好在 RefineContextKey 的伴生对象里有

2023-08-16 12:53 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt
> +}
别忘了这个

2023-08-16 12:54 UTC, Him188 approved these changes

2023-08-16 15:07 UTC, Him188 requested changes

2023-08-16 15:07 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt
> +    @Transient val thumbHeight: Int = 0
构造器接收 val thumbnail: ShortVideoThumbnail

2023-08-17 10:55 UTC, Lawaxi commented
无比期待

2023-08-17 11:22 UTC, Lawaxi commented
Contact.uploadShortVideo必须要有缩略图吗

2023-08-17 11:27 UTC, StageGuard commented
> Contact.uploadShortVideo必须要有缩略图吗

协议上是需要。在 QQ 客户端中通常是自动截取视频文件中间的某一帧作为缩略图。但是 mirai 没有解码视频的能力，所以需要用户自行处理。

2023-08-20 04:03 UTC, Him188 approved these changes

2023-08-20 07:31 UTC, Karlatemp reviewed
No other issue

2023-08-20 07:31 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt
> +        } as User
mirai 可能有时候会同步不上全部联系人信息，这时候这个大块的 when 的返回值就是 null, 直接 as User 的报错信息只有个 xxx 不能为 null, 应该用 ` as User? ?: error("cannot find xxxxx")`

2023-08-20 07:31 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/message/protocol/impl/ShortVideoProtocol.kt
> +}
最好与 [shortVideo.kt](https://github.com/mamoe/mirai/pull/2739/files#diff-7c2da10f9eb62a17f535ae4ee75fc64b61a0d75998ea432a45b73ed60a8d0d5bR240-R253) 的 Int.toVideoFormat 合并，或者留个注释说明要更新需要同步更新

2023-08-20 10:41 UTC, merged

2023-08-20 10:42 UTC, landall commented
牛逼！