Fix qimei error -1 on Android
mamoe/mirai pull request #2753
Opened 2023-07-25 18:49 UTC by zhaodice

Base64居然敢自动换行！！直接导致qimei post 失败 error code -1 不解释！
https://github.com/mamoe/mirai/issues/2752

会导致直接post以下内容（多出了可恶的\n）：
```
{"key":"cKEwfBzaNDaW7k/1KvV612Lk857Zy6fNsBQnGioXLb6El0NB1daWh0N6daSOFuRH6w+BysDiMAuk\nRi5QpWyl1W0pOE32TswI1xii6ybp3DA2rpHwmBoaXYggDd7yG5IHIzaxwn6Y5rlqIRuGeoq9nOmg\nbtUc5QYoIWqrINH2CLY=\n","params":"AJoFBdx6izCswqsQUoR+zF1aQRaIg3fCrEpa2dNhdagm4zAoa1uyxCcLVzX/E8bD8tElS4zTMFJ3\nv0jGfbVxeIEWMvwcVTaxeLfzuPpbdrglqb2UnN/EsggsOzlF20ejqdhiWOEH/jugonPnPHdiJN3Q\nIMryE+AauV0batv5lXDSQFtUjXMxe0dkh2zrzMDEP7ptFcKDEY0DzzwXwx0DrrjvWwRtczqe4/fD\nMol0FFClQknqyjd2A2uqhgJqlV51o2RPY5FZaTFYiQbSxUJy+bUjm8i+/typ1+UFNHU2q2qt87Jb\nSAvnRbeZECV5hIFnhDh7RC45aphU4c+0mMHGemAiJTXXn+vax8i3Rvbc4E+hmjgiKLZv4GEW7HEy\nEkuI/WHTeL0y73uZi1UjE0m4+kkDO+10IPJDnEVOq0VEzipFWg/8khgYJIGxUN70skai/5ib/mZn\nbncrZlV3p6yTwIifQMjKfPa4kWgsoFpMCVCyfQAsELqXclNWxEmCwj1p2/Ox327+E08q/JT0TYWC\nQaNCiL6jTXE0B/Y/Gf9GOamBzGP3QBA+b0/RBGQOPAVjHvs7wyzAyCH+wmWqAiMmhpataWZeFtFi\nUgnnVj+SRQk/8dQHcStNfM4fmVWBP3DIwLQTjrmlrb2pVulTD7eYU6W+bBjtsJMgdXy3Kg0EV96I\n+6b3EXwIqn8xcUmVlxtX/hawJgTU982a/Hu+KUMOeKJBHrmmJTaVeIXeBpDUUhiC1ekY0RvCH8hX\nK2vKqoiHAxQd/60BvT+zr036xE4dyB2XQ9X+MdzOns8PT+9ss7KqOMVIh6BrO60ez1sND12aSk1G\ntArx6Wevyi6aAzzCQCNUzTkjgKg3dCfwnEXv+TAiYmq3VOJ7CGjS/HAy8nWImSlRjf8tBSs8uI73\nHuOviRitK+TmwaVftsbTUxFxfCxuL7Kxt4MhMkzxykPCzMyxeWaw9u5aZRM3gkQBlbTD0Lt1oshe\nnq0lveojWp9Rc2J8BgMvcUH42LVsImxVGxZ4ZzfXaLC4Z3nZWS8IzlTMhxQN0w6Chz/0EW30Bi+V\nQq65FVqmDGO3P2pXQ6pEH0hFZBkXrGB+NHqYqySKE+HbDZVyVIajkFgEdYr8UN9klupt5UPJAm2U\nVFuVdDfSwLQvdGJaDtC7wx1KNQAyguc0p6ezSTEs3Z8wNYpejJ0wIXz0zLipCGupcLIXwHkY0njE\nk+Uyod92gsLfKjGGWfaqPUyyHbjXg0IhGhj5Uy2M9I53N/WluKdZkQzK6sYzhNEFHukwhs4e2JmV\nW3CB3Olfk9LORjoha4u0i7oajZ+CJM7KQVNdfEDGvpNopFrJWacGX5jl8NrX5oscfeGUhcKMXStm\nGB+YDVGOV6UcjVXXIB/LfuarEFiae5ly3mHz/usCKndCXvHb5bT1+AnoSXj0bkdLR+rvZe7+/xFp\nm9mAuA2/VuV1jIuzzF0zZFR1giLVn98cjl+/SYbLRX6wottZzT7UoyQspAUnYEVM9FsR9QMs4LYN\na+iJavMKwbGO0WRM6kgLhPFrHbmvdEvfnnift0REF87r6QdopWawFEef9BmXndI8QdrT21rD+4m7\n6UbILG0q3WU2ThgkiwrR5T1e5Zmk3MJhVQxOrfTuZHNiZCeFjjG22dsCzZQIViBpgMe1YueDagwb\nsxvHCdYgS5kDZlsWTMWXT54OIDH8KWxH/2SaPm4lcuvuid2mB1ucVzbNK9PtU/eYZodoL2G0vRno\ncY9zHEn36FNWXoQFY5zDXPFVqbyj5q6Ams9vz6NOoRqNiWCAF1y5c9+YKxrKX/FvY4ufQtTlwfwL\nfHG3W1XQNplsmzybBwTfQfOnYX41GAHGlqAAnzvrQGk9YhCGXYTOxGpBza7l+AIxwuDPHj8DLSxq\n4lavbB5sFOV0AtgdrUAUzleCx3nC75UV6puNjN793XQDXFquA+4786gZkvVakoseHu1mBFSIc/X1\nCip0um4lyHDj0FS2UNyRkJMhPldElKDwTyAQHMgEE6ZEHt45A7gJTsv9+Us6+fuDNrCqx9JyXBIC\ns7iVjegXEGfANjVQl0y/IA8I/kvzQoLXRvvONkFDA1BkbZKz9jGtPjSfaLQlWA0TFM7euh3RzobP\nw6jtK8CiJaYucg3Y8hDusOrDLlswxKnFmtFhiD97LyBZbkahkzQLC2Cs9293d3sPbKeb5Q==\n","time":1690310597000,"nonce":"FycTMTsxw81w6znz","sign":"F98132300FAD4A6FF4EA385FAF9CBE1F","extra":""}
```

本补丁将不允许base64编码时夹带换行符，也不允许带换行符的base64被解码（解码前需要提前替换\n），与瘟斗士平台保持一致

2023-07-25 19:43 UTC, mikko-mikust commented
~~说实话不建议这么快pr的，这个函数有好几个地方都在用，你最好都试一下其他的地方有没有问题~~

2023-07-26 01:20 UTC, zhaodice commented
> ~说实话不建议这么快pr的，这个函数有好几个地方都在用，你最好都试一下其他的地方有没有问题~

这函数本身就不应该换行，windows平台就是没换行的，如果单纯去掉换行就出了问题...那windows平台应该早就出问题了

2023-07-26 03:18 UTC, zhaodice commented
经测试，安卓端一切正常：
![image](https://github.com/mamoe/mirai/assets/63996691/4628d117-b6bc-4df4-8915-16fc165d9fc5)

qimei已经正常获取
![image](https://github.com/mamoe/mirai/assets/63996691/12ecbf28-508d-41d3-8e89-a7f9c49da2d9)

2023-07-26 04:59 UTC, StageGuard commented
你快把我 review 的改了

2023-07-26 05:05 UTC, zhaodice commented
> 你快把我 review 的改了

咋改，没看见什么东西啊？

2023-07-26 05:07 UTC, mikko-mikust commented
> > ~说实话不建议这么快pr的，这个函数有好几个地方都在用，你最好都试一下其他的地方有没有问题~
> 
> 这函数本身就不应该换行，windows平台就是没换行的，如果单纯去掉换行就出了问题...那windows平台应该早就出问题了

就是你应该也去测一下调用这个函数的其他地方(使用的地方很少其实)，比如匿名群消息什么的

2023-07-26 05:12 UTC, StageGuard requested changes

2023-07-26 05:12 UTC, StageGuard commented on mirai-core-utils/src/androidMain/kotlin/Actuals.kt
> +    return Base64.encodeToString(this, Base64.NO_WRAP)
保持这个函数的默认行为(可以在参数加上默认值)

2023-07-26 05:12 UTC, StageGuard commented on mirai-core-utils/src/androidMain/kotlin/Actuals.kt
> +    return Base64.decode(this, Base64.NO_WRAP)
同上

2023-07-26 05:12 UTC, StageGuard commented
> > 你快把我 review 的改了
> 
> 咋改，没看见什么东西啊？

抱歉忘了点 submit review ;v;

2023-07-26 05:13 UTC, zhaodice commented
> > > 你快把我 review 的改了
> > 
> > 
> > 咋改，没看见什么东西啊？
> 
> 抱歉忘了点 submit review ;v;

这样是否会导致不一致？因为windows平台的base64是没有换行的

2023-07-26 05:14 UTC, StageGuard commented
> > > > 你快把我 review 的改了
> > > 
> > > 
> > > 咋改，没看见什么东西啊？
> > 
> > 
> > 抱歉忘了点 submit review ;v;
> 
> 这样是否会导致不一致？因为windows平台的base64是没有换行的

你测试一下（

2023-07-26 05:15 UTC, zhaodice commented on mirai-core-utils/src/androidMain/kotlin/Actuals.kt
> +    return Base64.encodeToString(this, Base64.NO_WRAP)
https://github.com/mamoe/mirai/blob/ee7461b08cc987f2a05c445658bb9984880eb0aa/mirai-core-utils/src/jvmMain/kotlin/Actuals.kt#L19 在jvmMain 里就没有这个参数，应该是不换行的，所以在安卓平台应该与其保持一致比较好？

2023-07-26 05:18 UTC, mikko-mikust commented
> > > > 你快把我 review 的改了
> > > 
> > > 
> > > 咋改，没看见什么东西啊？
> > 
> > 
> > 抱歉忘了点 submit review ;v;
> 
> 这样是否会导致不一致？因为windows平台的base64是没有换行的

~~如果有问题的话估计调用函数的地方都要改一下来适应 ~~

2023-07-26 05:19 UTC, zhaodice commented
```
fun main(args : Array<String>){
    println(java.util.Base64.getEncoder().encodeToString("1佛坪哼哼啊啊啊啊外人看来规划微软厉害了‘开了个好人与推理怕溜了人格与苹果·然后看完v可欧培亚航空，人【怕怕【更可怕融合给客人紧哦碰怕【；还不快来肉片啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊为我国·1opk-tfgm-423 投票去买全欧培儿歌看来人么和波兰取决于0 遇见50她以前吗，呕吐以加强亦哦v吗，53ioyb，奥胖同学，兼容问题迷哦吗加强哟怕".toByteArray()))
}
```
运行结果：
```
MeS9m+WdquWTvOWTvOWViuWViuWViuWViuWkluS6uueci+adpeinhOWIkuW+rui9r+WOieWus+S6huKAmOW8gOS6huS4quWlveS6uuS4juaOqOeQhuaAlea6nOS6huS6uuagvOS4juiLueaenMK354S25ZCO55yL5a6MduWPr+asp+WfueS6muiIquepuu+8jOS6uuOAkOaAleaAleOAkOabtOWPr+aAleiejeWQiOe7meWuouS6uue0p+WTpueisOaAleOAkO+8m+i/mOS4jeW/q+adpeiCieeJh+WViuWViuWViuWViuWViuWViuWViuWViuWViuWViuWViuWViuWViuWViuWViuS4uuaIkeWbvcK3MW9way10ZmdtLTQyMyDmipXnpajljrvkubDlhajmrKfln7nlhL/mrYznnIvmnaXkurrkuYjlkozms6LlhbDlj5blhrPkuo4wIOmBh+ingTUw5aW55Lul5YmN5ZCX77yM5ZGV5ZCQ5Lul5Yqg5by65Lqm5ZOmduWQl++8jDUzaW95Yu+8jOWlpeiDluWQjOWtpu+8jOWFvOWuuemXrumimOi/t+WTpuWQl+WKoOW8uuWTn+aAlQ==
```
没有出现换行，既然jvm原生都没有出现换行，安卓就没必要换行，所以NO_WRAP是可以的
总不能你这个mirai在jvm下base64不换行，在安卓下突然插个\n吧

2023-07-26 05:20 UTC, StageGuard commented on mirai-core-utils/src/androidMain/kotlin/Actuals.kt
> +    return Base64.encodeToString(this, Base64.NO_WRAP)
在 Android 和 JVM 的默认行为不一致的情况下， expect 函数的行为应该默认是 JVM 的行为。

2023-07-26 05:20 UTC, zhaodice commented
除非要换行都换行，绝对不能出现平台不同，编码结果不一样的情况

2023-07-26 05:22 UTC, StageGuard commented
> 除非要换行都换行，绝对不能出现平台不同，编码结果不一样的情况

那这样就没问题

2023-07-26 05:22 UTC, zhaodice commented
@StageGuard 我测过了，jvm下不会换行，测试代码在上面，不放心可以自己运行，jvm都不换行，android就没必要换行了吧，要保证行为一致呀

2023-07-26 05:22 UTC, StageGuard approved these changes

2023-07-26 05:25 UTC, merged