[core]修复从可确定图片类型的字符串组成的mirai code构造的图片type为UNKNOW或与期望类型不一致
mamoe/mirai pull request #2761
Opened 2023-07-29 23:19 UTC by Hamusuta0320

fix #2760

2023-07-30 02:57 UTC, Him188 reviewed
请添加单元测试

2023-07-30 02:57 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +    // 这里既然是未知格式，空串会不会好点，返回gif会可能造成歧义
这会发给服务器，你改了之后测试过吗？

2023-07-30 02:58 UTC, Him188 commented
测试失败了

```
LongMessageProtocolTest > can convert messages to LongMessageInternal() FAILED
    org.opentest4j.AssertionFailedError at LongMessageProtocolTest.kt:68
```

改完请使用 `./gradlew check` 测试通过后再提交

2023-07-30 04:29 UTC, Hamusuta0320 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +    // 这里既然是未知格式，空串会不会好点，返回gif会可能造成歧义
还没有 我测试一下

2023-07-30 12:32 UTC, Hamusuta0320 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +    // 这里既然是未知格式，空串会不会好点，返回gif会可能造成歧义
主动判断类型之后，`can convert messages to LongMessageInternal`这个测试用例会出问题，修改之后从服务器拿的resId会发生变化，目前不太清楚会不会影响一些根据resId操作的代码。UNKNOWN("gif")这里保持原样，不做修改。

2023-07-30 12:48 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
>          /**
提供初始化值，而不是 get 的时候替换

2023-07-30 13:52 UTC, Hamusuta0320 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
>          /**
get的时候计算会有什么问题呢 在初始值中计算会一直使用初始空串的imageId计算
或者在build方法中计算可以吗
```kotlin
public fun build(): Image {
    if(type == ImageType.UNKNOWN) type = ImageType.match(imageId.split(".").last())
    @OptIn(MiraiInternalApi::class)
    return InternalImageProtocol.instance.createImage(
        imageId = imageId,
        size = size,
        type = type,
        width = width,
        height = height,
        isEmoji = isEmoji,
    )
}
```

2023-07-31 03:05 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
>          /**
我觉得 get 时候也行

2023-07-31 03:38 UTC, Hamusuta0320 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
>          /**
get方式在ImageBuilder this的context中也可以判断type
build方式的只能拿到UNKNOW

2023-08-07 05:14 UTC, Him188 approved these changes

2023-08-08 07:48 UTC, Karlatemp approved these changes
format

2023-08-12 06:02 UTC, Him188 requested changes

2023-08-12 06:02 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Image.kt
> +            if(type == ImageType.UNKNOWN) type = ImageType.match(imageId.split(".").last())
```suggestion
            if (type == ImageType.UNKNOWN) {
                type = ImageType.match(imageId.split(".").last())
            }
```

2023-08-12 06:05 UTC, merged