Add low level api for getting group honor members list.
mamoe/mirai pull request #501
Opened 2020-08-17 16:03 UTC by yyuueexxiinngg

添加用于获取群荣誉数据的low level API, `enum`中字段参考官方字段值

已可获取:

| 数据 | 对应`enum` |
| ----- | ------------- |
| 龙王 | TALKATIVE　|
| 龙王 | TALKATIVE　|
| 龙王 | TALKATIVE　|
| 龙王 | TALKATIVE　|
| 龙王 | TALKATIVE　|
| 龙王 | TALKATIVE　|

2020-08-17 16:06 UTC, Him188 commented
Seems interesting.

2020-08-18 02:08 UTC, yyuueexxiinngg commented
更新:

- 移除代码中对群活跃等级称号设定的默认值, 因此项只在查询`活跃头衔`时会从服务器返回, 其余时均返回空对象, 设定默认值会导致其与群主设定的自定义活跃头衔不符
- 将`GroupHonorTypeSerializer`中序列化结果从`String`改为`Int`, 与反序列化统一

2020-08-18 02:21 UTC, yyuueexxiinngg commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/data/GroupHonorListData.kt
> +    val activeObj: PlaceHolder? = null,
此处`activeObj`以及下面`showActiveObj`仅在查询群荣誉类型`ACTIVE(7), 活跃头衔`时会返回(上方`enum`中已注释, 未支持), 其余时间返回空对象

查询此项时, 服务器返回的对象中`Key`的值不固定, 跟随群主设定的自定义头衔值, 举例:

当群使用默认活跃头衔时:

```js
activeObj = { 传说: Tag[] , 话唠: Tag[], ......, 冒泡: Tag[] }
``` 

当群使用默认活跃头衔时:

```js
activeObj = { 等级六: Tag[] , 等级五: Tag[], ......, 等级一: Tag[] }
```

2020-08-19 11:30 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/data/GroupHonorListData.kt
> +    val activeObj: PlaceHolder? = null,
可以直接根据数组下标确定等级，或者直接存储为List<Pair<Key,Value>>结果

2020-08-20 17:17 UTC, Cyenoch approved these changes

2020-09-01 12:19 UTC, Him188 requested changes

2020-09-01 12:19 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/data/GroupHonorListData.kt
> +public enum class GroupHonorType(public val value: Int) {
`@MiraiExperimentalAPI`,  
`@SinceMirai("1.3.0")`

2020-09-01 12:19 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/data/GroupHonorListData.kt
> +public data class GroupHonorListData(
`@SinceMirai("1.3.0")`

2020-09-01 12:19 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/data/GroupHonorListData.kt
> +        public fun fromInt(value: Int): GroupHonorType = values().first { it.value == value }
1. `@JvmStatic`.
2. `fromInt` 可能不拥有很明确的语义. 请更换, 或者删除它.

2020-09-02 17:46 UTC, yyuueexxiinngg commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/data/GroupHonorListData.kt
> +        public fun fromInt(value: Int): GroupHonorType = values().first { it.value == value }
已增加`@JvmStatic`, 将`fromInt `重命名为`deserializeFromInt`

考虑到此方法仅在`GroupHonorListData`的反序列方法中调用, 将其可见性改为了`internal`

目前保留此方法的原因是让`enum`直接绑定一个Int值, 此值为数据中的`type`字段, 以方便发送给服务器的查询时直接提交`Enum.value`, 亦方便对服务器返回`type`时进行反序列化 , 


因无需让用户手动通过Int反序列化, 故修改为`internal`

2020-09-14 23:34 UTC, Him188 approved these changes

2020-09-15 04:54 UTC, merged