Try to fix #358 according to @Mar8s comment
mamoe/mirai pull request #509
Opened 2020-08-18 13:53 UTC by sandtechnology

2020-08-18 14:03 UTC, Him188 commented
请问是否有测试过?

2020-08-18 14:19 UTC, sandtechnology commented
突然发现名字写错了 尴尬
进行过测试，TIM电脑端进行踢出操作和安卓端进行主动退出操作都有效

2020-08-18 23:47 UTC, Him188 requested changes

2020-08-18 23:47 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.PbPushTransMsg.kt
> +                                    BotLeaveEvent.Kick(group.members[operator]).broadcast()
如果是 bot 被踢，不应该广播 `MemberLeaveEvent`
此时还需要关闭  Group 对象，取消其作用域下所有协程，请参考OnlinePush.ReqPush中原处理方案：
```kotlin
return@lambda528 if (group != null && bot.groups.delegate.remove(group)) {
            group.cancel(CancellationException("Being kicked"))
            sequenceOf(BotLeaveEvent.Active(group))
        } else emptySequence()
```

2020-08-19 04:22 UTC, Him188 approved these changes

2020-09-12 07:46 UTC, Him188 approved these changes

2020-09-15 13:01 UTC, Him188 requested changes

2020-09-15 13:01 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.PbPushTransMsg.kt
> -                else -> {
为什么要删除这里的else?

2020-09-15 14:13 UTC, sandtechnology commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.PbPushTransMsg.kt
> -                else -> {
emmm，貌似else确实被移动到了内部，但是对代码执行没有影响

2020-09-15 14:16 UTC, sandtechnology commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.PbPushTransMsg.kt
> -                else -> {
是我疏忽了，确实影响代码执行，已做移动处理

2020-09-16 00:23 UTC, Him188 approved these changes

2020-09-16 00:23 UTC, merged