Support Nudge message
mamoe/mirai pull request #600
Opened 2020-09-13 14:03 UTC by sandtechnology

2020-09-13 16:27 UTC, Him188 requested changes

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/FriendImpl.kt
> +            "Please use android phone protocol!"
throw UnsupportedOperationException(' nudge is supported only with protocol ANDROID_PHONE')

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/FriendImpl.kt
> +        require(coolDown > 10000L) {
check()

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/MemberImpl.kt
> +    override suspend fun nudge() {
应该与 FriendImpl 尽可能共用这些代码

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/NudgeManager.kt
> +class NudgeManager {
删除

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/NudgeManager.kt
> +    internal object Nudge : OutgoingPacketFactory<Nudge.Response>("OidbSvc.0xed3") {
`NudgePacket`?

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                grayTip.msgTemplParam?.forEach {
forEach? Did you mean `map`?

即使它现在可能只有一个数据，但也不能这样 forEach 处理

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +            else -> {
在未实现时不要直接忽略

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +            1067L -> {
在未实现时不要直接忽略

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                body.msgTemplParam?.forEach {
与 0x14 问题相同

2020-09-13 16:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Member.kt
> +    @JvmSynthetic
JvmBlockingBridge 的方法不能 JvmSynthetic

2020-09-13 16:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Member.kt
> +     * 协议限制：手机协议 [MiraiProtocol.ANDROID_PHONE]
更改为 “需要使用 [手机协议][...]”

2020-09-13 16:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Friend.kt
> +    public abstract suspend fun nudge()
JvmBlockingBridge 的方法不能 JvmSynthetic

2020-09-13 16:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Member.kt
> +    public abstract suspend fun nudge()
Friend 和 Member 都适用这个方法，此方法应该放入 User

2020-09-13 16:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/friend.kt
> +public data class FriendNudgeEvent internal constructor(
抽象一个 UserNudgeEvent?

2020-09-13 16:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/friend.kt
> +    public val target: Friend,
一个好友的戳一戳目标是什么？

2020-09-13 16:27 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/group.kt
> +     * 戳一戳的目标
如果对象是 Bot，这个属性会怎么样？应该添加解释

2020-09-13 16:27 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                return@lambda528 emptySequence()
不要随意忽略未知协议 （else 忽略了所有情况）

若必须这么做，请添加注释说明原因。
否则添加一条网络日志提示。

2020-09-13 16:37 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Member.kt
> +    public abstract suspend fun nudge()
但是如何判断是Friend还是Member？
在kt中仍然是instanceof吗？

2020-09-13 16:38 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Member.kt
> +    public abstract suspend fun nudge()
只能这样做

2020-09-13 16:39 UTC, sandtechnology commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/NudgeManager.kt
> +class NudgeManager {
删除是指将类移动吗？
如果是，从目前的实现来看我没有找到合适的地方，能否指出一下呢？

2020-09-13 16:41 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/NudgeManager.kt
> +class NudgeManager {
直接把 NudgePacket 放置顶层即可，因为这个 `NudgeManager` 似乎显得没有必要

2020-09-13 16:42 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/contact/FriendImpl.kt
> +        require(coolDown > 10000L) {
备注：check 抛出 IllegalStateException，require 抛出 IlegalArfumentException. require 在此时更恰当

2020-09-13 16:52 UTC, sandtechnology commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                grayTip.msgTemplParam?.forEach {
这个实际上是一个`List<Pair<X,Y>>`的结构，我觉得要解析这么一个`List` forEach是唯一的办法了
有什么更好的实现方式吗？

2020-09-13 16:53 UTC, sandtechnology commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +            else -> {
将会与其他包一样做输出日志处理

2020-09-13 16:54 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/friend.kt
> +public data class FriendNudgeEvent internal constructor(
我感觉直接使用泛型化的`UserNudgeEvent`会更合适

2020-09-13 16:55 UTC, sandtechnology commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                return@lambda528 emptySequence()
将会与其他包一样做输出日志处理

2020-09-13 16:57 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/group.kt
> +     * 戳一戳的目标
对象是Bot会输出Bot对象的member，所以我觉得不必说明
但考虑到其他事件的event说明，将会添加解释

2020-09-13 16:59 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/friend.kt
> +    public val target: Friend,
这个目标可能是好友自身也可能是Bot，因此没有做说明

2020-09-13 17:01 UTC, sandtechnology commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +            1067L -> {
将会与其他包一样做输出日志处理

2020-09-13 22:53 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                grayTip.msgTemplParam?.forEach {
把 List map，每一项元素都解析，然后 `list.asSequence`

2020-09-13 22:55 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/friend.kt
> +    public val target: Friend,
那么就应该添加说明，尽量减少用户的问题

2020-09-14 11:26 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/friend.kt
> +public data class FriendNudgeEvent internal constructor(
考虑了一波放弃了 因为两者存在差别

2020-09-14 11:46 UTC, Him188 requested changes

2020-09-14 11:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/event/events/group.kt
> +     * 戳一戳的目标，如果对象是Bot则为Bot的Member对象
英文和中文之间要有一个空格，Bot 和 Member 需要引用 （`[Bot]`）

2020-09-14 11:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Friend.kt
> +     * 发送戳一戳自己的消息，冷却时间为10秒。
数字与中文之间加空格

英文与中文之间加空格

2020-09-14 11:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Friend.kt
> +     * 发送戳一戳好友的消息，冷却时间为10秒。
数字与中文之间加空格

2020-09-14 11:46 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/net.mamoe.mirai/contact/Member.kt
> +     * 发送戳一戳该成员的消息，冷却时间为10秒。
数字与中文之间加空格

2020-09-14 12:51 UTC, Him188 requested changes

2020-09-14 12:51 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/QQAndroidBotNetworkHandler.kt
> +        logger.info { "群组列表与群成员加载完成, 共 ${troopListData.groups.size} 个" }
请在其他 PR 独立修改这些内容

2020-09-14 12:51 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/QQAndroidBotNetworkHandler.kt
> +        logger.info { "好友列表加载完成, 共 ${currentFriendCount} 个" }
请在其他 PR 独立修改这些内容

2020-09-14 12:51 UTC, Him188 commented on mirai-core-qqandroid/src/commonMain/kotlin/net/mamoe/mirai/qqandroid/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +            else -> {
实际上并没有解决，我有空去改

2020-09-14 13:50 UTC, sandtechnology commented
因为我是不知道这个玩意是在mirai什么时候才会加入的，能否提供一下版本号以便加入SinceMirai注解呢

2020-09-14 15:08 UTC, Him188 approved these changes

2020-09-14 15:09 UTC, Him188 commented
我会在merge之后添加注解

2020-09-15 13:17 UTC, merged