Simplify DeviceInfo
mamoe/mirai pull request #655
Opened 2020-10-24 13:04 UTC by AdoptOSS

*Note: breaking changes that may apply to v2.0 only*
# Reason
简化`DeviceInfo`的设计，去除原有的复杂继承体系，直接在common中实现
从语义角度上来讲，`DeviceInfo`被设计为一个**数据类**似乎更好，没有将`DeviceInfo`派生出各种子类的必要
没有必要弄出一个复杂的MPP架构实现
各种设备信息实现方式，可以使用适当参数创建`DeviceInfo`对象，无需派生出不同子类
原有的`SystemDeviceInfo`和`DeviceInfoData`高度重复，可能有违代码复用的精神

在Android平台下，Default device info设计为随机（原为读取本机信息），理由如下：
- 与其它平台统一，且便于common实现
- 几乎所有的文档、注释都假定默认情况为随机（原有实现与文档不符）
- 在Android平台获取设备信息需要额外的权限，默认获取本机信息可能会导致开发部署更加复杂
- 获取设备信息有个人隐私安全上的风险，没有必要作为默认选项
- Mirai鼓励用户设置Device Info Supplier，且提供了DSL，如有必要，用户选择使用Android本机信息也是极其简单的

# Main Change
删除`SystemDeviceInfo`和`DeviceInfoData`，直接使用`DeviceInfo`（原为抽象类）
不再在`DeviceInfo`保存`Context`（数据类设计为上下文无关似乎更好）
# Solve
可能缓解#648，避免序列化与反序列化使用不同class（这是不提倡的）造成的风险和额外的维护成本
# About Android
https://github.com/mamoe/mirai/blob/a774b8a7062fbd26742b7eb73896294fa6ab01b0/mirai-core/src/androidMain/kotlin/net/mamoe/mirai/utils/SystemDeviceInfo.android.kt#L47-L52
原有的Android平台实现将来可以实现为一个***android-specific supplier***，这样实现的可扩展性也会更好
https://github.com/mamoe/mirai/blob/6b7365d24c9845bc0818fbd6c4889d42c1acf573/mirai-core-api/src/commonMain/kotlin/utils/BotConfiguration.common.kt#L40-L45

2020-10-24 13:55 UTC, Karlatemp requested changes

2020-10-24 13:55 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/StringUtils.kt
> +
缺少 Copyright

2020-10-24 13:55 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/StringUtils.kt
> +
整个文件都由 `internal` 修饰, 因此请将此文件放置于 `mirai/mirai-core-api/src/commonMain/kotlin/utils/internal/` 下并更换包为 `net.mamoe.mirai.utils.internal`

2020-10-24 16:17 UTC, Karlatemp approved these changes

2020-10-24 16:20 UTC, Him188 requested changes

2020-10-24 16:20 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/DeviceInfo.kt
> +        public fun random(): DeviceInfo {
`@JvmStatic`

2020-10-24 16:26 UTC, Him188 requested changes
见评论

2020-10-25 00:22 UTC, Him188 approved these changes

2020-10-25 00:23 UTC, Him188 commented
感谢你的帮助，这个修改将会包含在 2.0-M1

2020-10-27 00:57 UTC, merged