fix bkn calculate error.
mamoe/mirai pull request #671
Opened 2020-11-06 05:53 UTC by jihuayu

fix bkn calculate error.
fix compile error.

2020-11-06 06:02 UTC, Him188 requested changes

2020-11-06 06:04 UTC, Him188 commented
`fold` 的结果就是 `Int`, 对 `Int` 位与 `2147483647` 是否有实际作用?

2020-11-06 06:29 UTC, ryoii commented
`fold` 返回 Int 会溢出，负数的 bkn 不知道有没有影响

2020-11-06 06:32 UTC, jihuayu commented
我试过了，加了这个代码就对了。
如果不这么做就不行。
我看了网络上的代码，也有这一步。


 
---Original---
From: "ryoii"<notifications@github.com&gt;
Date: 2020/11/6 14:29:38
To: "mamoe/mirai"<mirai@noreply.github.com&gt;;
Cc: "Author"<author@noreply.github.com&gt;;"纪华裕"<8042833@qq.com&gt;;
Subject: Re: [mamoe/mirai] fix bkn calculate error. (#671)




 
fold 返回 Int 会溢出，负数的 bkn 不知道有没有影响
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-11-06 07:18 UTC, jihuayu commented on mirai-core/src/commonMain/kotlin/QQAndroidBot.common.kt
> +            .fold(5381) { acc: Int, b: Byte -> acc + acc.shl(5) + b.toInt() }.and(2147483647)
改好了

2020-11-06 14:16 UTC, Him188 requested changes

2020-11-06 14:16 UTC, Him188 commented on mirai-core-api/src/jvmMain/kotlin/findMiraiInstance.kt
> +    return ServiceLoader.load(Mirai::class.java).firstOrNull()
与 'fix bkn calculate error.' 无关. 不应该在此 PR 中包含.

2020-12-18 10:17 UTC, Him188 commented
@jihuayu  由于长时间没有收到修改回复, 我们会在近期以你作为作者提交并关闭这个 PR.

2020-12-18 10:27 UTC, closed without merging