发送音乐卡片
mamoe/mirai pull request #690
Opened 2020-11-30 15:20 UTC by wdvxdr1123

#682 

不会kt，xjb写的 (给点指导

2020-11-30 15:23 UTC, Him188 commented
感谢你的帮助. mirai 正在进行架构调整, 因此会稍晚处理这个 PR

2020-11-30 15:26 UTC, wdvxdr1123 commented
我是写到一半不知道怎么写了, QAQ ( mirai代码有点看不懂，能给点指南就好了

2020-11-30 15:28 UTC, Him188 commented
在 2.0 重构后将会添加相关协议和内部实现文档

2020-12-01 14:30 UTC, Karlatemp requested changes
若需要添加一个新功能, 请在 (`mirai-core-api`>`Group.kt`) 提供相关api和文档说明

`MusicType` 可考虑移动至 `mirai-core-api`

2020-12-20 00:24 UTC, Him188 commented
2.0-M2 将会添加协议实现的文档，因此我把这个 PR 推迟到 2.0-M3。你可以在这期间查阅文档。

2021-01-22 01:51 UTC, Him188 commented
我会根据你的逻辑重新实现它

2021-01-22 04:09 UTC, Him188 commented
#889

2021-01-22 04:09 UTC, closed without merging

2021-01-22 04:14 UTC, wdvxdr1123 commented
感谢