Update QQ original faces name & Add missed channel check
mamoe/mirai pull request #720
Opened 2020-12-17 05:08 UTC by sandtechnology

2020-12-17 05:13 UTC, Him188 requested changes

2020-12-17 05:13 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/QQAndroidBotNetworkHandler.kt
> +        check(channel.isOpen) { "network channel is closed" }
每个 PR 只能处理一件事情

2020-12-17 05:13 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
> +        public val id2StringMap: Map<Int, String> = buildMap {
这个属性并不需要公开。
可以改成 internal array, 像之前那样实现

2020-12-17 05:13 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
> +@ExperimentalStdlibApi
删除此行

2020-12-17 05:13 UTC, Karlatemp requested changes

2020-12-17 05:13 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
>  @Serializable
`@OptIn(ExperimentalStdlibApi::class)`

2020-12-17 05:13 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
> +            9 to "大哭"
缺少 `[]`, 命名建议为 `id2name`

2020-12-18 10:20 UTC, Him188 requested changes

2020-12-18 10:20 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
> +    public val name: String = contentToString().let { it.substring(1, it.length - 1) }
应写 `public val name: String get() = `

2020-12-18 10:36 UTC, Him188 approved these changes

2020-12-18 10:44 UTC, Karlatemp approved these changes

2020-12-20 00:09 UTC, Him188 requested changes
保持统一命名方式

2020-12-20 00:09 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
> +        public const val OK: Int = 124
应该叫 HAO 和 `好`

2020-12-20 00:09 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Face.kt
> +        public const val NO: Int = 123
应该叫 BU 和 `不`

2020-12-20 12:59 UTC, Him188 approved these changes

2020-12-20 12:59 UTC, merged