Fix #577
mamoe/mirai pull request #728
Opened 2020-12-18 17:42 UTC by sandtechnology

2020-12-18 17:47 UTC, Him188 requested changes

2020-12-18 17:47 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Voice.kt
> +    public val codec: Int = 0,
internal 或者 `@MiraiInternalApi`

2020-12-18 17:47 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/Voice.kt
> +    public val codec: Int = 0,
不过 Voice 还会有修改，现在留着 public 也不错

2020-12-18 17:48 UTC, Him188 approved these changes

2020-12-18 17:50 UTC, sandtechnology commented on mirai-core-api/src/commonMain/kotlin/message/data/Voice.kt
> +    public val codec: Int = 0,
考虑了下文件解析 这个未来应该会用enum代表，目前来说可以用于文件类型识别
其实语音还有一堆东西没做（如果要做私聊），不过那是未来的事情了

2020-12-19 18:58 UTC, CL-Jeremy commented
请问现在的状态下直接构建使用时，报 `java.lang.NoSuchMethodError: net/mamoe/mirai/message/data/Voice.<init>(Ljava/lang/String;[BJLjava/lang/String;)V` 是因为当前插件无权访问这个方法吗（虽然只是正常调用包装的 API）？使用 `mirai-api-http` 1.9.0 配合 1.x 或 1.9.2 配合 2.0-M1-1 均显示同样错误。

2020-12-19 20:25 UTC, CL-Jeremy commented
刚刚又进行了一点测试：https://github.com/CL-Jeremy/mirai/commit/ac041492168315d579629ec611deef3b4d003f89
```
2020-12-20 05:00:27 I/Net XXXXXXXXX: Codec ID is: 1
2020-12-20 05:00:27 V/Net XXXXXXXXX: Send: PttStore.GroupPttUp
2020-12-20 05:00:27 V/Net XXXXXXXXX: Recv: RequireUpload(fileId=1648046745, uKey=[48, -127, -110, 2, 1, 1, 4, -127, -118, 48, -127, -121, 2, 1, 1, 2, 1, 1, 2, 4, -80, -120, -125, 121, 2, 2, 0, -1, 2, 4, -74, 2, -38, -54, 4, 16, -46, -111, 109, 62, -122, 58, -80, -60, 68, -73, 32, 41, 58, -31, 34, -100, 2, 1, 2, 2, 3, 0, -90, -47, 4, 16, -46, -111, 109, 62, -122, 58, -80, -60, 68, -73, 32, 41, 58, -31, 34, -100, 2, 4, 95, -34, 91, -37, 4, 36, 104, 48, 104, 54, 78, 67, 118, 80, 98, 51, 98, 121, 51, 67, 68, 81, 104, 83, 67, 102, 54, 71, 51, 73, 52, 106, 81, 74, 119, 65, 121, 101, 120, 98, 50, 68, 2, 3, 15, 82, 89, 2, 4, -79, -7, -51, -53, 2, 4, 86, -8, -51, -53, 2, 4, -100, 34, -31, 58, 4, 0, 4, 0])
2020-12-20 05:00:27 V/Net XXXXXXXXX: [Highway] Uploading ptt to 203.205.249.177:80, size=41.7 KiB
2020-12-20 05:00:27 V/Net XXXXXXXXX: [Highway] Uploading ptt: succeed at 78 KiB/s
```
收到的依然是一个 10.3 kB 大小的 AMR……

2020-12-20 00:10 UTC, merged

2020-12-20 03:31 UTC, sandtechnology commented
别问 问就是上传方式有问题（ 
目前我没能力修复