ExternalResource
mamoe/mirai pull request #754
Opened 2020-12-22 16:32 UTC by Him188

2020-12-23 05:01 UTC, Karlatemp requested changes

2020-12-23 05:01 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalImage.kt
> +    override fun inputStream(): InputStream = file.inputStream()
未对 file 进行复位操作 `this.seek(0)`

2020-12-23 05:01 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalImage.kt
> +    override fun close() {}
同上

2020-12-23 05:02 UTC, Karlatemp commented
且需要对资源释放的时机进行讨论, 保持发完就释放或由调用者自行释放

2020-12-23 05:43 UTC, Him188 commented
> 且需要对资源释放的时机进行讨论, 保持原本发完就释放 或 改为 由调用者自行释放

我觉得发完就释放比较好

2020-12-23 14:37 UTC, Karlatemp requested changes

2020-12-23 14:37 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +}
上下 `inputStream` 方法实现不一致

2020-12-23 16:27 UTC, Him188 reviewed
感觉不支持 BufferedImage 更好？

2020-12-23 16:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/IMirai.kt
> +    public var FileCacheStrategy: FileCacheStrategy
要删除 `BotConfiguration.FileCacheStrategty`

2020-12-23 16:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/contact/Contact.kt
> +        public suspend fun <C : Contact> C.sendImage(bufferedImage: BufferedImage): MessageReceipt<C> =
format

2020-12-23 16:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/SendImageUtilsJvmKt.kt
> +public suspend inline fun <C : Contact> BufferedImage.sendAsImageTo(contact: C): MessageReceipt<C> =
format

2020-12-23 16:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/SendImageUtilsJvmKt.kt
> +public suspend inline fun BufferedImage.uploadAsImage(contact: Contact): Image =
format

2020-12-23 16:27 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/SendImageUtilsJvmKt.kt
> +public suspend inline fun Contact.uploadImage(bufferedImage: BufferedImage): Image = bufferedImage.uploadAsImage(this)
format

2020-12-25 14:50 UTC, Karlatemp requested changes
uploadImage 的资源处理与 Conversation 中的决定不符合

2020-12-25 14:50 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt
>      }
在 Conversation 中确定资源在上传后即释放, 然而实际代码实现并没有做到

2020-12-25 14:50 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
>      }
在 Conversation 中确定资源在上传后即释放, 然而实际代码实现并没有做到

2020-12-25 14:50 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
> +    override suspend fun uploadImage(image: ExternalResource): Image = image.use { _ ->
在 Conversation 中确定资源在上传后即释放, 然而实际代码实现并没有做到

2020-12-25 14:50 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt
> +    override suspend fun uploadImage(image: ExternalResource): Image = image.use { _ ->
在 Conversation 中确定资源在上传后即释放, 然而实际代码实现并没有做到

2020-12-25 14:54 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
> +    override suspend fun uploadImage(image: ExternalResource): Image = image.use { _ ->
`image.use { _ ->` 不是做到了吗

2020-12-25 14:55 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt
> +    override suspend fun uploadImage(image: ExternalResource): Image = image.use { _ ->
近视了(((

2020-12-25 14:56 UTC, Him188 commented
似乎对于 `ExternalResource` 来说不应该释放？因为 stdlib Stream 的类似方法都是不自动释放

2020-12-25 15:05 UTC, Karlatemp commented
主要的 `uploadXXX` 应不自动关闭， 按照语义来讲应该是仅 upload 而不应该顺便 close

如 `InputStream.sendAsXXX` 等扩展则可以考虑是否应该自动关闭，`InputStream.sendAsXXXX` 等方法我认为也是不应该关闭的，因为 user 一般都会使用 `inputStream.use { stream -> .... }` 以确保资源的正确关闭

2020-12-26 07:55 UTC, Him188 commented
现在所有的操作都不会自动关闭

2020-12-26 08:23 UTC, Karlatemp requested changes

2020-12-26 08:23 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +    public fun inputStream(): InputStream
`关闭此流不会关闭 [ExternalResource].`

2020-12-26 08:23 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +            ExternalResourceImplByFile(this, formatName, closeOriginalFileOnClose)
`@Throws(IOException::class)`

2020-12-26 08:23 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/SendImageUtilsJvmKt.kt
> +@file:JvmName("SendImageUtilsJvmKt")
鉴于此文件存在 `uploadAsGroupVoice`, 名为 `SendResourceUtilsJvmKt` 是否会更好?

2020-12-26 09:02 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +            ExternalResourceImplByFile(this, formatName, closeOriginalFileOnClose)
这个方法不会进行 IO 操作

2020-12-26 09:06 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +            ExternalResourceImplByFile(this, formatName, closeOriginalFileOnClose)
上方 `File.toExternalResource(formatName: String? = null)` 中存在

2020-12-26 09:11 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/utils/ExternalResource.kt
> +            ExternalResourceImplByFile(this, formatName, closeOriginalFileOnClose)
确实，不过它抛的是 `FileNotFoundException`，以 Kotlin 习惯不需要指定异常
声明抛出 IOException 通常是为了阻止在协程环境调用这些 BIO，而这里没有 BIO （？）

2020-12-26 09:29 UTC, Karlatemp approved these changes

2020-12-26 09:36 UTC, merged