Support MarketFace
mamoe/mirai pull request #761
Opened 2020-12-24 11:52 UTC by sandtechnology

2020-12-24 12:05 UTC, Him188 requested changes

2020-12-24 12:05 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/faceImpl.kt
> +    companion object Key :
impl 不应该有 key

2020-12-24 12:05 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/HummerMessage.kt
> +    override val key: MessageKey<MarketFace>
应该在这里实现key

2020-12-24 12:05 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/HummerMessage.kt
> +public interface MarketFace : CodableMessage, MessageContent, ConstrainSingle {
此类型不是 HummerMessage 子类，就不应该放在 HummerMessage.kt

2020-12-24 12:10 UTC, sandtechnology commented on mirai-core-api/src/commonMain/kotlin/message/data/HummerMessage.kt
> +public interface MarketFace : CodableMessage, MessageContent, ConstrainSingle {
那应该放在外面吗？因为是接口的原因无法继承HummerMessage（

2020-12-24 16:12 UTC, Him188 requested changes

2020-12-24 16:12 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/message/data/HummerMessage.kt
> +        AbstractPolymorphicMessageKey<MessageContent, MarketFace>(MessageContent, { it.safeCast() })
baseKey 应该是 HummerMessage

2020-12-25 03:19 UTC, Him188 approved these changes

2020-12-25 13:32 UTC, merged