Support Stranger
mamoe/mirai pull request #795
Opened 2020-12-30 16:18 UTC by sandtechnology

2020-12-31 06:39 UTC, Him188 requested changes

2020-12-31 07:00 UTC, Him188 requested changes

2020-12-31 07:00 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/list/StrangerList.kt
> +        var seq = 0
`object GetStrangerList` 是静态的，mirai 允许多 bot 实例，这个 `seq` 会被所有 bot 共享

2020-12-31 07:00 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/list/StrangerList.kt
> +        var seq = 0
应该移动到 `QQAndroidClient`

2020-12-31 07:01 UTC, Him188 requested changes

2020-12-31 07:01 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/UserInfo.kt
> +    public val id: Long
协议内部接口使用 `uin`

2020-12-31 07:05 UTC, Him188 requested changes

2020-12-31 07:05 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/QQAndroidBot.kt
> +    override val asStranger: Stranger get() = Mirai._lowLevelNewStranger(bot, StrangerInfoImpl(bot.id, bot.nick))
```suggestion
    override val asStranger: Stranger = Mirai._lowLevelNewStranger(bot, StrangerInfoImpl(bot.id, bot.nick))
```

2020-12-31 09:31 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/message/offlineSourceImpl.kt
> +    val bot: Bot?,
需要bot实例帮助判断是否为陌生人信息，bot为null时默认好友

2020-12-31 09:32 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/QQAndroidBot.kt
> +    override val asStranger: Stranger get() = Mirai._lowLevelNewStranger(bot, StrangerInfoImpl(bot.id, bot.nick))
如果使用get会提示使用到的参数`bot.nick`是惰性初始化的 将会更改为惰性初始化

2020-12-31 09:32 UTC, sandtechnology commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/list/StrangerList.kt
> +        var seq = 0
如果移动到`QQAndroidClient` 那应该是`strangerSeq`？

2020-12-31 09:37 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/QQAndroidBot.kt
> +    override val asStranger: Stranger get() = Mirai._lowLevelNewStranger(bot, StrangerInfoImpl(bot.id, bot.nick))
可以 `by lazy { }`

2020-12-31 09:39 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/message/offlineSourceImpl.kt
> +    val bot: Bot?,
那不需要 `val`

2020-12-31 11:10 UTC, sandtechnology commented
除上传图片功能不可用（好友私聊也有此bug）外其余功能测试完毕，因此Ready for review

2020-12-31 18:11 UTC, Him188 approved these changes

2020-12-31 18:13 UTC, Him188 commented
在 `QQAndroidBot` close 或 `QQAndroidBotNetworkHandler` close 时有同时 close 一些 ContactList 实例（或 clear），（现有对 Bot.friends 和 Bot.groups 的处理）也需要对 Bot.strangers 做这样的处理

2021-01-01 07:49 UTC, Him188 commented
> 在 `QQAndroidBot` close 或 `QQAndroidBotNetworkHandler` close 时有同时 close 一些 ContactList 实例（或 clear），（现有对 Bot.friends 和 Bot.groups 的处理）也需要对 Bot.strangers 做这样的处理

network/QQAndroidBotNetworkHandler.kt:382

2021-01-01 07:50 UTC, Him188 commented
> > 在 `QQAndroidBot` close 或 `QQAndroidBotNetworkHandler` close 时有同时 close 一些 ContactList 实例（或 clear），（现有对 Bot.friends 和 Bot.groups 的处理）也需要对 Bot.strangers 做这样的处理
> 
> network/QQAndroidBotNetworkHandler.kt:382

发现这个PR处理到了

2021-01-01 13:39 UTC, merged