Syncing when joined group by other client & Add missed invitor in invite event
mamoe/mirai pull request #804
Opened 2021-01-02 16:41 UTC by sandtechnology

Fix #478

2021-01-02 17:33 UTC, Karlatemp requested changes

2021-01-02 17:33 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/event/events/group.kt
>      }
`invitor` 一定是 `NormalMember`

toString 没有添加新字段值

2021-01-02 17:33 UTC, Karlatemp commented on mirai-core-api/src/commonMain/kotlin/event/events/group.kt
>      }
```suggestion
        public override val member: NormalMember,
        /**
         * 邀请者
         */
        public val invitor: NormalMember
    ) : MemberJoinEvent(member) {
        public override fun toString(): String = "MemberJoinEvent.Invite(member=${member.id}, invitor=${invitor.id})"
    }
```

2021-01-05 04:40 UTC, Him188 requested changes

2021-01-05 04:40 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/chat/receive/OnlinePush.ReqPush.kt
> +                    1, 2 -> bot.launch(bot.network.coroutineContext) {
```suggestion
                    1, 2 -> bot.network.launch {
```

2021-01-05 04:59 UTC, Him188 approved these changes

2021-01-05 05:54 UTC, sandtechnology commented
Conflicts solved

2021-01-05 09:27 UTC, Him188 commented
感谢你的帮助

2021-01-05 09:27 UTC, merged