Support detect official bot, fix #439
mamoe/mirai pull request #810
Opened 2021-01-04 12:00 UTC by sandtechnology

2021-01-05 15:34 UTC, Karlatemp requested changes

2021-01-05 15:34 UTC, Karlatemp commented on mirai-core/src/commonMain/kotlin/utils/string.kt
> +
`internal`

2021-01-08 12:29 UTC, Karlatemp approved these changes

2021-01-12 12:36 UTC, Him188 approved these changes

2021-01-14 11:35 UTC, Him188 approved these changes

2021-01-20 09:27 UTC, Him188 commented
@sandtechnology 请更新 dev 分支的修改

2021-01-20 10:16 UTC, sandtechnology commented
@Him188 OK了

2021-01-20 11:20 UTC, merged