UserProfile query
mamoe/mirai pull request #866
Opened 2021-01-17 09:50 UTC by Karlatemp

close #637

TODO:
- [ ] 完成查询已经是好友的信息, 目前方式查询对象为好友时没有详细信息
- [ ] 完善文档
- [ ] 完善 API 设计

2021-01-17 10:35 UTC, Him188 requested changes

2021-01-17 10:35 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/LowLevelApiAccessor.kt
> +    public suspend fun queryProfile(bot: Bot, targetId: Long): UserProfile
看起来可它比较稳定, 可以作为高级 API

2021-01-17 10:35 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/profile/UserProfile.kt
> +package net.mamoe.mirai.profile
net.mamoe.mirai.data

2021-01-17 10:35 UTC, Him188 commented on mirai-core/src/commonMain/kotlin/network/protocol/packet/summarycard/SummaryCard.kt
> +                                vReq0x5ebFieldId = listOf(
展开太长了, 可以只分2-3行

2021-01-20 09:37 UTC, Him188 commented on mirai-core-api/src/commonMain/kotlin/data/UserProfile.kt
> +    public val sex: Int
maybe enum?
MALE, FEMALE, (保密),

保密 by default

2021-01-21 10:59 UTC, Him188 approved these changes

2021-01-21 11:00 UTC, Him188 commented
> 完成查询已经是好友的信息, 目前方式查询对象为好友时没有详细信息

可以单独开一个 issue 推迟到 2.2.0 做, 如果它很复杂的话

2021-01-21 14:13 UTC, Karlatemp commented
> > 完成查询已经是好友的信息, 目前方式查询对象为好友时没有详细信息
> 
> 可以单独开一个 issue 推迟到 2.2.0 做, 如果它很复杂的话

她很迷，刚编写时会缺少部分信息，然后不知道为啥最近几次测试又完整了，反正她现在能用

2021-01-21 23:47 UTC, Him188 commented
> > > 完成查询已经是好友的信息, 目前方式查询对象为好友时没有详细信息
> > 
> > 
> > 可以单独开一个 issue 推迟到 2.2.0 做, 如果它很复杂的话
> 
> 她很迷，刚编写时会缺少部分信息，然后不知道为啥最近几次测试又完整了，反正她现在能用

那我觉得可以等出问题了再修复

2021-01-21 23:47 UTC, merged